pcilib: bank.h File Reference
bank.h File Reference
#include <pcilib.h>
Data Structures
struct pcilib_register_protocol_api_description_t
struct pcilib_register_protocol_description_t
struct pcilib_register_bank_description_t
struct pcilib_register_range_t
Default mappings: defines virtual address to register mappings, i.e.
struct pcilib_register_bank_context_s
Macros
#define PCILIB_REGISTER_BANK_INVALID ((pcilib_register_bank_t)-1)
#define PCILIB_REGISTER_BANK0 0
First BANK to be used in the event engine.
#define PCILIB_REGISTER_BANK1 1
#define PCILIB_REGISTER_BANK2 2
#define PCILIB_REGISTER_BANK3 3
#define PCILIB_REGISTER_BANK_CONF 64
Configuration registers.
#define PCILIB_REGISTER_BANK_PROPERTY 65
Registers abstracting properties and other computed registers.
#define PCILIB_REGISTER_BANK_DMACONF 96
DMA configuration in the software registers.
#define PCILIB_REGISTER_BANK_DMA 97
First BANK address to be used by DMA engines.
#define PCILIB_REGISTER_BANK_DMA0 PCILIB_REGISTER_BANK_DMA
First BANK address to be used by DMA engines.
#define PCILIB_REGISTER_BANK_DMA1 (PCILIB_REGISTER_BANK_DMA + 1)
Second BANK address to be used by DMA engines.
#define PCILIB_REGISTER_BANK_DMA2 (PCILIB_REGISTER_BANK_DMA + 2)
Third BANK address to be used by DMA engines.
#define PCILIB_REGISTER_BANK_DMA3 (PCILIB_REGISTER_BANK_DMA + 3)
Fourth BANK address to be used by DMA engines.
#define PCILIB_REGISTER_BANK_DYNAMIC 128
First BANK address to map dynamic XML configuration.
#define PCILIB_REGISTER_PROTOCOL_INVALID ((pcilib_register_protocol_t)-1)
#define PCILIB_REGISTER_PROTOCOL0 0
First PROTOCOL address to be used in the event engine.
#define PCILIB_REGISTER_PROTOCOL_DEFAULT 64
Default memmap based protocol.
#define PCILIB_REGISTER_PROTOCOL_SOFTWARE 65
Software registers.
#define PCILIB_REGISTER_PROTOCOL_PROPERTY 66
Protocol to access registers interfacing properties.
#define PCILIB_REGISTER_PROTOCOL_DMA 96
First PROTOCOL address to be used by DMA engines.
#define PCILIB_REGISTER_PROTOCOL_DYNAMIC 128
First PROTOCOL address to be used by plugins.
Typedefs
typedef uint8_t pcilib_register_bank_t
Type holding the bank position within the field listing register banks in the model.
typedef uint8_t pcilib_register_bank_addr_t
Type holding the bank address number.
typedef uint8_t pcilib_register_protocol_t
Type holding the protocol position within the field listing register protocols in the model.
typedef uint8_t pcilib_register_protocol_addr_t
Type holding the protocol address.
typedef struct pcilib_register_bank_context_s pcilib_register_bank_context_t
Enumerations
enum pcilib_model_modification_flags_t { PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT = 0 , PCILIB_MODEL_MODIFICATION_FLAG_OVERRIDE = 1 , PCILIB_MODEL_MODIFICATION_FLAG_SKIP_EXISTING = 2 }
enum pcilib_address_resolution_flags_t {
PCILIB_ADDRESS_RESOLUTION_FLAGS_DEFAULT = 0 , PCILIB_ADDRESS_RESOLUTION_FLAG_BUS_ADDRESS = 1 , PCILIB_ADDRESS_RESOLUTION_FLAG_PHYS_ADDRESS = 2 , PCILIB_ADDRESS_RESOLUTION_MASK_ADDRESS_TYPE = 3 ,
PCILIB_ADDRESS_RESOLUTION_FLAG_READ_ONLY = 4 , PCILIB_ADDRESS_RESOLUTION_FLAG_WRITE_ONLY = 8 , PCILIB_ADDRESS_RESOLUTION_MASK_ACCESS_MODE = 12
}
Functions
int pcilib_init_register_banks (pcilib_t *ctx)
Initalizes context of register banks.
void pcilib_free_register_banks (pcilib_t *ctx, pcilib_register_bank_t start)
Destroys contexts of register banks.
int pcilib_add_register_banks (pcilib_t *ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_bank_description_t *banks, pcilib_register_bank_t *ids)
Use this function to add new register banks into the model or override configuration of the existing banks.
int pcilib_add_register_protocols (pcilib_t *ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_protocol_description_t *protocols, pcilib_register_protocol_t *ids)
Use this function to add new register protocols into the model.
int pcilib_add_register_ranges (pcilib_t *ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_range_t *ranges)
Use this function to add new register ranges into the model.
pcilib_register_bank_t pcilib_find_register_bank_by_addr (pcilib_t *ctx, pcilib_register_bank_addr_t bank)
Find the register bank id (offset in banks array) corresponding to the specified bank address.
pcilib_register_bank_t pcilib_find_register_bank_by_name (pcilib_t *ctx, const char *bankname)
Find the register bank id (offset in banks array) corresponding to the specified bank name.
pcilib_register_bank_t pcilib_find_register_bank (pcilib_t *ctx, const char *bank)
Find the register bank id (offset in banks array) corresponding to the specified bank name or address.
pcilib_register_protocol_t pcilib_find_register_protocol_by_addr (pcilib_t *ctx, pcilib_register_protocol_addr_t protocol)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol address.
pcilib_register_protocol_t pcilib_find_register_protocol_by_name (pcilib_t *ctx, const char *name)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol name.
pcilib_register_protocol_t pcilib_find_register_protocol (pcilib_t *ctx, const char *name)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol name or address.
uintptr_t pcilib_resolve_bank_address_by_id (pcilib_t *ctx, pcilib_address_resolution_flags_t flags, pcilib_register_bank_t bank)
Resolves the address of the specified register bank.
uintptr_t pcilib_resolve_bank_address (pcilib_t *ctx, pcilib_address_resolution_flags_t flags, const char *bank)
Resolves the address of the specified register bank.
uintptr_t pcilib_resolve_register_address_by_id (pcilib_t *ctx, pcilib_address_resolution_flags_t flags, pcilib_register_t reg)
Resolves the address of the specified register.
uintptr_t pcilib_resolve_register_address (pcilib_t *ctx, pcilib_address_resolution_flags_t flags, const char *bank, const char *regname)
Resolves the address of the specified register.
int pcilib_get_register_bank_attr_by_id (pcilib_t *ctx, pcilib_register_bank_t bank, const char *attr, pcilib_value_t *val)
Extracts additional information about the specified register bank.
int pcilib_get_register_bank_attr (pcilib_t *ctx, const char *bankname, const char *attr, pcilib_value_t *val)
Extracts additional information about the specified register bank.
Macro Definition Documentation
PCILIB_REGISTER_BANK0
#define PCILIB_REGISTER_BANK0 0
First BANK to be used in the event engine.
PCILIB_REGISTER_BANK1
#define PCILIB_REGISTER_BANK1 1
PCILIB_REGISTER_BANK2
#define PCILIB_REGISTER_BANK2 2
PCILIB_REGISTER_BANK3
#define PCILIB_REGISTER_BANK3 3
PCILIB_REGISTER_BANK_CONF
#define PCILIB_REGISTER_BANK_CONF 64
Configuration registers.
PCILIB_REGISTER_BANK_DMA
#define PCILIB_REGISTER_BANK_DMA 97
First BANK address to be used by DMA engines.
PCILIB_REGISTER_BANK_DMA0
#define PCILIB_REGISTER_BANK_DMA0 PCILIB_REGISTER_BANK_DMA
First BANK address to be used by DMA engines.
PCILIB_REGISTER_BANK_DMA1
#define PCILIB_REGISTER_BANK_DMA1 (PCILIB_REGISTER_BANK_DMA + 1)
Second BANK address to be used by DMA engines.
PCILIB_REGISTER_BANK_DMA2
#define PCILIB_REGISTER_BANK_DMA2 (PCILIB_REGISTER_BANK_DMA + 2)
Third BANK address to be used by DMA engines.
PCILIB_REGISTER_BANK_DMA3
#define PCILIB_REGISTER_BANK_DMA3 (PCILIB_REGISTER_BANK_DMA + 3)
Fourth BANK address to be used by DMA engines.
PCILIB_REGISTER_BANK_DMACONF
#define PCILIB_REGISTER_BANK_DMACONF 96
DMA configuration in the software registers.
PCILIB_REGISTER_BANK_DYNAMIC
#define PCILIB_REGISTER_BANK_DYNAMIC 128
First BANK address to map dynamic XML configuration.
PCILIB_REGISTER_BANK_INVALID
#define PCILIB_REGISTER_BANK_INVALID ((pcilib_register_bank_t)-1)
PCILIB_REGISTER_BANK_PROPERTY
#define PCILIB_REGISTER_BANK_PROPERTY 65
Registers abstracting properties and other computed registers.
PCILIB_REGISTER_PROTOCOL0
#define PCILIB_REGISTER_PROTOCOL0 0
First PROTOCOL address to be used in the event engine.
PCILIB_REGISTER_PROTOCOL_DEFAULT
#define PCILIB_REGISTER_PROTOCOL_DEFAULT 64
Default memmap based protocol.
PCILIB_REGISTER_PROTOCOL_DMA
#define PCILIB_REGISTER_PROTOCOL_DMA 96
First PROTOCOL address to be used by DMA engines.
PCILIB_REGISTER_PROTOCOL_DYNAMIC
#define PCILIB_REGISTER_PROTOCOL_DYNAMIC 128
First PROTOCOL address to be used by plugins.
PCILIB_REGISTER_PROTOCOL_INVALID
#define PCILIB_REGISTER_PROTOCOL_INVALID ((pcilib_register_protocol_t)-1)
PCILIB_REGISTER_PROTOCOL_PROPERTY
#define PCILIB_REGISTER_PROTOCOL_PROPERTY 66
Protocol to access registers interfacing properties.
PCILIB_REGISTER_PROTOCOL_SOFTWARE
#define PCILIB_REGISTER_PROTOCOL_SOFTWARE 65
Software registers.
Typedef Documentation
pcilib_register_bank_addr_t
typedef uint8_t pcilib_register_bank_addr_t
Type holding the bank address number.
pcilib_register_bank_context_t
typedef struct pcilib_register_bank_context_s pcilib_register_bank_context_t
pcilib_register_bank_t
typedef uint8_t pcilib_register_bank_t
Type holding the bank position within the field listing register banks in the model.
pcilib_register_protocol_addr_t
typedef uint8_t pcilib_register_protocol_addr_t
Type holding the protocol address.
pcilib_register_protocol_t
typedef uint8_t pcilib_register_protocol_t
Type holding the protocol position within the field listing register protocols in the model.
Enumeration Type Documentation
pcilib_address_resolution_flags_t
enum pcilib_address_resolution_flags_t
Enumerator
PCILIB_ADDRESS_RESOLUTION_FLAGS_DEFAULT
PCILIB_ADDRESS_RESOLUTION_FLAG_BUS_ADDRESS
Resolve bus address instead of VA.
PCILIB_ADDRESS_RESOLUTION_FLAG_PHYS_ADDRESS
Resolve hardware address instead of VA.
PCILIB_ADDRESS_RESOLUTION_MASK_ADDRESS_TYPE
PCILIB_ADDRESS_RESOLUTION_FLAG_READ_ONLY
Request read-only memory, in case if read-write resolution is impossible.
PCILIB_ADDRESS_RESOLUTION_FLAG_WRITE_ONLY
Request write-only resolution, in case if read-write resolution is impossible.
PCILIB_ADDRESS_RESOLUTION_MASK_ACCESS_MODE
             {
    PCILIB_ADDRESS_RESOLUTION_FLAGS_DEFAULT = 0,
    PCILIB_ADDRESS_RESOLUTION_FLAG_BUS_ADDRESS = 1,
    PCILIB_ADDRESS_RESOLUTION_FLAG_PHYS_ADDRESS = 2,
    PCILIB_ADDRESS_RESOLUTION_MASK_ADDRESS_TYPE = 3,
    PCILIB_ADDRESS_RESOLUTION_FLAG_READ_ONLY = 4,
    PCILIB_ADDRESS_RESOLUTION_FLAG_WRITE_ONLY = 8,
    PCILIB_ADDRESS_RESOLUTION_MASK_ACCESS_MODE = 12
} pcilib_address_resolution_flags_t;
pcilib_model_modification_flags_t
enum pcilib_model_modification_flags_t
Enumerator
PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT
PCILIB_MODEL_MODIFICATION_FLAG_OVERRIDE
Instructs to override the existing registers/banks/etc...
PCILIB_MODEL_MODIFICATION_FLAG_SKIP_EXISTING
If flag is set, pcilib will just skip existing registers/banks/etc instead of reporting a error.
             {
    PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT = 0,
    PCILIB_MODEL_MODIFICATION_FLAG_OVERRIDE = 1,
    PCILIB_MODEL_MODIFICATION_FLAG_SKIP_EXISTING = 2
} pcilib_model_modification_flags_t;
Function Documentation
pcilib_add_register_banks()
int pcilib_add_register_banks (pcilib_t * ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_bank_description_t * banks, pcilib_register_bank_t * ids)
Use this function to add new register banks into the model or override configuration of the existing banks.
The function will copy the context of banks structure, but name, description, and other strings in the structure are considered to have static duration and will not be copied. On error no new banks are initalized.
Parameters
[in,out] ctx - pcilib context
[in] flags - instructs if existing banks should be reported as error (default), overriden or ignored
[in] n - number of banks to initialize. It is OK to pass 0 if banks variable is NULL terminated (last member of banks array have all members set to 0)
[in] banks - bank descriptions
[out] ids - if specified will contain the ids of the newly registered and overriden banks
Returns
- error or 0 on success
{
    int err;
    size_t i;
    pcilib_register_bank_t bank;
    size_t dyn_banks = ctx->dyn_banks;
    size_t num_banks = ctx->num_banks;
    size_t cur_banks = num_banks;
    if (!n) {
        for (n = 0; banks[n].access; n++);
    }
    if ((ctx->num_banks + n + 1) > PCILIB_MAX_REGISTER_BANKS)
        return PCILIB_ERROR_TOOBIG;
    for (i = 0; i < n; i++) {
            // Try to find if the bank is already existing...
        bank = pcilib_find_register_bank_by_name(ctx, banks[i].name);
        if ((bank == PCILIB_REGISTER_BANK_INVALID)&&(banks[i].addr != PCILIB_REGISTER_BANK_DYNAMIC))
            bank = pcilib_find_register_bank_by_addr(ctx, banks[i].addr);
        if (bank == PCILIB_REGISTER_BANK_INVALID) {
            bank = num_banks++;
        } else if (flags&PCILIB_MODEL_MODIFICATION_FLAG_SKIP_EXISTING) {
            if (ids) ids[i] = bank;
            continue;
        } else if ((flags&PCILIB_MODEL_MODIFICATION_FLAG_OVERRIDE) == 0) {
            if (pcilib_find_register_bank_by_name(ctx, banks[i].name) == PCILIB_REGISTER_BANK_INVALID)
                pcilib_error("The bank %s is already existing and override flag is not set", banks[i].name);
            else
                pcilib_error("The bank with address 0x%lx is already existing and override flag is not set", banks[i].addr);
            memset(ctx->banks + ctx->num_banks, 0, sizeof(pcilib_register_bank_description_t));
            return PCILIB_ERROR_EXIST;
        }
        memcpy(ctx->banks + bank,  banks + i, sizeof(pcilib_register_bank_description_t));
        if (ids) ids[i] = bank;
        if (banks[i].addr == PCILIB_REGISTER_BANK_DYNAMIC) {
            ctx->banks[bank].addr = PCILIB_REGISTER_BANK_DYNAMIC + dyn_banks + 1;
            dyn_banks++;
        }
    }
    ctx->num_banks = num_banks;
        // If banks are already initialized, we need to re-run the initialization code
    if (ctx->reg_bar_mapped) {
        ctx->reg_bar_mapped = 0;
        err = pcilib_init_register_banks(ctx);
        if (err) {
            ctx->num_banks = cur_banks;
            memset(ctx->banks + ctx->num_banks, 0, sizeof(pcilib_register_bank_description_t));
            return err;
        }
    }
    ctx->dyn_banks = dyn_banks;
    return 0;
}
References pcilib_register_bank_description_t::access, pcilib_register_bank_description_t::addr, pcilib_s::banks, pcilib_s::dyn_banks, pcilib_s::num_banks, pcilib_error, PCILIB_ERROR_EXIST, PCILIB_ERROR_TOOBIG, pcilib_find_register_bank_by_addr(), pcilib_find_register_bank_by_name(), pcilib_init_register_banks(), PCILIB_MAX_REGISTER_BANKS, PCILIB_MODEL_MODIFICATION_FLAG_OVERRIDE, PCILIB_MODEL_MODIFICATION_FLAG_SKIP_EXISTING, PCILIB_REGISTER_BANK_DYNAMIC, PCILIB_REGISTER_BANK_INVALID, and pcilib_s::reg_bar_mapped.
Referenced by pcilib_add_registers(), pcilib_add_registers_from_properties(), and pcilib_open().
pcilib_add_register_protocols()
int pcilib_add_register_protocols (pcilib_t * ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_protocol_description_t * protocols, pcilib_register_protocol_t * ids)
Use this function to add new register protocols into the model.
It is error to re-register already registered protocols. The function will copy the context of banks structure, but name, description, and other strings in the structure are considered to have static duration and will not be copied. On error no new protocols are initalized.
Parameters
[in,out] ctx - pcilib context
[in] flags - not used
[in] n - number of protocols to initialize. It is OK to pass 0 if protocols variable is NULL terminated (last member of protocols array have all members set to 0)
[in] protocols - protocol descriptions
[out] ids - if specified will contain the ids of the newly registered protocols
Returns
- error or 0 on success
{
        // DS: Override existing banks
    if (!n) {
        for (n = 0; protocols[n].api; n++);
    }
    if ((ctx->num_protocols + n + 1) > PCILIB_MAX_REGISTER_PROTOCOLS)
        return PCILIB_ERROR_TOOBIG;
    memcpy(ctx->protocols + ctx->num_protocols, protocols, n * sizeof(pcilib_register_protocol_description_t));
    ctx->num_protocols += n;
    return 0;
}
References pcilib_register_protocol_description_t::api, pcilib_s::num_protocols, PCILIB_ERROR_TOOBIG, PCILIB_MAX_REGISTER_PROTOCOLS, and pcilib_s::protocols.
Referenced by pcilib_open().
pcilib_add_register_ranges()
int pcilib_add_register_ranges (pcilib_t * ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_range_t * ranges)
Use this function to add new register ranges into the model.
It is error register overlapping registered ranges. On error no new ranges are initalized.
Parameters
[in,out] ctx - pcilib context
[in] flags - not used
[in] n - number of protocols to initialize. It is OK to pass 0 if protocols variable is NULL terminated.
[in] ranges - range descriptions
Returns
- error or 0 on success
{
    if (!n) {
        for (n = 0; ranges[n].end; n++);
    }
    if ((ctx->num_ranges + n + 1) > PCILIB_MAX_REGISTER_RANGES)
        return PCILIB_ERROR_TOOBIG;
    memcpy(ctx->ranges + ctx->num_ranges, ranges, n * sizeof(pcilib_register_range_t));
    ctx->num_ranges += n;
    return 0;
}
References pcilib_register_range_t::end, pcilib_s::num_ranges, PCILIB_ERROR_TOOBIG, PCILIB_MAX_REGISTER_RANGES, and pcilib_s::ranges.
pcilib_find_register_bank()
pcilib_register_bank_t pcilib_find_register_bank (pcilib_t * ctx, const char * bank)
Find the register bank id (offset in banks array) corresponding to the specified bank name or address.
Parameters
[in,out] ctx - pcilib context
[in] bank - either the name or the address of the required register bank
Returns
- bank id or PCILIB_REGISTER_BANK_INVALID if bank is not found
{
    pcilib_register_bank_t res;
    unsigned long addr;
    if (!bank) {
        const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
        const pcilib_register_bank_description_t *banks = model_info->banks;
        if ((banks)&&(banks[0].access)) return (pcilib_register_bank_t)0;
        return PCILIB_REGISTER_BANK_INVALID;
    }
    if (pcilib_isxnumber(bank)&&(sscanf(bank,"%lx", &addr) == 1)) {
        res = pcilib_find_register_bank_by_addr(ctx, addr);
        if (res != PCILIB_REGISTER_BANK_INVALID) return res;
    }
    return pcilib_find_register_bank_by_name(ctx, bank);
}
References pcilib_model_description_t::banks, pcilib_find_register_bank_by_addr(), pcilib_find_register_bank_by_name(), pcilib_get_model_description(), pcilib_isxnumber(), and PCILIB_REGISTER_BANK_INVALID.
Referenced by pcilib_find_register(), pcilib_read_register_space(), pcilib_resolve_bank_address(), and pcilib_write_register_space().
pcilib_find_register_bank_by_addr()
pcilib_register_bank_t pcilib_find_register_bank_by_addr (pcilib_t * ctx, pcilib_register_bank_addr_t bank)
Find the register bank id (offset in banks array) corresponding to the specified bank address.
Parameters
[in,out] ctx - pcilib context
[in] bank - the address of register bank
Returns
- bank id or PCILIB_REGISTER_BANK_INVALID if bank is not found
{
    pcilib_register_bank_t i;
    for (i = 0; ctx->banks[i].access; i++)
        if (ctx->banks[i].addr == bank) return i;
    return PCILIB_REGISTER_BANK_INVALID;
}
References pcilib_register_bank_description_t::access, pcilib_register_bank_description_t::addr, pcilib_s::banks, and PCILIB_REGISTER_BANK_INVALID.
Referenced by pcilib_add_register_banks(), pcilib_add_registers(), pcilib_add_registers_from_properties(), pcilib_find_register_bank(), pcilib_get_register_info(), pcilib_read_register_by_id(), and pcilib_write_register_by_id().
pcilib_find_register_bank_by_name()
pcilib_register_bank_t pcilib_find_register_bank_by_name (pcilib_t * ctx, const char * bankname)
Find the register bank id (offset in banks array) corresponding to the specified bank name.
Parameters
[in,out] ctx - pcilib context
[in] bankname - the name of register bank
Returns
- bank id or PCILIB_REGISTER_BANK_INVALID if bank is not found
{
    pcilib_register_bank_t i;
    for (i = 0; ctx->banks[i].access; i++)
        if (!strcasecmp(ctx->banks[i].name, bankname)) return i;
    return PCILIB_REGISTER_BANK_INVALID;
}
References pcilib_register_bank_description_t::access, pcilib_s::banks, pcilib_register_bank_description_t::name, and PCILIB_REGISTER_BANK_INVALID.
Referenced by pcilib_add_register_banks(), pcilib_find_register_bank(), pcilib_get_register_bank_attr(), and pcilib_get_register_info().
pcilib_find_register_protocol()
pcilib_register_protocol_t pcilib_find_register_protocol (pcilib_t * ctx, const char * name)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol name or address.
Parameters
[in,out] ctx - pcilib context
[in] name - either the name or the address of the required register protocol
Returns
- protocol id or PCILIB_REGISTER_PROTOCOL_INVALID if register protocol is not found
{
    pcilib_register_bank_t res;
    unsigned long addr;
    if (pcilib_isxnumber(protocol)&&(sscanf(protocol,"%lx", &addr) == 1)) {
        res = pcilib_find_register_protocol_by_addr(ctx, addr);
        if (res != PCILIB_REGISTER_BANK_INVALID) return res;
    }
    return pcilib_find_register_protocol_by_name(ctx, protocol);
}
References pcilib_find_register_protocol_by_addr(), pcilib_find_register_protocol_by_name(), pcilib_isxnumber(), and PCILIB_REGISTER_BANK_INVALID.
pcilib_find_register_protocol_by_addr()
pcilib_register_protocol_t pcilib_find_register_protocol_by_addr (pcilib_t * ctx, pcilib_register_protocol_addr_t protocol)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol address.
Parameters
[in,out] ctx - pcilib context
[in] protocol - the address of register protocol
Returns
- protocol id or PCILIB_REGISTER_PROTOCOL_INVALID if register protocol is not found
{
    pcilib_register_protocol_t i;
    for (i = 0; ctx->protocols[i].api; i++)
        if (ctx->protocols[i].addr == protocol) return i;
    return PCILIB_REGISTER_PROTOCOL_INVALID;
}
References pcilib_register_protocol_description_t::addr, pcilib_register_protocol_description_t::api, PCILIB_REGISTER_PROTOCOL_INVALID, and pcilib_s::protocols.
Referenced by pcilib_find_register_protocol(), and pcilib_init_register_banks().
pcilib_find_register_protocol_by_name()
pcilib_register_protocol_t pcilib_find_register_protocol_by_name (pcilib_t * ctx, const char * name)
Find the register protocol id (offset in protocols array) corresponding to the specified protocol name.
Parameters
[in,out] ctx - pcilib context
[in] name - the name of register protocol
Returns
- protocol id or PCILIB_REGISTER_PROTOCOL_INVALID if register protocol is not found
{
    pcilib_register_protocol_t i;
    for (i = 0; ctx->protocols[i].api; i++)
        if (!strcasecmp(ctx->protocols[i].name, name)) return i;
    return PCILIB_REGISTER_PROTOCOL_INVALID;
}
References pcilib_register_protocol_description_t::api, pcilib_register_protocol_description_t::name, PCILIB_REGISTER_PROTOCOL_INVALID, and pcilib_s::protocols.
Referenced by pcilib_find_register_protocol().
pcilib_free_register_banks()
void pcilib_free_register_banks (pcilib_t * ctx, pcilib_register_bank_t start)
Destroys contexts of register banks.
This is an internal function and will be called during clean-up.
Parameters
[in,out] ctx - pcilib context
[in] start - specifies first bank to clean (used to clean only part of the banks to keep the defined state if pcilib_init_register_banks has failed)
{
    size_t i;
    for (i = start; i < ctx->num_banks_init; i++) {
        const pcilib_register_protocol_api_description_t *bapi = ctx->bank_ctx[i]->api;
        if (ctx->bank_ctx[i]) {
            if (bapi->free)
                bapi->free(ctx, ctx->bank_ctx[i]);
            else
                free(ctx->bank_ctx[i]);
            ctx->bank_ctx[i] = NULL;
        }
    }
    ctx->num_banks_init = start;
}
References pcilib_register_bank_context_s::api, pcilib_s::bank_ctx, pcilib_register_protocol_api_description_t::free, and pcilib_s::num_banks_init.
Referenced by pcilib_close(), and pcilib_init_register_banks().
pcilib_get_register_bank_attr()
int pcilib_get_register_bank_attr (pcilib_t * ctx, const char * bankname, const char * attr, pcilib_value_t * val)
Extracts additional information about the specified register bank.
The additional information is model-specific and are provided as extra XML attributes in XML-described register bank. The available attributes are only restricted by used XSD schema.
Parameters
[in,out] ctx - pcilib context
[in] bankname - the name of register bank
[in] attr - requested attribute name
[in,out] val - the value of attribute is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    pcilib_register_bank_t bank;
    bank = pcilib_find_register_bank_by_name(ctx, bankname);
    if (bank == PCILIB_REGISTER_BANK_INVALID) {
        pcilib_error("Bank (%s) is not found", bankname);
        return PCILIB_ERROR_NOTFOUND;
    }
    return pcilib_get_register_bank_attr_by_id(ctx, bank, attr, val);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register_bank_by_name(), pcilib_get_register_bank_attr_by_id(), and PCILIB_REGISTER_BANK_INVALID.
pcilib_get_register_bank_attr_by_id()
int pcilib_get_register_bank_attr_by_id (pcilib_t * ctx, pcilib_register_bank_t bank, const char * attr, pcilib_value_t * val)
Extracts additional information about the specified register bank.
The additional information is model-specific and are provided as extra XML attributes in XML-described register bank. The available attributes are only restricted by used XSD schema.
Parameters
[in,out] ctx - pcilib context
[in] bank - register bank id
[in] attr - requested attribute name
[in,out] val - the value of attribute is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    assert(bank < ctx->num_banks);
    return pcilib_get_xml_attr(ctx, ctx->bank_ctx[bank]->xml, attr, val);
}
References pcilib_s::bank_ctx, pcilib_get_xml_attr(), and pcilib_register_bank_context_s::xml.
Referenced by pcilib_get_register_bank_attr().
pcilib_init_register_banks()
int pcilib_init_register_banks (pcilib_t * ctx)
Initalizes context of register banks.
This is an internal function and will be called automatically when new register banks are added. On error no new banks are initalized
Parameters
[in,out] ctx - pcilib context
Returns
- error or 0 on success
{
    int err;
    size_t start = ctx->num_banks_init;
    err = pcilib_map_register_space(ctx);
    if (err) return err;
    for (; ctx->num_banks_init < ctx->num_banks; ctx->num_banks_init++) {
        pcilib_register_bank_context_t *bank_ctx;
        pcilib_register_protocol_t protocol;
        const pcilib_register_protocol_api_description_t *bapi;
        protocol = pcilib_find_register_protocol_by_addr(ctx, ctx->banks[ctx->num_banks_init].protocol);
        if (protocol == PCILIB_REGISTER_PROTOCOL_INVALID) {
            const char *name = ctx->banks[ctx->num_banks_init].name;
            if (!name) name = "unnamed";
            pcilib_error("Invalid register protocol address (%u) is specified for bank %i (%s)", ctx->banks[ctx->num_banks_init].protocol, ctx->banks[ctx->num_banks_init].addr, name);
            pcilib_free_register_banks(ctx, start);
            return PCILIB_ERROR_INVALID_BANK;
        }
        bapi = ctx->protocols[protocol].api;
        if (bapi->init) {
            const char *model = ctx->protocols[protocol].model;
            if (!model) model = ctx->model;
            bank_ctx = bapi->init(ctx, ctx->num_banks_init, model, ctx->protocols[protocol].args);
        } else
            bank_ctx = (pcilib_register_bank_context_t*)malloc(sizeof(pcilib_register_bank_context_t));
        if (!bank_ctx) {
            pcilib_free_register_banks(ctx, start);
            return PCILIB_ERROR_FAILED;
        }
        bank_ctx->bank = ctx->banks + ctx->num_banks_init;
        bank_ctx->api = bapi;
        bank_ctx->xml = ctx->xml.bank_nodes[ctx->num_banks_init];
        ctx->bank_ctx[ctx->num_banks_init] = bank_ctx;
    }
    return 0;
}
References pcilib_register_bank_description_t::addr, pcilib_register_protocol_description_t::api, pcilib_register_bank_context_s::api, pcilib_register_protocol_description_t::args, pcilib_register_bank_context_s::bank, pcilib_s::bank_ctx, pcilib_xml_s::bank_nodes, pcilib_s::banks, pcilib_register_protocol_api_description_t::init, pcilib_register_protocol_description_t::model, pcilib_s::model, pcilib_register_bank_description_t::name, pcilib_s::num_banks, pcilib_s::num_banks_init, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_BANK, pcilib_find_register_protocol_by_addr(), pcilib_free_register_banks(), pcilib_map_register_space(), PCILIB_REGISTER_PROTOCOL_INVALID, pcilib_register_bank_description_t::protocol, pcilib_s::protocols, pcilib_register_bank_context_s::xml, and pcilib_s::xml.
Referenced by pcilib_add_register_banks(), pcilib_init_dma(), and pcilib_open().
pcilib_resolve_bank_address()
uintptr_t pcilib_resolve_bank_address (pcilib_t * ctx, pcilib_address_resolution_flags_t flags, const char * bank)
Resolves the address of the specified register bank.
The address of the register0 in the bank is returned.
All address types (virtual address in process address space, physical address, or bus address) can be resolved. The caller has also to specify the requested access mode (read, write, read/write) and the error will be returned if the requested access type is not possible.
Parameters
[in,out] ctx - pcilib context
[in] flags - specifies the type of required address (virtual, physical, or bus) and the required access (ro/wo/rw)
[in] bank - the name of register bank
Returns
- the resolved address or PCILIB_ADDRESS_INVALID on error
{
    pcilib_register_bank_t bank_id = pcilib_find_register_bank(ctx, bank);
    if (bank_id == PCILIB_REGISTER_BANK_INVALID) {
        if (bank) pcilib_error("Invalid register bank is specified (%s)", bank);
        else pcilib_error("Register bank should be specified");
        return PCILIB_ADDRESS_INVALID;
    }
    return pcilib_resolve_bank_address_by_id(ctx, flags, bank_id);
}
References PCILIB_ADDRESS_INVALID, pcilib_error, pcilib_find_register_bank(), PCILIB_REGISTER_BANK_INVALID, and pcilib_resolve_bank_address_by_id().
pcilib_resolve_bank_address_by_id()
uintptr_t pcilib_resolve_bank_address_by_id (pcilib_t * ctx, pcilib_address_resolution_flags_t flags, pcilib_register_bank_t bank)
Resolves the address of the specified register bank.
The address of the register0 in the bank is returned.
All address types (virtual address in process address space, physical address, or bus address) can be resolved. The caller has also to specify the requested access mode (read, write, read/write) and the error will be returned if the requested access type is not possible.
Parameters
[in,out] ctx - pcilib context
[in] flags - specifies the type of required address (virtual, physical, or bus) and the required access (ro/wo/rw)
[in] bank - the id of register bank
Returns
- the resolved address or PCILIB_ADDRESS_INVALID on error
{
    pcilib_register_bank_context_t *bctx = ctx->bank_ctx[bank];
    if (!bctx->api->resolve)
        return PCILIB_ADDRESS_INVALID;
    return bctx->api->resolve(ctx, bctx, flags, PCILIB_REGISTER_ADDRESS_INVALID);
}
References pcilib_register_bank_context_s::api, pcilib_s::bank_ctx, PCILIB_ADDRESS_INVALID, PCILIB_REGISTER_ADDRESS_INVALID, and pcilib_register_protocol_api_description_t::resolve.
Referenced by pcilib_resolve_bank_address().
pcilib_resolve_register_address()
uintptr_t pcilib_resolve_register_address (pcilib_t * ctx, pcilib_address_resolution_flags_t flags, const char * bank, const char * regname)
Resolves the address of the specified register.
All address types (virtual address in process address space, physical address, or bus address) can be resolved. The caller has also to specify the requested access mode (read, write, read/write) and the error will be returned if the requested access type is not possible.
Parameters
[in,out] ctx - pcilib context
[in] flags - specifies the type of required address (virtual, physical, or bus) and the required access (ro/wo/rw)
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - the name of the register
Returns
- the resolved address or PCILIB_ADDRESS_INVALID on error
{
    pcilib_register_t reg = pcilib_find_register(ctx, bank, regname);
    if (reg == PCILIB_REGISTER_INVALID) {
        pcilib_error("Register (%s) is not found", regname);
        return PCILIB_ADDRESS_INVALID;
    }
    return pcilib_resolve_register_address_by_id(ctx, flags, reg);
}
References PCILIB_ADDRESS_INVALID, pcilib_error, pcilib_find_register(), PCILIB_REGISTER_INVALID, and pcilib_resolve_register_address_by_id().
pcilib_resolve_register_address_by_id()
uintptr_t pcilib_resolve_register_address_by_id (pcilib_t * ctx, pcilib_address_resolution_flags_t flags, pcilib_register_t reg)
Resolves the address of the specified register.
All address types (virtual address in process address space, physical address, or bus address) can be resolved. The caller has also to specify the requested access mode (read, write, read/write) and the error will be returned if the requested access type is not possible.
Parameters
[in,out] ctx - pcilib context
[in] flags - specifies the type of required address (virtual, physical, or bus) and the required access (ro/wo/rw)
[in] reg - the id of register
Returns
- the resolved address or PCILIB_ADDRESS_INVALID on error
{
    pcilib_register_bank_context_t *bctx = ctx->bank_ctx[ctx->register_ctx[reg].bank];
    if (!bctx->api->resolve)
        return PCILIB_ADDRESS_INVALID;
    return bctx->api->resolve(ctx, bctx, 0, ctx->registers[reg].addr);
}
References pcilib_register_description_t::addr, pcilib_register_bank_context_s::api, pcilib_register_context_t::bank, pcilib_s::bank_ctx, PCILIB_ADDRESS_INVALID, pcilib_s::register_ctx, pcilib_s::registers, and pcilib_register_protocol_api_description_t::resolve.
Referenced by pcilib_resolve_register_address().