pcilib: bar.c File Reference
bar.c File Reference
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>
#include "pcilib.h"
#include "pci.h"
#include "tools.h"
#include "error.h"
#include "model.h"
#include "plugin.h"
Macros
#define _BSD_SOURCE
#define _DEFAULT_SOURCE
#define _POSIX_C_SOURCE 200809L
Functions
pcilib_bar_t pcilib_detect_bar (pcilib_t *ctx, uintptr_t addr, size_t size)
Detects in which PCI BAR the specified buffer is residing.
int pcilib_detect_address (pcilib_t *ctx, pcilib_bar_t *bar, uintptr_t *addr, size_t size)
Detects the BAR and mapping offset of the specified PCI buffer.
void * pcilib_map_bar (pcilib_t *ctx, pcilib_bar_t bar)
Maps the specified bar to the address space of the process.
void pcilib_unmap_bar (pcilib_t *ctx, pcilib_bar_t bar, void *data)
Unmaps the specified bar from the address space of the process.
char * pcilib_resolve_bar_address (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr)
Resolves the phisycal PCI address to a virtual address in the process address space.
int pcilib_map_register_space (pcilib_t *ctx)
int pcilib_map_data_space (pcilib_t *ctx, uintptr_t addr)
char * pcilib_resolve_data_space (pcilib_t *ctx, uintptr_t addr, size_t *size)
Resolves the virtual address and the size of PCI BAR space used for data exchange.
const pcilib_bar_info_t * pcilib_get_bar_list (pcilib_t *ctx)
Return a list of BAR memory regions available in the hardware.
const pcilib_bar_info_t * pcilib_get_bar_info (pcilib_t *ctx, pcilib_bar_t bar)
Return information about the specified BAR or NULL if BAR is not present in hardware.
int pcilib_read (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO read from the PCI BAR.
int pcilib_write (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO write to the PCI BAR.
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
Function Documentation
pcilib_detect_address()
int pcilib_detect_address (pcilib_t * ctx, pcilib_bar_t * bar, uintptr_t * addr, size_t size)
Detects the BAR and mapping offset of the specified PCI buffer.
The complete specified buffer of size bytes should fit into the BAR. Otherwise, an error will be returned.
Parameters
[in] ctx - pcilib context
[in,out] bar - the function will check if the buffer belongs to the specified BAR unless bar is PCILIB_BAR_DETECT. It will be set to the actually detected BAR in the last case.
[in,out] addr - specifies the address to detect. The address may be specified as absolute physical address or offset in the BAR. On success, the addr will contain offset which should be added to the address returned by pcilib_map_bar() to get position of BAR mapping in virtual address space.
[in] size - the size of the buffer
Returns
- error code or 0 in case of success
{
    const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
    if (!board_info) return PCILIB_ERROR_NOTFOUND;
    if (*bar == PCILIB_BAR_DETECT) {
        *bar = pcilib_detect_bar(ctx, *addr, size);
        if (*bar == PCILIB_BAR_INVALID) {
            pcilib_error("The requested data block at address 0x%x with size %zu does not belongs to any available memory bar", *addr, size);
            return PCILIB_ERROR_NOTFOUND;
        }
        if (*addr < board_info->bar_start[*bar])
            *addr += board_info->bar_start[*bar];
    } else {
        if ((*addr < board_info->bar_start[*bar])||((board_info->bar_start[*bar] + board_info->bar_length[*bar]) < (((uintptr_t)*addr) + size))) {
            if ((board_info->bar_length[*bar]) >= (((uintptr_t)*addr) + size)) {
                *addr += board_info->bar_start[*bar];
            } else {
                pcilib_error("The requested data block at address 0x%x with size %zu does not belong the specified memory bar (Bar %i: starting at 0x%x with size 0x%x)", *addr, size, *bar, board_info->bar_start[*bar], board_info->bar_length[*bar]);
                return PCILIB_ERROR_NOTFOUND;
            }
        }
    }
    *addr -= board_info->bar_start[*bar];
    *addr += board_info->bar_start[*bar] & ctx->page_mask;
    return 0;
}
References pcilib_s::page_mask, PCILIB_BAR_DETECT, PCILIB_BAR_INVALID, pcilib_detect_bar(), pcilib_error, PCILIB_ERROR_NOTFOUND, and pcilib_get_board_info().
Referenced by pcilib_map_register_space(), pcilib_read(), pcilib_read_fifo(), pcilib_write(), and pcilib_write_fifo().
pcilib_detect_bar()
pcilib_bar_t pcilib_detect_bar (pcilib_t * ctx, uintptr_t addr, size_t size)
Detects in which PCI BAR the specified buffer is residing.
The complete specified buffer of size bytes should fit into the BAR. Otherwise, an error will be returned.
Parameters
[in] ctx - pcilib context
[in] addr - physical address of the begining of the buffer
[in] size - the size of the buffer
Returns
- return the BAR (numbered from 0) or PCILIB_BAR_INVALID if buffer does not belong to any BAR.
{
    int n = 0;
    pcilib_bar_t i = ctx->reg_bar;
    const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
    if (!board_info) return PCILIB_BAR_INVALID;
        // First checking the default register bar
    if ((addr >= board_info->bar_start[i])&&((board_info->bar_start[i] + board_info->bar_length[i]) >= (addr + size))) return i;
        // Otherwise iterate
    for (i = 0; i < PCILIB_MAX_BARS; i++) {
        if (board_info->bar_length[i] > 0) {
            if ((addr >= board_info->bar_start[i])&&((board_info->bar_start[i] + board_info->bar_length[i]) >= (addr + size))) return i;
            if (n) n = -1;
            else n = i + 1;
        }
    }
    if (n > 0) return n - 1;
    return PCILIB_BAR_INVALID;
}
References PCILIB_BAR_INVALID, pcilib_get_board_info(), PCILIB_MAX_BARS, and pcilib_s::reg_bar.
Referenced by pcilib_detect_address(), and pcilib_resolve_bar_address().
pcilib_get_bar_info()
const pcilib_bar_info_t * pcilib_get_bar_info (pcilib_t * ctx, pcilib_bar_t bar)
Return information about the specified BAR or NULL if BAR is not present in hardware.
Parameters
[in,out] ctx - pcilib context
[in] bar - the PCI BAR number (numbered from 0)
Returns
- pointer to structure describing the specified BAR or NULL in case of error
{
    int i;
    const pcilib_bar_info_t *info = pcilib_get_bar_list(ctx);
    if (!info) return NULL;
    for (i = 0; info[i].size; i++) {
        if (info[i].bar == bar)
            return &info[i];
    }
    return NULL;
}
References pcilib_get_bar_list(), and pcilib_bar_info_t::size.
pcilib_get_bar_list()
const pcilib_bar_info_t * pcilib_get_bar_list (pcilib_t * ctx)
Return a list of BAR memory regions available in the hardware.
The list is terminated by a dummy BAR description with 0 size.
Parameters
[in,out] ctx - pcilib context
Returns
- pointer to structure describing the BARs or NULL in case of error
{
    int i, bars = 0;
    const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
    if (!board_info) return NULL;
    for (i = 0; i < PCILIB_MAX_BARS; i++) {
        if (board_info->bar_length[i] > 0) {
            ctx->bar_info[bars++] = (pcilib_bar_info_t) {
                .bar = i,
                .size = board_info->bar_length[i],
                .phys_addr =  board_info->bar_start[i],
                .virt_addr = ctx->bar_space[i]
            };
        }
    }
    return ctx->bar_info;
}
References pcilib_bar_info_t::bar, pcilib_s::bar_info, pcilib_s::bar_space, pcilib_get_board_info(), and PCILIB_MAX_BARS.
Referenced by pcilib_get_bar_info().
pcilib_map_bar()
void * pcilib_map_bar (pcilib_t * ctx, pcilib_bar_t bar)
Maps the specified bar to the address space of the process.
This function may be called multiple times for the same bar. It will only map the BAR once. Normally, the required BARs will be automatically mapped when BAR addresses are resolved with pcilib_resolve_bar_address() and similar.
Parameters
[in,out] ctx - pcilib context
[in] bar - the PCI BAR number (numbered from 0) return - the address where the BAR is mapped. You can't use this address directly, instead pcilib_resolve_register_address(ctx, bar, 0) have to be used to find the start of the BAR in virtual address space.
{
    void *res;
    int err, ret;
    const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
    if (!board_info) return NULL;
    if (ctx->bar_space[bar]) return ctx->bar_space[bar];
    err = pcilib_lock_global(ctx);
    if (err) {
        pcilib_error("Error (%i) acquiring mmap lock", err);
        return NULL;
    }
    ret = ioctl( ctx->handle, PCIDRIVER_IOC_MMAP_MODE, PCIDRIVER_MMAP_PCI );
    if (ret) {
        pcilib_unlock_global(ctx);
        pcilib_error("PCIDRIVER_IOC_MMAP_MODE ioctl have failed", bar);
        return NULL;
    }
    ret = ioctl( ctx->handle, PCIDRIVER_IOC_MMAP_AREA, PCIDRIVER_BAR0 + bar );
    if (ret) {
        pcilib_unlock_global(ctx);
        pcilib_error("PCIDRIVER_IOC_MMAP_AREA ioctl have failed for bank %i", bar);
        return NULL;
    }
#ifdef PCILIB_FILE_IO
    file_io_handle = open("/root/data", O_RDWR);
    res = mmap( 0, board_info->bar_length[bar], PROT_WRITE | PROT_READ, MAP_SHARED, ctx->file_io_handle, 0 );
#else
    res = mmap( 0, board_info->bar_length[bar], PROT_WRITE | PROT_READ, MAP_SHARED, ctx->handle, 0 );
#endif
    pcilib_unlock_global(ctx);
    if ((!res)||(res == MAP_FAILED)) {
        pcilib_error("Failed to mmap data bank %i", bar);
        return NULL;
    }
    ctx->bar_space[bar] = res;
    return res;
}
References pcilib_s::bar_space, pcilib_s::handle, pcilib_error, pcilib_get_board_info(), pcilib_lock_global(), and pcilib_unlock_global().
Referenced by pcilib_map_data_space(), pcilib_map_register_space(), pcilib_read(), pcilib_read_fifo(), pcilib_resolve_bar_address(), pcilib_write(), and pcilib_write_fifo().
pcilib_map_data_space()
int pcilib_map_data_space (pcilib_t * ctx, uintptr_t addr)
{
    int err;
    pcilib_bar_t i;
    if (!ctx->data_bar_mapped) {
        const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
        if (!board_info) return PCILIB_ERROR_FAILED;
        err = pcilib_map_register_space(ctx);
        if (err) {
            pcilib_error("Error mapping register space");
            return err;
        }
        int data_bar = -1;
        for (i = 0; i < PCILIB_MAX_BARS; i++) {
            if ((ctx->bar_space[i])||(!board_info->bar_length[i])) continue;
            if (addr) {
                if (board_info->bar_start[i] == addr) {
                    data_bar = i;
                    break;
                }
            } else {
                if (data_bar >= 0) {
                    data_bar = -1;
                    break;
                }
                data_bar = i;
            }
        }
        if (data_bar < 0) {
            if (addr) pcilib_error("Unable to find the specified data space (%lx)", addr);
            else pcilib_error("Unable to find the data space");
            return PCILIB_ERROR_NOTFOUND;
        }
        ctx->data_bar = data_bar;
        if (!ctx->bar_space[data_bar]) {
            char *data_space = pcilib_map_bar(ctx, data_bar);
            if (data_space) ctx->bar_space[data_bar] = data_space;
            else {
                pcilib_error("Unable to map the data space");
                return PCILIB_ERROR_FAILED;
            }
        }
        ctx->data_bar_mapped = 0;
    }
    return 0;
}
References pcilib_s::bar_space, pcilib_s::data_bar, pcilib_s::data_bar_mapped, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_NOTFOUND, pcilib_get_board_info(), pcilib_map_bar(), pcilib_map_register_space(), and PCILIB_MAX_BARS.
Referenced by pcilib_resolve_data_space().
pcilib_map_register_space()
int pcilib_map_register_space (pcilib_t * ctx)
{
    int err;
    pcilib_register_bank_t i;
    if (!ctx->reg_bar_mapped)  {
        const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
        const pcilib_register_bank_description_t *banks = model_info->banks;
        for (i = 0; ((banks)&&(banks[i].access)); i++) {
//          uint32_t buf[2];
            void *reg_space;
            pcilib_bar_t bar = banks[i].bar;
            if (bar == PCILIB_BAR_NOBAR)
                continue;
            if (bar == PCILIB_BAR_DETECT) {
                uintptr_t addr = banks[0].read_addr;
                err = pcilib_detect_address(ctx, &bar, &addr, 1);
                if (err) return err;
                if (!ctx->bar_space[bar]) {
                    reg_space = pcilib_map_bar(ctx, bar);
//                  pcilib_memcpy(&buf, reg_space, 8);
                    if (reg_space) {
                        ctx->bar_space[bar] = reg_space;
                    } else {
                        return PCILIB_ERROR_FAILED;
                    }
                }
            } else if (!ctx->bar_space[bar]) {
                reg_space = pcilib_map_bar(ctx, bar);
                if (reg_space) {
                    ctx->bar_space[bar] = reg_space;
                } else {
                    return PCILIB_ERROR_FAILED;
                }
//              pcilib_memcpy(&buf, reg_space, 8);
            }
            if (!i) ctx->reg_bar = bar;
        }
        ctx->reg_bar_mapped = 1;
    }
    return 0;
}
References pcilib_model_description_t::banks, pcilib_register_bank_description_t::bar, pcilib_s::bar_space, PCILIB_BAR_DETECT, PCILIB_BAR_NOBAR, pcilib_detect_address(), PCILIB_ERROR_FAILED, pcilib_get_model_description(), pcilib_map_bar(), pcilib_register_bank_description_t::read_addr, pcilib_s::reg_bar, and pcilib_s::reg_bar_mapped.
Referenced by pcilib_init_register_banks(), and pcilib_map_data_space().
pcilib_resolve_data_space()
char * pcilib_resolve_data_space (pcilib_t * ctx, uintptr_t addr, size_t * size)
Resolves the virtual address and the size of PCI BAR space used for data exchange.
This is left-over from older version of pcilib and currently unused. We may reconsider how it is organized and implemented. The data_space parameter may go into the model definition.
Parameters
[in] ctx - pcilib context
[in] addr - may hint there the data space is located, use 0 to autodetect
[out] size - the size of data space is returned
Returns
- virtual address of data space (ready to use) or NULL if detection has failed
{
    int err;
    err = pcilib_map_data_space(ctx, addr);
    if (err) {
        pcilib_error("Failed to map the specified address space (%lx)", addr);
        return NULL;
    }
    if (size) *size = ctx->board_info.bar_length[ctx->data_bar];
    return ctx->bar_space[ctx->data_bar] + (ctx->board_info.bar_start[ctx->data_bar] & ctx->page_mask);
}
References pcilib_s::bar_space, pcilib_s::board_info, pcilib_s::data_bar, pcilib_s::page_mask, pcilib_error, and pcilib_map_data_space().
pcilib_unmap_bar()
void pcilib_unmap_bar (pcilib_t * ctx, pcilib_bar_t bar, void * data)
Unmaps the specified bar from the address space of the process.
Actually, it will only unmap the BAR if it is not used by DMA or Event egines. So, it is fine to include the calls to pcilib_map_bar() / pcilib_unmap_bar() when a specific BAR is needed. On other hand, there is a little point in doing so. The BAR may be left mapped and will be automatically umapped when pcilib_close() is called.
Parameters
[in,out] ctx - pcilib context
[in] bar - BAR number (numbered from 0)
[in,out] data - The address returned by pcilib_map_bar() call
{
    const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
    if (!board_info) return;
    if (ctx->bar_space[bar]) return;
    munmap(data, board_info->bar_length[bar]);
#ifdef PCILIB_FILE_IO
    close(ctx->file_io_handle);
#endif
}
References pcilib_s::bar_space, and pcilib_get_board_info().
Referenced by pcilib_close(), pcilib_read(), pcilib_read_fifo(), pcilib_write(), and pcilib_write_fifo().