pcilib: dma.c File Reference
dma.c File Reference
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include <errno.h>
#include <assert.h>
#include "error.h"
#include "pcilib.h"
#include "pci.h"
#include "dma.h"
#include "tools.h"
#include "pagecpy.h"
Data Structures
struct pcilib_dma_read_callback_context_t
Functions
const pcilib_dma_description_t * pcilib_get_dma_description (pcilib_t *ctx)
pcilib_dma_engine_t pcilib_find_dma_by_addr (pcilib_t *ctx, pcilib_dma_direction_t direction, pcilib_dma_engine_addr_t dma)
This function resolves the ID of DMA engine from its address and direction.
pcilib_dma_engine_t pcilib_add_dma_engine (pcilib_t *ctx, pcilib_dma_engine_description_t *desc)
int pcilib_init_dma (pcilib_t *ctx)
int pcilib_start_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Starts DMA engine.
int pcilib_stop_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Stops DMA engine or just cleans up the process-specific memory buffers (see pcilib_start_dma() for details).
int pcilib_enable_irq (pcilib_t *ctx, pcilib_irq_type_t irq_type, pcilib_dma_flags_t flags)
int pcilib_disable_irq (pcilib_t *ctx, pcilib_dma_flags_t flags)
int pcilib_acknowledge_irq (pcilib_t *ctx, pcilib_irq_type_t irq_type, pcilib_irq_source_t irq_source)
int pcilib_stream_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, pcilib_dma_callback_t cb, void *cbattr)
Reads data from DMA buffers and pass it to the specified callback function.
int pcilib_read_dma_custom (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *read_bytes)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
int pcilib_read_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void *buf, size_t *read_bytes)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
int pcilib_skip_dma (pcilib_t *ctx, pcilib_dma_engine_t dma)
Tries to drop all pending data in the DMA channel.
int pcilib_push_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *written)
Pushes new data to the DMA engine.
int pcilib_write_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void *buf, size_t *written_bytes)
Pushes new data to the DMA engine and blocks until hardware gets it all.
double pcilib_benchmark_dma (pcilib_t *ctx, pcilib_dma_engine_addr_t dma, uintptr_t addr, size_t size, size_t iterations, pcilib_dma_direction_t direction)
Benchmarks the DMA implementation.
int pcilib_get_dma_status (pcilib_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_engine_status_t *status, size_t n_buffers, pcilib_dma_buffer_status_t *buffers)
Function Documentation
pcilib_add_dma_engine()
pcilib_dma_engine_t pcilib_add_dma_engine (pcilib_t * ctx, pcilib_dma_engine_description_t * desc)
{
    pcilib_dma_engine_t engine = ctx->num_engines++;
    memcpy (&ctx->engines[engine], desc, sizeof(pcilib_dma_engine_description_t));
    return engine;
}
References pcilib_s::engines, and pcilib_s::num_engines.
pcilib_get_dma_description()
const pcilib_dma_description_t * pcilib_get_dma_description (pcilib_t * ctx)
{
    int err;
    err = pcilib_init_dma(ctx);
    if (err) {
        pcilib_error("Error (%i) while initializing DMA", err);
        return NULL;
    }
    if (!ctx->dma_ctx) return NULL;
    return &ctx->dma;
}
References pcilib_s::dma, pcilib_s::dma_ctx, pcilib_error, and pcilib_init_dma().
Referenced by pcilib_acknowledge_irq(), pcilib_benchmark_dma(), pcilib_disable_irq(), pcilib_enable_irq(), pcilib_find_dma_by_addr(), pcilib_get_dma_status(), pcilib_push_dma(), pcilib_start_dma(), pcilib_stop_dma(), and pcilib_stream_dma().
pcilib_get_dma_status()
int pcilib_get_dma_status (pcilib_t * ctx, pcilib_dma_engine_t dma, pcilib_dma_engine_status_t * status, size_t n_buffers, pcilib_dma_buffer_status_t * buffers)
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return 0;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return -1;
    }
    if (!info->api->status) {
        memset(status, 0, sizeof(pcilib_dma_engine_status_t));
        return -1;
   }
        // DS: We should check we don't exceed allocated engine range
    if (!info->engines[dma].addr_bits) {
        pcilib_error("The DMA engine (%i) is not supported by device", dma);
        return -1;
    }
    return info->api->status(ctx->dma_ctx, dma, status, n_buffers, buffers);
}
References pcilib_dma_engine_description_t::addr_bits, pcilib_dma_description_t::api, pcilib_s::dma_ctx, pcilib_dma_description_t::engines, pcilib_error, pcilib_get_dma_description(), and pcilib_dma_api_description_t::status.
pcilib_init_dma()
int pcilib_init_dma (pcilib_t * ctx)
{
    int err;
    pcilib_dma_context_t *dma_ctx = NULL;
    const pcilib_dma_description_t *info = &ctx->dma;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    pcilib_dma_engine_t dma;
    if (ctx->dma_ctx)
        return 0;
    if ((ctx->event_ctx)&&(model_info->api)&&(model_info->api->init_dma)) {
        err = pcilib_init_register_banks(ctx);
        if (err) {
            pcilib_error("Error (%i) while initializing register banks", err);
            return err;
        }
        dma_ctx = model_info->api->init_dma(ctx->event_ctx);
    } else if ((ctx->dma.api)&&(ctx->dma.api->init)) {
        err = pcilib_init_register_banks(ctx);
        if (err) {
            pcilib_error("Error (%i) while initializing register banks", err);
            return err;
        }
        dma_ctx = ctx->dma.api->init(ctx, (ctx->dma.model?ctx->dma.model:ctx->model), ctx->dma.args);
    }
    if (dma_ctx) {
        for  (dma = 0; info->engines[dma].addr_bits; dma++) {
            if (info->engines[dma].direction&PCILIB_DMA_FROM_DEVICE) {
                ctx->dma_rlock[dma] = pcilib_get_lock(ctx, PCILIB_LOCK_FLAGS_DEFAULT, "dma%ir/%s", info->engines[dma].addr, info->name);
                if (!ctx->dma_rlock[dma]) break;
            }
            if (info->engines[dma].direction&PCILIB_DMA_TO_DEVICE) {
                ctx->dma_wlock[dma] = pcilib_get_lock(ctx, PCILIB_LOCK_FLAGS_DEFAULT, "dma%iw/%s", info->engines[dma].addr, info->name);
                if (!ctx->dma_wlock[dma]) break;
            }
        }
        if (info->engines[dma].addr_bits) {
            if (ctx->dma.api->free)
                ctx->dma.api->free(dma_ctx);
            pcilib_error("Failed to intialize DMA locks");
            return PCILIB_ERROR_FAILED;
        }
        dma_ctx->pcilib = ctx;
            // DS: parameters?
        ctx->dma_ctx = dma_ctx;
    }
    return 0;
}
References pcilib_dma_engine_description_t::addr, pcilib_dma_engine_description_t::addr_bits, pcilib_dma_description_t::api, pcilib_model_description_t::api, pcilib_dma_description_t::args, pcilib_dma_engine_description_t::direction, pcilib_s::dma, pcilib_s::dma_ctx, pcilib_s::dma_rlock, pcilib_s::dma_wlock, pcilib_dma_description_t::engines, pcilib_s::event_ctx, pcilib_dma_api_description_t::free, pcilib_dma_api_description_t::init, pcilib_event_api_description_t::init_dma, pcilib_dma_description_t::model, pcilib_s::model, pcilib_dma_description_t::name, pcilib_dma_context_t::pcilib, PCILIB_DMA_FROM_DEVICE, PCILIB_DMA_TO_DEVICE, pcilib_error, PCILIB_ERROR_FAILED, pcilib_get_lock(), pcilib_get_model_description(), pcilib_init_register_banks(), and PCILIB_LOCK_FLAGS_DEFAULT.
Referenced by pcilib_get_dma_description().