pcilib: error.c File Reference
error.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "export.h"
#include "error.h"
Macros
#define _BSD_SOURCE
#define _DEFAULT_SOURCE
#define PCILIB_LOGGER_HISTORY 16
Functions
void pcilib_print_error (void *arg, const char *file, int line, pcilib_log_priority_t prio, const char *msg, va_list va)
void pcilib_log_message (const char *file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char *msg,...)
void pcilib_log_vmessage (const char *file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char *msg, va_list va)
int pcilib_set_logger (pcilib_log_priority_t min_prio, pcilib_logger_t logger, void *arg)
Replaces default logging function.
pcilib_logger_t pcilib_get_logger ()
Gets current logger function.
pcilib_log_priority_t pcilib_get_log_level ()
Gets current logger min priority.
void * pcilib_get_logger_context ()
Gets current logger argument.
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
PCILIB_LOGGER_HISTORY
#define PCILIB_LOGGER_HISTORY 16
Function Documentation
pcilib_get_log_level()
pcilib_log_priority_t pcilib_get_log_level ()
Gets current logger min priority.
{
    return pcilib_logger_min_prio;
}
pcilib_get_logger()
pcilib_logger_t pcilib_get_logger ()
Gets current logger function.
{
    return pcilib_logger;
}
pcilib_get_logger_context()
void * pcilib_get_logger_context ()
Gets current logger argument.
{
    return pcilib_logger_argument;
}
pcilib_log_message()
void pcilib_log_message (const char * file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char * msg, ...)
{
    va_list va;
    if ((!prio)||(prio >= pcilib_logger_min_prio)) {
        if (pcilib_log_check_history(flags, msg))
            return;
        va_start(va, msg);
        pcilib_logger(pcilib_logger_argument, file, line, prio, msg, va);
        va_end(va);
    }
}
pcilib_log_vmessage()
void pcilib_log_vmessage (const char * file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char * msg, va_list va)
{
    if ((!prio)||(prio >= pcilib_logger_min_prio)) {
        if (pcilib_log_check_history(flags, msg))
            return;
        pcilib_logger(pcilib_logger_argument, file, line, prio, msg, va);
    }
}
Referenced by pcilib_debug_message(), and pcilib_log_python_error().
pcilib_print_error()
void pcilib_print_error (void * arg, const char * file, int line, pcilib_log_priority_t prio, const char * msg, va_list va)
{
    size_t size = strlen(msg) + strlen(file) + 64;
    char *stmp = alloca(size * sizeof(char*));
    if (stmp) {
        sprintf(stmp, "%s [%s:%d]\n", msg, file, line);
        vprintf(stmp, va);
    } else {
            // Bad for multithreading...
        vprintf(msg, va);
        printf(" [%s:%d]\n", file, line);
    }
}
Referenced by pcilib_set_logger().