pcilib: event.h File Reference
event.h File Reference
#include <pcilib.h>
#include <pcilib/version.h>
#include <pcilib/dma.h>
Data Structures
struct pcilib_autostop_parameters_t
struct pcilib_rawdata_parameters_t
struct pcilib_parallel_parameters_t
struct pcilib_event_parameters_t
struct pcilib_event_context_s
struct pcilib_event_description_t
struct pcilib_event_data_type_description_t
struct pcilib_event_api_description_t
Macros
#define PCILIB_EVENT_INTERFACE_VERSION PCILIB_VERSION
Functions
int pcilib_init_event_engine (pcilib_t *ctx)
int pcilib_configure_preprocessing_threads (pcilib_t *ctx, size_t max_threads)
Macro Definition Documentation
PCILIB_EVENT_INTERFACE_VERSION
#define PCILIB_EVENT_INTERFACE_VERSION PCILIB_VERSION
Function Documentation
pcilib_configure_preprocessing_threads()
int pcilib_configure_preprocessing_threads (pcilib_t * ctx, size_t max_threads)
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    ctx->event_ctx->params.parallel.max_threads = max_threads;
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_parallel_parameters_t::max_threads, pcilib_event_parameters_t::parallel, pcilib_event_context_s::params, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
Referenced by pcilib_start().
pcilib_init_event_engine()
int pcilib_init_event_engine (pcilib_t * ctx)
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if ((api)&&(api->init)) {
        ctx->event_ctx = api->init(ctx);
        if (ctx->event_ctx) {
            ctx->event_ctx->pcilib = ctx;
        }
    }
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::init, pcilib_event_context_s::pcilib, and pcilib_get_model_description().
Referenced by pcilib_open().