pcilib: event.c File Reference
event.c File Reference
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdarg.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>
#include <time.h>
#include "pci.h"
#include "tools.h"
#include "error.h"
Data Structures
struct timespec
struct pcilib_grab_callback_user_data_t
Macros
#define _POSIX_C_SOURCE 199309L
#define PCILIB_DEFINE_TIMESPEC 1
Functions
pcilib_event_t pcilib_find_event (pcilib_t *ctx, const char *event)
Resolves the event ID based on its name.
pcilib_event_data_type_t pcilib_find_event_data_type (pcilib_t *ctx, pcilib_event_t event, const char *data_type)
Resolves the data type based on its name.
int pcilib_init_event_engine (pcilib_t *ctx)
pcilib_context_t * pcilib_get_event_engine (pcilib_t *ctx)
Provides access to the context of event engine.
int pcilib_reset (pcilib_t *ctx)
Should reset the hardware and software in default state.
int pcilib_configure_rawdata_callback (pcilib_t *ctx, pcilib_event_rawdata_callback_t callback, void *user)
Requests the streaming the rawdata from the event engine.
int pcilib_configure_autostop (pcilib_t *ctx, size_t max_events, pcilib_timeout_t duration)
Configures conditions when the grabbing will be stopped automatically.
int pcilib_configure_autotrigger (pcilib_t *ctx, pcilib_timeout_t interval, pcilib_event_t event, size_t trigger_size, void *trigger_data)
Request the auto-triggering while grabbing.
int pcilib_configure_preprocessing_threads (pcilib_t *ctx, size_t max_threads)
int pcilib_start (pcilib_t *ctx, pcilib_event_t event_mask, pcilib_event_flags_t flags)
Analyzes current configuration, allocates necessary buffers and spawns required data processing threads.
int pcilib_stop (pcilib_t *ctx, pcilib_event_flags_t flags)
Stops event grabbing and optionally cleans up the used memory.
int pcilib_stream (pcilib_t *ctx, pcilib_event_callback_t callback, void *user)
Streams the incomming events to the provided callback function.
int pcilib_get_next_event (pcilib_t *ctx, pcilib_timeout_t timeout, pcilib_event_id_t *evid, size_t info_size, pcilib_event_info_t *info)
Waits until the next event is available.
int pcilib_trigger (pcilib_t *ctx, pcilib_event_t event, size_t trigger_size, void *trigger_data)
Issues a single software trigger for the specified event.
void * pcilib_get_data_with_argument (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t *size)
Returns pointer to the data of the specified type associated with the specified event.
int pcilib_copy_data_with_argument (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t size, void *buf, size_t *retsize)
Copies the data of the specified type associated with the specified event into the provided buffer.
void * pcilib_get_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t *size)
Returns pointer to the data of the specified type associated with the specified event.
int pcilib_copy_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t size, void *buf, size_t *ret_size)
Copies the data of the specified type associated with the specified event into the provided buffer.
int pcilib_return_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, void *data)
int pcilib_grab (pcilib_t *ctx, pcilib_event_t event_mask, size_t *size, void **data, pcilib_timeout_t timeout)
This is a simples way to grab the data from the event engine.
Macro Definition Documentation
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 199309L
PCILIB_DEFINE_TIMESPEC
#define PCILIB_DEFINE_TIMESPEC 1
Function Documentation
pcilib_configure_preprocessing_threads()
int pcilib_configure_preprocessing_threads (pcilib_t * ctx, size_t max_threads)
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    ctx->event_ctx->params.parallel.max_threads = max_threads;
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_parallel_parameters_t::max_threads, pcilib_event_parameters_t::parallel, pcilib_event_context_s::params, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
Referenced by pcilib_start().
pcilib_init_event_engine()
int pcilib_init_event_engine (pcilib_t * ctx)
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if ((api)&&(api->init)) {
        ctx->event_ctx = api->init(ctx);
        if (ctx->event_ctx) {
            ctx->event_ctx->pcilib = ctx;
        }
    }
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::init, pcilib_event_context_s::pcilib, and pcilib_get_model_description().
Referenced by pcilib_open().