pcilib: Public PCI API (MMIO)
Public PCI API (MMIO)
API for manipulation with memory-mapped PCI BAR space.
Functions
char * pcilib_resolve_bar_address (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr)
Resolves the phisycal PCI address to a virtual address in the process address space.
int pcilib_read (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO read from the PCI BAR.
int pcilib_write (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO write to the PCI BAR.
int pcilib_read_fifo (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO read from the PCI BAR.
int pcilib_write_fifo (pcilib_t *ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void *buf)
Performs PIO write to the PCI BAR.
Detailed Description
API for manipulation with memory-mapped PCI BAR space.
Function Documentation
pcilib_read()
int pcilib_read (pcilib_t * ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void * buf)
Performs PIO read from the PCI BAR.
The BAR will be automatically mapped and unmapped if necessary.
Parameters
[in,out] ctx - pcilib context
[in] bar - the BAR to read, use PCILIB_BAR_DETECT to detect bar by the specified physical address
[in] addr - absolute physical address to read or the offset in the specified bar
[in] access - word size (access width in bytes)
[in] n - number of words to read
[out] buf - the read data will be placed in this buffer
Returns
- error code or 0 on success
{
    void *data;
    pcilib_detect_address(ctx, &bar, &addr, access * n);
    data = pcilib_map_bar(ctx, bar);
    pcilib_memcpy(buf, data + addr, access, n);
    pcilib_unmap_bar(ctx, bar, data);
    return 0;
}
References pcilib_detect_address(), pcilib_map_bar(), pcilib_memcpy(), and pcilib_unmap_bar().
pcilib_read_fifo()
int pcilib_read_fifo (pcilib_t * ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void * buf)
Performs PIO read from the PCI BAR.
The specified address is treated as FIFO and will be read n times. The BAR will be automatically mapped and unmapped if necessary.
Parameters
[in,out] ctx - pcilib context
[in] bar - the BAR to read, use PCILIB_BAR_DETECT to detect bar by the specified physical address
[in] addr - absolute physical address to read or the offset in the specified bar
[in] access - the size of FIFO register in bytes (i.e. if access = 4, the 32-bit reads from FIFO will be performed)
[in] n - specifies how many times the data should be read from FIFO
[out] buf - the data will be placed in this buffer which should be at least n * access bytes long
Returns
- error code or 0 on success
{
    int i;
    void *data;
    pcilib_detect_address(ctx, &bar, &addr, fifo_size);
    data = pcilib_map_bar(ctx, bar);
    for (i = 0; i < n; i++) {
        pcilib_memcpy(buf + i * fifo_size, data + addr, fifo_size, 1);
    }
    pcilib_unmap_bar(ctx, bar, data);
    return 0;
}
References pcilib_detect_address(), pcilib_map_bar(), pcilib_memcpy(), and pcilib_unmap_bar().
pcilib_resolve_bar_address()
char * pcilib_resolve_bar_address (pcilib_t * ctx, pcilib_bar_t bar, uintptr_t addr)
Resolves the phisycal PCI address to a virtual address in the process address space.
The required BAR will be mapped if necessary.
Parameters
[in,out] ctx - pcilib context
[in] bar - specifies the BAR address belong to, use PCILIB_BAR_DETECT for autodetection
[in] addr - specifies the physical address on the PCI bus or offset in the BAR if bar is specified
Returns
- the virtual address in the process address space or NULL in case of error
{
    if (bar == PCILIB_BAR_DETECT) {
        bar = pcilib_detect_bar(ctx, addr, 1);
        if (bar == PCILIB_BAR_INVALID) return NULL;
        if ((!ctx->bar_space[bar])&&(!pcilib_map_bar(ctx, bar))) {
            pcilib_error("Failed to map the requested bar (%i)", bar);
            return NULL;
        }
        return ctx->bar_space[bar] + (addr - ctx->board_info.bar_start[bar]) + (ctx->board_info.bar_start[bar] & ctx->page_mask);
    } else {
        if ((!ctx->bar_space[bar])&&(!pcilib_map_bar(ctx, bar))) {
            pcilib_error("Failed to map the requested bar (%i)", bar);
            return NULL;
        }
        if (addr < ctx->board_info.bar_length[bar]) {
            return ctx->bar_space[bar] + addr + (ctx->board_info.bar_start[bar] & ctx->page_mask);
        }
        if ((addr >= ctx->board_info.bar_start[bar])&&(addr < (ctx->board_info.bar_start[bar] + ctx->board_info.bar_length[ctx->reg_bar]))) {
            return ctx->bar_space[bar] + (addr - ctx->board_info.bar_start[bar]) + (ctx->board_info.bar_start[bar] & ctx->page_mask);
        }
    }
    return NULL;
}
References pcilib_s::bar_space, pcilib_s::board_info, pcilib_s::page_mask, PCILIB_BAR_DETECT, PCILIB_BAR_INVALID, pcilib_detect_bar(), pcilib_error, pcilib_map_bar(), and pcilib_s::reg_bar.
pcilib_write()
int pcilib_write (pcilib_t * ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void * buf)
Performs PIO write to the PCI BAR.
The BAR will be automatically mapped and unmapped if necessary.
Parameters
[in,out] ctx - pcilib context
[in] bar - the BAR to write, use PCILIB_BAR_DETECT to detect bar by the specified physical address
[in] addr - absolute physical address to write or the offset in the specified bar
[in] access - word size (access width in bytes)
[in] n - number of words to write
[out] buf - the pointer to the data to be written
Returns
- error code or 0 on success
{
    void *data;
    pcilib_detect_address(ctx, &bar, &addr, access * n);
    data = pcilib_map_bar(ctx, bar);
    pcilib_memcpy(data + addr, buf, access, n);
    pcilib_unmap_bar(ctx, bar, data);
    return 0;
}
References pcilib_detect_address(), pcilib_map_bar(), pcilib_memcpy(), and pcilib_unmap_bar().
pcilib_write_fifo()
int pcilib_write_fifo (pcilib_t * ctx, pcilib_bar_t bar, uintptr_t addr, uint8_t access, size_t n, void * buf)
Performs PIO write to the PCI BAR.
The specified address is treated as FIFO and will be written n times. The BAR will be automatically mapped and unmapped if necessary.
Parameters
[in,out] ctx - pcilib context
[in] bar - the BAR to write, use PCILIB_BAR_DETECT to detect bar by the specified physical address
[in] addr - absolute physical address to write or the offset in the specified bar
[in] access - the size of FIFO register in bytes (i.e. if access = 4, the 32-bit writes to FIFO will be performed)
[in] n - specifies how many times the data should be written to FIFO
[out] buf - buffer to write which should be at least n * access bytes long
Returns
- error code or 0 on success
{
    int i;
    void *data;
    pcilib_detect_address(ctx, &bar, &addr, fifo_size);
    data = pcilib_map_bar(ctx, bar);
    for (i = 0; i < n; i++) {
        pcilib_memcpy(data + addr, buf + i * fifo_size, fifo_size, 1);
    }
    pcilib_unmap_bar(ctx, bar, data);
    return 0;
}
References pcilib_detect_address(), pcilib_map_bar(), pcilib_memcpy(), and pcilib_unmap_bar().