pcilib: Public Event Data API
Public Event Data API
A part of Event API actually providing access to the data.
Functions
pcilib_event_data_type_t pcilib_find_event_data_type (pcilib_t *ctx, pcilib_event_t event, const char *data_type)
Resolves the data type based on its name.
int pcilib_grab (pcilib_t *ctx, pcilib_event_t event, size_t *size, void **data, pcilib_timeout_t timeout)
This is a simples way to grab the data from the event engine.
int pcilib_copy_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t size, void *buf, size_t *retsize)
Copies the data of the specified type associated with the specified event into the provided buffer.
int pcilib_copy_data_with_argument (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t size, void *buf, size_t *retsize)
Copies the data of the specified type associated with the specified event into the provided buffer.
void * pcilib_get_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t *size_or_err)
Returns pointer to the data of the specified type associated with the specified event.
void * pcilib_get_data_with_argument (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t *size_or_err)
Returns pointer to the data of the specified type associated with the specified event.
int pcilib_return_data (pcilib_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, void *data)
Detailed Description
A part of Event API actually providing access to the data.
Function Documentation
pcilib_copy_data()
int pcilib_copy_data (pcilib_t * ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t size, void * buf, size_t * retsize)
Copies the data of the specified type associated with the specified event into the provided buffer.
May return PCILIB_ERROR_OVERWRITTEN if the data was overwritten during the call.
Parameters
[in,out] ctx - pcilib context
[in] event_id - specifies the ID of event to get data from
[in] data_type - specifies the desired type of data
PCILIB_EVENT_DATA will request the default data type
PCILIB_EVENT_RAW_DATA will request the raw data
The other types of data may be defined by event engine
[in] size - specifies the size of provided buffer in bytes
[out] buf - the data will be copied in this buffer if it is big enough, otherwise PCILIB_ERROR_TOOBIG will be returned
[out] retsize - the number of actually written bytes will be returned in this parameter
Returns
- error code or 0 on success
{
    int err;
    void *res = buf;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_api_description_t *api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->get_data) {
        err = api->get_data(ctx->event_ctx, event_id, data_type, 0, NULL, &size, &res);
        if (err) return err;
        if (buf != res) memcpy(buf, res, size);
        if (ret_size) *ret_size = size;
        return 0;
    }
    return PCILIB_ERROR_NOTSUPPORTED;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::get_data, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
pcilib_copy_data_with_argument()
int pcilib_copy_data_with_argument (pcilib_t * ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void * arg, size_t size, void * buf, size_t * retsize)
Copies the data of the specified type associated with the specified event into the provided buffer.
May return PCILIB_ERROR_OVERWRITTEN if the data was overwritten during the call. This is very similar to pcilib_copy_data(), but allows to specify implementation specific argument explaining the requested data format.
Parameters
[in,out] ctx - pcilib context
[in] event_id - specifies the ID of event to get data from
[in] data_type - specifies the desired type of data
PCILIB_EVENT_DATA will request the default data type
PCILIB_EVENT_RAW_DATA will request the raw data
The other types of data may be defined by event engine
[in] arg_size - specifies the size of arg in bytes
[in] arg - implementation-specific argument expalining the requested data format
[in] size - specifies the size of provided buffer in bytes
[out] buf - the data will be copied in this buffer if it is big enough, otherwise PCILIB_ERROR_TOOBIG will be returned
[out] retsize - the number of actually written bytes will be returned in this parameter
Returns
- error code or 0 on success
{
    int err;
    void *res = buf;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_api_description_t *api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->get_data) {
        err = api->get_data(ctx->event_ctx, event_id, data_type, arg_size, arg, &size, &res);
        if (err) return err;
        if (buf != res) memcpy(buf, res, size);
        if (retsize) *retsize = size;
        return 0;
    }
    return PCILIB_ERROR_NOTSUPPORTED;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::get_data, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
pcilib_find_event_data_type()
pcilib_event_data_type_t pcilib_find_event_data_type (pcilib_t * ctx, pcilib_event_t event, const char * data_type)
Resolves the data type based on its name.
Parameters
[in,out] ctx - pcilib context
[in] event - the ID of the event producing the data
[in] data_type - the name of data type
Returns
- the data type or PCILIB_EVENT_DATA_TYPE_INVALID if the specified type is not found
{
    int i;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_data_type_description_t *data_types = model_info->data_types;
    for (i = 0; data_types[i].name; i++) {
        if ((data_types[i].evid&event)&&(!strcasecmp(data_types[i].name, data_type))) return data_types[i].data_type;
    }
    return (pcilib_event_data_type_t)-1;
}
References pcilib_event_data_type_description_t::data_type, pcilib_model_description_t::data_types, pcilib_event_data_type_description_t::name, and pcilib_get_model_description().
pcilib_get_data()
void * pcilib_get_data (pcilib_t * ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t * size_or_err)
Returns pointer to the data of the specified type associated with the specified event.
The data should be returned back to the Event engine using pcilib_return_data() call. WARNING: Current implementation may overwrite the data before the pcilib_return_data() call is executed. In this case the PCILIB_ERROR_OVERWRITTEN error will be returned by pcilib_return_data() call. I guess this is a bad idea and have to be changed. Meanwhile, for the ipecamera implementation the image data will be never overwritten. However, the raw data may get overwritten and the error code of pcilib_return_data() has to be consulted.
Parameters
[in,out] ctx - pcilib context
[in] event_id - specifies the ID of event to get data from
[in] data_type - specifies the desired type of data
PCILIB_EVENT_DATA will request the default data type
PCILIB_EVENT_RAW_DATA will request the raw data
The other types of data may be defined by event engine
[out] size_or_err - contain error code if function returns NULL or number of actually written bytes otherwise
Returns
- the pointer to the requested data or NULL otherwise
{
    int err;
    void *res = NULL;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_api_description_t *api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        if (size) *size = (size_t)PCILIB_ERROR_NOTSUPPORTED;
        return NULL;
    }
    if (api->get_data) {
        err = api->get_data(ctx->event_ctx, event_id, data_type, 0, NULL, size, &res);
        if (err) {
            if (size) *size = (size_t)err;
            return NULL;
        }
        return res;
    }
    if (size) *size = (size_t)PCILIB_ERROR_NOTSUPPORTED;
    return NULL;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::get_data, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
pcilib_get_data_with_argument()
void * pcilib_get_data_with_argument (pcilib_t * ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void * arg, size_t * size_or_err)
Returns pointer to the data of the specified type associated with the specified event.
The data should be returned back to the Event engine using pcilib_return_data() call. WARNING: Current implementation may overwrite the data before the pcilib_return_data() call is executed,
See also
pcilib_get_data() for details. Overall this function is very similar to pcilib_get_data(), but allows to specify implementation specific argument explaining the requested data format.
Parameters
[in,out] ctx - pcilib context
[in] event_id - specifies the ID of event to get data from
[in] data_type - specifies the desired type of data
PCILIB_EVENT_DATA will request the default data type
PCILIB_EVENT_RAW_DATA will request the raw data
The other types of data may be defined by event engine
[in] arg_size - specifies the size of arg in bytes
[in] arg - implementation-specific argument expalining the requested data format
[out] size_or_err - contain error code if function returns NULL or number of actually written bytes otherwise
Returns
- the pointer to the requested data or NULL otherwise
{
    int err;
    void *res = NULL;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_api_description_t *api = model_info->api;
    if (!api) {
        if (size) *size = (size_t)PCILIB_ERROR_NOTSUPPORTED;
        pcilib_error("Event API is not supported by the selected model");
        return NULL;
    }
    if (api->get_data) {
        err = api->get_data(ctx->event_ctx, event_id, data_type, arg_size, arg, size, &res);
        if (err) {
            if (size) *size = (size_t)err;
            return NULL;
        }
        return res;
    }
    if (size) *size = (size_t)PCILIB_ERROR_NOTSUPPORTED;
    return NULL;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::get_data, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
pcilib_grab()
int pcilib_grab (pcilib_t * ctx, pcilib_event_t event, size_t * size, void ** data, pcilib_timeout_t timeout)
This is a simples way to grab the data from the event engine.
The event engine is started, a software trigger for the specified event is issued if timeout is equal to PCILIB_TIMEOUT_IMMEDIATE, event is grabbed and the default data is copied into the user buffer. Then, the grabbing is stopped.
Parameters
[in,out] ctx - pcilib context
[in] event - the event to trigger and/or event mask to grab
[in,out] size - specifies the size of the provided buffer (if user supplies the buffer), the amount of data actually written is returned in this paramter
[in,out] data - Either contains a pointer to user-supplied buffer where the data will be written or pointer to NULL otherwise. In the later case, the pointer to newly allocated buffer will be returned in case of success. It is responsibility of the user to free the memory in this case. In case of failure, the content of data is undefined.
[in] timeout - either is equal to PCILIB_TIMEOUT_IMMEDIATE for immediate software trigger or specifies number of microseconds to wait for event triggered by hardware
Returns
- error code or 0 on success
{
    int err;
    pcilib_event_id_t eid;
    pcilib_grab_callback_user_data_t user = {ctx, size, data};
    err = pcilib_start(ctx, event_mask, PCILIB_EVENT_FLAGS_DEFAULT);
    if (!err) {
        if (timeout == PCILIB_TIMEOUT_IMMEDIATE) {
             err = pcilib_trigger(ctx, event_mask, 0, NULL);
             timeout = PCILIB_EVENT_TIMEOUT;
        }
    }
    if (!err) {
        err = pcilib_get_next_event(ctx, timeout, &eid, 0, NULL);
        if (!err) pcilib_grab_callback(event_mask, eid, &user);
    }
    pcilib_stop(ctx, PCILIB_EVENT_FLAGS_DEFAULT);
    return err;
}
References PCILIB_EVENT_FLAGS_DEFAULT, PCILIB_EVENT_TIMEOUT, pcilib_get_next_event(), pcilib_start(), pcilib_stop(), PCILIB_TIMEOUT_IMMEDIATE, and pcilib_trigger().
pcilib_return_data()
int pcilib_return_data (pcilib_t * ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, void * data)
{
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_api_description_t *api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->return_data)
        return api->return_data(ctx->event_ctx, event_id, data_type, data);
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), and pcilib_event_api_description_t::return_data.