pcilib: Public Property API
Public Property API
Properties is another abstraction on top of registers allowing arbitrary data types and computed registers.
Functions
pcilib_property_info_t * pcilib_get_property_list (pcilib_t *ctx, const char *branch, pcilib_list_flags_t flags)
Returns the list of properties available under the specified path.
void pcilib_free_property_info (pcilib_t *ctx, pcilib_property_info_t *info)
Cleans up the memory occupied by property list returned from the pcilib_get_property_list() call.
int pcilib_get_property_attr (pcilib_t *ctx, const char *prop, const char *attr, pcilib_value_t *val)
Extracts additional information about the specified register.
int pcilib_get_property (pcilib_t *ctx, const char *prop, pcilib_value_t *val)
Reads / computes the property value.
int pcilib_set_property (pcilib_t *ctx, const char *prop, const pcilib_value_t *val)
Writes the property value or executes the code associated with property.
Detailed Description
Properties is another abstraction on top of registers allowing arbitrary data types and computed registers.
Function Documentation
pcilib_free_property_info()
void pcilib_free_property_info (pcilib_t * ctx, pcilib_property_info_t * info)
Cleans up the memory occupied by property list returned from the pcilib_get_property_list() call.
Parameters
[in,out] ctx - pcilib context
[in,out] info - buffer to clean
{
    int i;
    for (i = 0; info[i].path; i++)
        free((char*)info[i].path);
    free(info);
}
References pcilib_property_info_t::path.
Referenced by pcilib_get_property_list().
pcilib_get_property()
int pcilib_get_property (pcilib_t * ctx, const char * prop, pcilib_value_t * val)
Reads / computes the property value.
Parameters
[in,out] ctx - pcilib context
[in] prop - property name (full name including path)
[out] val - the register value is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    return pcilib_read_register_view(ctx, NULL, NULL, prop, val);
}
References pcilib_read_register_view().
pcilib_get_property_attr()
int pcilib_get_property_attr (pcilib_t * ctx, const char * prop, const char * attr, pcilib_value_t * val)
Extracts additional information about the specified register.
Equivalent to the pcilib_get_register_attr_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] prop - property name (full name including path)
[in] attr - requested attribute name
[in,out] val - the value of attribute is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    pcilib_view_context_t *view_ctx;
    view_ctx = pcilib_find_view_context_by_name(ctx, prop);
    if (!view_ctx) {
        pcilib_error("The specified property (%s) is not found", prop);
        return PCILIB_ERROR_NOTFOUND;
    }
    if (!view_ctx->xml) return PCILIB_ERROR_NOTFOUND;
    return pcilib_get_xml_attr(ctx, view_ctx->xml, attr, val);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_view_context_by_name(), pcilib_get_xml_attr(), and pcilib_view_context_s::xml.
pcilib_get_property_list()
pcilib_property_info_t * pcilib_get_property_list (pcilib_t * ctx, const char * branch, pcilib_list_flags_t flags)
Returns the list of properties available under the specified path.
Parameters
[in,out] ctx - pcilib context
[in] branch - path or NULL to return the top-level properties
[in] flags - not used at the moment
Returns
- the list of the properties which should be cleaned with pcilib_free_property_info() or NULL in the case of error
{
    int err = 0;
    size_t pos = 0;
    size_t name_offset = 0;
    pcilib_view_context_t *view_ctx, *view_tmp;
    pcilib_property_info_t *info = (pcilib_property_info_t*)malloc((ctx->num_views + 1) * sizeof(pcilib_property_info_t));
    struct dir_hash_s {
        char *name;
        UT_hash_handle hh;
    } *dir_hash = NULL, *dir, *dir_tmp;
    if (branch) {
        name_offset = strlen(branch);
        if (branch[name_offset - 1] != '/') name_offset++;
    }
        // Find all folders
    HASH_ITER(hh, ctx->view_hash, view_ctx, view_tmp) {
        const pcilib_view_description_t *v = ctx->views[view_ctx->view];
        const char *subname = v->name + name_offset;
        const char *suffix;
        if (!(v->flags&PCILIB_VIEW_FLAG_PROPERTY)) continue;
        if ((branch)&&(strncasecmp(branch, v->name, strlen(branch)))) continue;
        suffix = strchr(subname, '/');
        if (suffix) {
            char *name = strndup(v->name, suffix - v->name);
            if (!name) {
                err = PCILIB_ERROR_MEMORY;
                break;
            }
            HASH_FIND_STR(dir_hash, name + name_offset, dir);
            if (dir) {
                free(name);
                continue;
            }
            dir = (struct dir_hash_s*)malloc(sizeof(struct dir_hash_s));
            if (!dir) {
                err = PCILIB_ERROR_MEMORY;
                break;
            }
            dir->name = name;
            HASH_ADD_KEYPTR(hh, dir_hash, dir->name + name_offset, strlen(dir->name + name_offset), dir);
        }
    }
    HASH_ITER(hh, ctx->view_hash, view_ctx, view_tmp) {
        const pcilib_view_description_t *v = ctx->views[view_ctx->view];
        const char *subname = v->name + name_offset;
        if (!(v->flags&PCILIB_VIEW_FLAG_PROPERTY)) continue;
        if ((branch)&&(strncasecmp(branch, v->name, strlen(branch)))) continue;
        if (!strchr(subname, '/')) {
            pcilib_view_context_t *found_view;
            char *path = strdup(v->name);
            if (!path) {
                err = PCILIB_ERROR_MEMORY;
                break;
            }
            char *name = strrchr(v->name, '/');
            if (name) name++;
            else name = path;
            HASH_FIND_STR(dir_hash, name, found_view);
            info[pos++] = (pcilib_property_info_t) {
                .name = name,
                .path = path,
                .description = v->description,
                .type = v->type,
                .mode = v->mode,
                .unit = v->unit,
                .flags = (found_view?PCILIB_LIST_FLAG_CHILDS:0)
            };
            if (found_view) HASH_DEL(dir_hash, found_view);
        }
    }
    HASH_ITER(hh, dir_hash, dir, dir_tmp) {
        char *name = strrchr(dir->name, '/');
        if (name) name++;
        else name = dir->name;
        info[pos++] = (pcilib_property_info_t) {
            .name = name,
            .path = dir->name,
            .type = PCILIB_TYPE_INVALID,
            .flags = PCILIB_LIST_FLAG_CHILDS
        };
    }
    HASH_ITER(hh, dir_hash, dir, dir_tmp) {
        HASH_DEL(dir_hash, dir);
        free(dir);
    }
    HASH_CLEAR(hh, dir_hash);
    memset(&info[pos], 0, sizeof(pcilib_property_info_t));
    if (err) {
        pcilib_free_property_info(ctx, info);
        return NULL;
    }
    return info;
}
References pcilib_view_description_s::description, pcilib_view_description_s::flags, pcilib_view_description_s::mode, pcilib_property_info_t::name, pcilib_view_description_s::name, pcilib_s::num_views, PCILIB_ERROR_MEMORY, pcilib_free_property_info(), PCILIB_LIST_FLAG_CHILDS, PCILIB_TYPE_INVALID, PCILIB_VIEW_FLAG_PROPERTY, pcilib_view_description_s::type, pcilib_view_description_s::unit, pcilib_view_context_s::view, pcilib_s::view_hash, and pcilib_s::views.
pcilib_set_property()
int pcilib_set_property (pcilib_t * ctx, const char * prop, const pcilib_value_t * val)
Writes the property value or executes the code associated with property.
Parameters
[in,out] ctx - pcilib context
[in] prop - property name (full name including path)
[out] val - the property value (see Polymorphic values),
Returns
- error code or 0 on success
{
    return pcilib_write_register_view(ctx, NULL, NULL, prop, val);
}
References pcilib_write_register_view().