pcilib: Public Event API
Public Event API
High level API for reading the structured data from hardware.
Functions
pcilib_context_t * pcilib_get_event_engine (pcilib_t *ctx)
Provides access to the context of event engine.
pcilib_event_t pcilib_find_event (pcilib_t *ctx, const char *event)
Resolves the event ID based on its name.
int pcilib_start (pcilib_t *ctx, pcilib_event_t ev_mask, pcilib_event_flags_t flags)
Analyzes current configuration, allocates necessary buffers and spawns required data processing threads.
int pcilib_stop (pcilib_t *ctx, pcilib_event_flags_t flags)
Stops event grabbing and optionally cleans up the used memory.
int pcilib_stream (pcilib_t *ctx, pcilib_event_callback_t callback, void *user)
Streams the incomming events to the provided callback function.
int pcilib_get_next_event (pcilib_t *ctx, pcilib_timeout_t timeout, pcilib_event_id_t *evid, size_t info_size, pcilib_event_info_t *info)
Waits until the next event is available.
int pcilib_configure_rawdata_callback (pcilib_t *ctx, pcilib_event_rawdata_callback_t callback, void *user)
Requests the streaming the rawdata from the event engine.
int pcilib_configure_autostop (pcilib_t *ctx, size_t max_events, pcilib_timeout_t duration)
Configures conditions when the grabbing will be stopped automatically.
int pcilib_configure_autotrigger (pcilib_t *ctx, pcilib_timeout_t interval, pcilib_event_t event, size_t trigger_size, void *trigger_data)
Request the auto-triggering while grabbing.
int pcilib_trigger (pcilib_t *ctx, pcilib_event_t event, size_t trigger_size, void *trigger_data)
Issues a single software trigger for the specified event.
Detailed Description
High level API for reading the structured data from hardware.
Function Documentation
pcilib_configure_autostop()
int pcilib_configure_autostop (pcilib_t * ctx, size_t max_events, pcilib_timeout_t duration)
Configures conditions when the grabbing will be stopped automatically.
The recording of new events may be stopped after reaching max_events records or when the specified amount of time is elapsed whatever happens first. However, the pcilib_stop() function still must be called afterwards.
This function should be exectued before the grabbing is started with pcilib_start(). NOTE that this options might not be respected if grabbing is started with the PCILIB_EVENT_FLAG_RAW_DATA_ONLY flag specified.
Parameters
[in,out] ctx - pcilib context
[in] max_events - specifies number of events after which the grabbing is stopped
[in] duration - specifies number of microseconds to run the grabbing, special values PCILIB_TIMEOUT_IMMEDIATE and PCILIB_TIMEOUT_INFINITE are supported.
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    ctx->event_ctx->params.autostop.max_events = max_events;
    ctx->event_ctx->params.autostop.duration = duration;
    return 0;
}
References pcilib_model_description_t::api, pcilib_event_parameters_t::autostop, pcilib_autostop_parameters_t::duration, pcilib_s::event_ctx, pcilib_autostop_parameters_t::max_events, pcilib_event_context_s::params, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
pcilib_configure_autotrigger()
int pcilib_configure_autotrigger (pcilib_t * ctx, pcilib_timeout_t interval, pcilib_event_t event, size_t trigger_size, void * trigger_data)
Request the auto-triggering while grabbing.
The software triggering is currently not supported (but planned). Therefore it is fully relied on hardware support. If no hardware support is available, PCILIB_ERROR_NOTSUPPORTED will be returned.
This function should be exectued before the grabbing is started with pcilib_start().
Parameters
[in,out] ctx - pcilib context
[in] interval - instructs hardware that each interval microseconds a new trigger should be issued
[in] event - specifies ID of the event which will be triggered
[in] trigger_size - specifies the size of trigger buffer
[in] trigger_data - this implementation-specific buffer which will be passed through to the Event engine
Returns
- error code or 0 on success
{
        /* To support hardware without autotriggering, we need to provide in event.c a code
        to generate multiple triggers in a thread (available in cli). The function should
        be re-enabled afterwards: just set parameters and let implementation decide if it
        can make triggering in hardware or will use our emulation */
    return PCILIB_ERROR_NOTSUPPORTED;
}
References PCILIB_ERROR_NOTSUPPORTED.
pcilib_configure_rawdata_callback()
int pcilib_configure_rawdata_callback (pcilib_t * ctx, pcilib_event_rawdata_callback_t callback, void * user)
Requests the streaming the rawdata from the event engine.
The callback will be called each time new DMA packet is received. It is the fastest way to acuqire data. No memory copies performed and DMA buffers are directly passed to the specified callback. However, to prevent data loss, no long processing is allowed is only expected to copy data into the appropriate place and return control to the event engine.
This function should be exectued before the grabbing is started with pcilib_start(). The performance can be boosted further by disabling any data processing within the event engine. This is achieved by passing the PCILIB_EVENT_FLAG_RAW_DATA_ONLY flag to pcilib_start() function while starting the grabbing.
Parameters
[in,out] ctx - pcilib context
[in] callback - callback function to call for each event, the streaming is stopped if it return PCILIB_STREAMING_STOP or negative value indicating the error
[in,out] user - used data is passed through as the last parameter of callback function
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    ctx->event_ctx->params.rawdata.callback = callback;
    ctx->event_ctx->params.rawdata.user = user;
    return 0;
}
References pcilib_model_description_t::api, pcilib_rawdata_parameters_t::callback, pcilib_s::event_ctx, pcilib_event_context_s::params, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), pcilib_event_parameters_t::rawdata, and pcilib_rawdata_parameters_t::user.
pcilib_find_event()
pcilib_event_t pcilib_find_event (pcilib_t * ctx, const char * event)
Resolves the event ID based on its name.
Parameters
[in,out] ctx - pcilib context
[in] event - the event name
Returns
- the event ID or PCILIB_EVENT_INVALID if event is not found
{
    int i;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_event_description_t *events = model_info->events;
    for (i = 0; events[i].name; i++) {
        if (!strcasecmp(events[i].name, event)) return events[i].evid;
    }
    return (pcilib_event_t)-1;
}
References pcilib_model_description_t::events, pcilib_event_description_t::evid, pcilib_event_description_t::name, and pcilib_get_model_description().
pcilib_get_event_engine()
pcilib_context_t * pcilib_get_event_engine (pcilib_t * ctx)
Provides access to the context of event engine.
This may be required to call implementation-specific functions of event engine.
Parameters
[in,out] ctx - pcilib context
Returns
- context of event engine or NULL in the case of error. Depending on the implementation can be extension of pcilib_contex_t, it should be safe to type cast if you are running the correct engine.
{
    return ctx->event_ctx;
}
References pcilib_s::event_ctx.
pcilib_get_next_event()
int pcilib_get_next_event (pcilib_t * ctx, pcilib_timeout_t timeout, pcilib_event_id_t * evid, size_t info_size, pcilib_event_info_t * info)
Waits until the next event is available.
The event is only returned when all the data associated with the event is received from hardware. So, the raw data is necessarily present, but availability of alternative data formats is optional. Depending on the implementation and current configuration, the data decoding can be performed beforehand, in parallel, or only them the data is requested with pcilib_get_data() or pcilib_copy_data() calls.
The function is thread-safe. The multiple requests to pcilib_stream() and pcilib_get_next_event() will be automatically serialized by the event engine. The client application may get hold on the data from multiple events simultaneously. However, the data could be overwritten meanwhile by the hardware. The pcilib_return_data() will inform if it has happened by returning PCILIB_ERROR_OVERWRITTEN.
Parameters
[in,out] ctx - pcilib context
[in] timeout - specifies number of microseconds to wait for next event before reporting timeout, special values PCILIB_TIMEOUT_IMMEDIATE and PCILIB_TIMEOUT_INFINITE are supported.
[out] evid - the event ID is returned in this parameter
[in] info_size - the size of the passed event info structure (the implementation of event engine may extend the standad pcilib_event_info_t definition and provide extra information about the event. If big enough info buffer is provided, this additional information will be copied as well. Otherwise only standard information is provided.
[out] info - The information about the recorded event is written to info
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
//    pcilib_return_event_callback_context_t user;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->next_event)
        return api->next_event(ctx->event_ctx, timeout, evid, info_size, info);
/*
    if (api->stream) {
        err = api->stream(ctx->event_ctx, 1, timeout, pcilib_return_event_callback, &user);
        if (err) return err;
        if (evid) *evid = user->event_id;
        if (info) *info = user->info;
        return 0;
    }
*/
    pcilib_error("Event enumeration is not suppored by API");
    return PCILIB_ERROR_NOTSUPPORTED;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::next_event, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_model_description().
Referenced by pcilib_grab().
pcilib_start()
int pcilib_start (pcilib_t * ctx, pcilib_event_t ev_mask, pcilib_event_flags_t flags)
Analyzes current configuration, allocates necessary buffers and spawns required data processing threads.
Depending on the implementation and the current configuration, the actual event grabbing may start already here. In this case, the preprocessed events will be storred in the temporary buffers and may be lost if pcilib_stop() is called before reading them out. Alternatively, the actual grabbing may only commend when the pcilib_stream() or pcilib_get_next_event() functions are executed. The function is non-blocking and will return immediately after allocating required memory and spawning of the preprocessing threads. It is important to call pcilib_stop() in the end.
The grabbing will stop automatically if conditions defined using pcilib_configure_autostop() function are met. It also possible to stop grabbing using pcilib_stop() call at any moment.
The process- and thread-safety is implementation depedent. However, normally the event engine will depend on DMA and if DMA engine is process-safe it will ensure the process-safety for event engine as well. The thread-safety is not directly ensured by currently implemented Event engines. The functions of Event engine may be called from multiple threads, but it is the user responsibility to ensure that only a single function of Event engine is running at each moment. On other hand, the Event and register APIs may be used in parallel.
Parameters
[in,out] ctx - pcilib context
[in] ev_mask - specifies events to listen for, use PCILIB_EVENTS_ALL to grab all events
[in] flags - various implementation-specific flags controlling operation of event engine
PCILIB_EVENT_FLAG_PREPROCESS - requires event preprocessing (i.e. event data is decoded before it is requested, this is often required for multi-threaded processing)
PCILIB_EVENT_FLAG_RAW_DATA_ONLY - disables data processing at all, only raw data will be provided in this case
Returns
- error code or 0 on success
{
    int err;
    pcilib_register_value_t max_threads;
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    err = pcilib_read_register(ctx, "conf", "max_threads", &max_threads);
    if (!err) {
        err = pcilib_configure_preprocessing_threads(ctx, max_threads);
        if (err) pcilib_warning("Error (%i) configuring number of preprocessing threads", err);
    }
    if (api->start)
        return api->start(ctx->event_ctx, event_mask, flags);
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_configure_preprocessing_threads(), pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), pcilib_read_register(), pcilib_warning, and pcilib_event_api_description_t::start.
Referenced by pcilib_grab().
pcilib_stop()
int pcilib_stop (pcilib_t * ctx, pcilib_event_flags_t flags)
Stops event grabbing and optionally cleans up the used memory.
This function operates in two modes. If PCILIB_EVENT_FLAG_STOP_ONLY flag is specified, the event grabbing is stopped, but all memory structures are kept intact. This also forces the blocked pcilib_stream() and pcilib_get_next_event() to return after a short while.
Unlike DMA engine, the event engine is not persistent and is always completely stopped when application is finished. Therefore, later the pcilib_stop() should be necessarily called again without PCILIB_EVENT_FLAG_STOP_ONLY flag to commend full clean up and release all used memory. Such call may only be issued when no threads are using Event engine any more. There should be no functions waiting for next event to appear and all of the obtained event data should be already returned back to the system.
pcilib_stop executed with PCILIB_EVENT_FLAG_STOP_ONLY is thread safe. The full version of the function is not and should be never called in parallel with any other action of the event engine. Actually, it is thread safe in the case of ipecamera, but this is not guaranteed for other event engines.
Parameters
[in,out] ctx - pcilib context
[in] flags - flags specifying operation mode
PCILIB_EVENT_FLAG_STOP_ONLY - instructs library to keep all the data structures intact and to onlystop the data grabbing
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->stop)
        return api->stop(ctx->event_ctx, flags);
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), and pcilib_event_api_description_t::stop.
Referenced by pcilib_grab().
pcilib_stream()
int pcilib_stream (pcilib_t * ctx, pcilib_event_callback_t callback, void * user)
Streams the incomming events to the provided callback function.
If Event engine is not started yet, it will be started and terminated upon the completion of the call. The streaming will continue while Event engine is started and the callback function does not return an error (negative) or PCILIB_STREAMING_STOP.
The callback is called only when all the data associated with the event is received from hardware. So, the raw data is necessarily present, but availability of alternative data formats is optional. Depending on the implementation and current configuration, the data decoding can be performed beforehand, in parallel with callback execution, or only them the data is requested with pcilib_get_data() or pcilib_copy_data() calls.
The function is thread-safe. The multiple requests to pcilib_stream() and pcilib_get_next_event() will be automatically serialized by the event engine. The pcilib_stream() is running in the single thread and no new calls to callback are issued until currently executed callback returns. The client application may get hold on the data from multiple events simultaneously. However, the data could be overwritten meanwhile by the hardware. The pcilib_return_data() will inform if it has happened by returning PCILIB_ERROR_OVERWRITTEN.
Parameters
[in,out] ctx - pcilib context
[in] callback - callback function to call for each event, the streaming is stopped if it return PCILIB_STREAMING_STOP or negative value indicating the error
[in,out] user - used data is passed through as the last parameter of callback function
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->stream)
        return api->stream(ctx->event_ctx, callback, user);
    if (api->next_event) {
        pcilib_error("Streaming using next_event API is not implemented yet");
    }
    pcilib_error("Event enumeration is not suppored by API");
    return PCILIB_ERROR_NOTSUPPORTED;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_event_api_description_t::next_event, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), and pcilib_event_api_description_t::stream.
pcilib_trigger()
int pcilib_trigger (pcilib_t * ctx, pcilib_event_t event, size_t trigger_size, void * trigger_data)
Issues a single software trigger for the specified event.
No hardware support is required. The function is fully thread safe and can be called while other thread is blocked in the pcilib_stream() or pcilib_get_next_event() calls.
Parameters
[in,out] ctx - pcilib context
[in] event - specifies ID of the event to trigger
[in] trigger_size - specifies the size of trigger buffer
[in] trigger_data - this implementation-specific buffer which will be passed through to the Event engine
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->trigger)
        return api->trigger(ctx->event_ctx, event, trigger_size, trigger_data);
    pcilib_error("Self triggering is not supported by the selected model");
    return PCILIB_ERROR_NOTSUPPORTED;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), and pcilib_event_api_description_t::trigger.
Referenced by pcilib_grab().