pcilib: Polymorphic values
Polymorphic values
API for manipulation of data formats and units.
Functions
void pcilib_clean_value (pcilib_t *ctx, pcilib_value_t *val)
Destroys the polymorphic value and frees any extra used memory, but does not free pcilib_value_t itself.
int pcilib_copy_value (pcilib_t *ctx, pcilib_value_t *dst, const pcilib_value_t *src)
Copies the polymorphic value.
int pcilib_set_value_from_float (pcilib_t *ctx, pcilib_value_t *val, double fval)
Initializes the polymorphic value from floating-point number.
int pcilib_set_value_from_int (pcilib_t *ctx, pcilib_value_t *val, long ival)
Initializes the polymorphic value from integer.
int pcilib_set_value_from_register_value (pcilib_t *ctx, pcilib_value_t *val, pcilib_register_value_t regval)
Initializes the polymorphic value from the register value.
int pcilib_set_value_from_static_string (pcilib_t *ctx, pcilib_value_t *val, const char *str)
Initializes the polymorphic value from the static string.
int pcilib_set_value_from_string (pcilib_t *ctx, pcilib_value_t *val, const char *str)
Initializes the polymorphic value from the string.
double pcilib_get_value_as_float (pcilib_t *ctx, const pcilib_value_t *val, int *err)
Get the floating point value from the polymorphic type.
long pcilib_get_value_as_int (pcilib_t *ctx, const pcilib_value_t *val, int *err)
Get the integer value from the polymorphic type.
pcilib_register_value_t pcilib_get_value_as_register_value (pcilib_t *ctx, const pcilib_value_t *val, int *err)
Get the integer value from the polymorphic type.
int pcilib_convert_value_unit (pcilib_t *ctx, pcilib_value_t *val, const char *unit_name)
Convert the units of the supplied polymorphic value.
int pcilib_convert_value_type (pcilib_t *ctx, pcilib_value_t *val, pcilib_value_type_t type)
Convert the type of the supplied polymorphic value.
Detailed Description
API for manipulation of data formats and units.
Function Documentation
pcilib_clean_value()
void pcilib_clean_value (pcilib_t * ctx, pcilib_value_t * val)
Destroys the polymorphic value and frees any extra used memory, but does not free pcilib_value_t itself.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
{
    if (!val) return;
    if (val->data) {
        free(val->data);
        val->data = NULL;
    }
    memset(val, 0, sizeof(pcilib_value_t));
}
References pcilib_value_t::data.
Referenced by pcilib_copy_value(), pcilib_get_value_as_float(), pcilib_get_value_as_int(), pcilib_get_value_as_register_value(), pcilib_read_register_view_by_id(), pcilib_set_value_from_float(), pcilib_set_value_from_int(), pcilib_set_value_from_static_string(), and pcilib_set_value_from_string().
pcilib_convert_value_type()
int pcilib_convert_value_type (pcilib_t * ctx, pcilib_value_t * val, pcilib_value_type_t type)
Convert the type of the supplied polymorphic value.
The error will be reported if conversion is not supported or failed due to non-conformant content.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value of any type
[in] type - the requested type
Returns
err - error code or 0 on sccuess
{
    if (val->type == PCILIB_TYPE_INVALID) {
        pcilib_error("Can't convert uninitialized value");
        return PCILIB_ERROR_NOTINITIALIZED;
    }
    switch (type) {
     case PCILIB_TYPE_STRING:
        switch (val->type) {
         case PCILIB_TYPE_STRING:
            return 0;
         case PCILIB_TYPE_DOUBLE:
            sprintf(val->str, (val->format?val->format:"%lf"), val->fval);
            val->format = NULL;
            break;
         case PCILIB_TYPE_LONG:
            sprintf(val->str, (val->format?val->format:"%li"), val->ival);
            val->format = NULL;
            break;
         default:
            return PCILIB_ERROR_NOTSUPPORTED;
        }
        val->sval = val->str;
        break;
     case PCILIB_TYPE_DOUBLE:
        switch (val->type) {
         case PCILIB_TYPE_STRING:
            if (sscanf(val->sval, "%lf", &val->fval) != 1) {
                pcilib_warning("Can't convert string (%s) to float", val->sval);
                return PCILIB_ERROR_INVALID_DATA;
            }
            val->format = NULL;
            break;
         case PCILIB_TYPE_DOUBLE:
            return 0;
         case PCILIB_TYPE_LONG:
            val->fval = val->ival;
            val->format = NULL;
            break;
         default:
            return PCILIB_ERROR_NOTSUPPORTED;
        }
        break;
     case PCILIB_TYPE_LONG:
        switch (val->type) {
         case PCILIB_TYPE_STRING:
            if (pcilib_isnumber(val->sval)) {
                if (sscanf(val->sval, "%li", &val->ival) != 1) {
                    pcilib_warning("Can't convert string (%s) to int", val->sval);
                    return PCILIB_ERROR_INVALID_DATA;
                }
                val->format = NULL;
            } else if (pcilib_isxnumber(val->sval)) {
                if (sscanf(val->sval, "%lx", &val->ival) != 1) {
                    pcilib_warning("Can't convert string (%s) to int", val->sval);
                    return PCILIB_ERROR_INVALID_DATA;
                }
                val->format = "0x%lx";
            } else {
                pcilib_warning("Can't convert string (%s) to int", val->sval);
                return PCILIB_ERROR_INVALID_DATA;
            }
            break;
         case PCILIB_TYPE_DOUBLE:
            if (val->fval != round(val->fval))
                pcilib_info("Precision is lost while converting float value %lf to integer %.0lf", val->fval, round(val->fval));
            val->ival = round(val->fval);
            val->format = NULL;
            break;
         case PCILIB_TYPE_LONG:
            return 0;
         default:
            return PCILIB_ERROR_NOTSUPPORTED;
        }
     break;
     default:
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    val->type = type;
    return 0;
}
References pcilib_value_t::format, pcilib_value_t::fval, pcilib_value_t::ival, pcilib_error, PCILIB_ERROR_INVALID_DATA, PCILIB_ERROR_NOTINITIALIZED, PCILIB_ERROR_NOTSUPPORTED, pcilib_info, pcilib_isnumber(), pcilib_isxnumber(), PCILIB_TYPE_DOUBLE, PCILIB_TYPE_INVALID, PCILIB_TYPE_LONG, PCILIB_TYPE_STRING, pcilib_warning, pcilib_value_t::str, pcilib_value_t::sval, and pcilib_value_t::type.
Referenced by pcilib_get_value_as_float(), pcilib_get_value_as_int(), pcilib_get_value_as_register_value(), and pcilib_write_register_view_by_id().
pcilib_convert_value_unit()
int pcilib_convert_value_unit (pcilib_t * ctx, pcilib_value_t * val, const char * unit_name)
Convert the units of the supplied polymorphic value.
The error will be reported if currently used units of the value are unknown, the requested conversion is not supported, or the value is not numeric.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value of any numeric type
[in] unit_name - the requested units
Returns
err - error code or 0 on sccuess
{
    if (val->type == PCILIB_TYPE_INVALID) {
        pcilib_error("Can't convert uninitialized value");
        return PCILIB_ERROR_NOTINITIALIZED;
    }
    if ((val->type != PCILIB_TYPE_DOUBLE)&&(val->type != PCILIB_TYPE_LONG)) {
        pcilib_error("Can't convert value of type %u, only values with integer and float types can be converted to different units", val->type);
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    if (!val->unit) {
        pcilib_error("Can't convert value with the unspecified unit");
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    pcilib_unit_t unit = pcilib_find_unit_by_name(ctx, val->unit);
    if (unit == PCILIB_UNIT_INVALID) {
        pcilib_error("Can't convert unrecognized unit %s", val->unit);
        return PCILIB_ERROR_NOTFOUND;
    }
    return pcilib_transform_unit_by_name(ctx, unit_name, val);
}
References pcilib_error, PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_ERROR_NOTFOUND, PCILIB_ERROR_NOTINITIALIZED, pcilib_find_unit_by_name(), pcilib_transform_unit_by_name(), PCILIB_TYPE_DOUBLE, PCILIB_TYPE_INVALID, PCILIB_TYPE_LONG, PCILIB_UNIT_INVALID, pcilib_value_t::type, and pcilib_value_t::unit.
pcilib_copy_value()
int pcilib_copy_value (pcilib_t * ctx, pcilib_value_t * dst, const pcilib_value_t * src)
Copies the polymorphic value.
If dst already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] dst - initialized polymorphic value
[in] src - initialized polymorphic value
Returns
- 0 on success or memory error
{
    if (dst->type != PCILIB_TYPE_INVALID)
        pcilib_clean_value(ctx, dst);
    memcpy(dst, src, sizeof(pcilib_value_t));
    if ((src->size)&&(src->data)) {
        dst->data = malloc(src->size);
        if (!dst->data) {
            dst->type = PCILIB_TYPE_INVALID;
            return PCILIB_ERROR_MEMORY;
        }
        memcpy(dst->data, src->data, src->size);
    }
    return 0;
}
References pcilib_value_t::data, pcilib_clean_value(), PCILIB_ERROR_MEMORY, PCILIB_TYPE_INVALID, pcilib_value_t::size, and pcilib_value_t::type.
Referenced by pcilib_get_value_as_float(), pcilib_get_value_as_int(), pcilib_get_value_as_register_value(), and pcilib_write_register_view_by_id().
pcilib_get_value_as_float()
double pcilib_get_value_as_float (pcilib_t * ctx, const pcilib_value_t * val, int * err)
Get the floating point value from the polymorphic type.
May inmply impliced type conversion, for isntance parsing the number from the string. Will return 0. and report an error if conversion failed.
Parameters
[in] ctx - pcilib context
[in] val - initialized polymorphic value of arbitrary type
[out] err - error code or 0 on sccuess
Returns
- the value or 0 in the case of error
{
    int err;
    double res;
    pcilib_value_t copy = {0};
    err = pcilib_copy_value(ctx, &copy, val);
    if (err) {
        if (ret) *ret = err;
        return 0.;
    }
    err = pcilib_convert_value_type(ctx, &copy, PCILIB_TYPE_DOUBLE);
    if (err) {
        if (ret) *ret = err;
        return 0.;
    }
    if (ret) *ret = 0;
    res = copy.fval;
    pcilib_clean_value(ctx, &copy);
    return res;
}
References pcilib_value_t::fval, pcilib_clean_value(), pcilib_convert_value_type(), pcilib_copy_value(), and PCILIB_TYPE_DOUBLE.
Referenced by pcilib_get_value_as_pyobject().
pcilib_get_value_as_int()
long pcilib_get_value_as_int (pcilib_t * ctx, const pcilib_value_t * val, int * err)
Get the integer value from the polymorphic type.
May inmply impliced type conversion resulting in precision loss if the val stores floating-point number. The warning message will be printed in this case, but no error returned.
Parameters
[in] ctx - pcilib context
[in] val - initialized polymorphic value of arbitrary type
[out] err - error code or 0 on sccuess
Returns
- the value or 0 in the case of error
{
    int err;
    long res;
    pcilib_value_t copy = {0};
    err = pcilib_copy_value(ctx, &copy, val);
    if (err) {
        if (ret) *ret = err;
        return 0;
    }
    err = pcilib_convert_value_type(ctx, &copy, PCILIB_TYPE_LONG);
    if (err) {
        if (ret) *ret = err;
        return 0;
    }
    if (ret) *ret = 0;
    res = copy.ival;
    pcilib_clean_value(ctx, &copy);
    return res;
}
References pcilib_value_t::ival, pcilib_clean_value(), pcilib_convert_value_type(), pcilib_copy_value(), and PCILIB_TYPE_LONG.
Referenced by pcilib_get_value_as_pyobject().
pcilib_get_value_as_register_value()
pcilib_register_value_t pcilib_get_value_as_register_value (pcilib_t * ctx, const pcilib_value_t * val, int * err)
Get the integer value from the polymorphic type.
May inmply impliced type conversion resulting in precision loss if the val stores floating-point number or complete data corruption if negative number is stored. The warning message will be printed in this case, but no error returned.
Parameters
[in] ctx - pcilib context
[in] val - initialized polymorphic value of arbitrary type
[out] err - error code or 0 on sccuess
Returns
- the value or 0 in the case of error
{
    int err;
    pcilib_register_value_t res;
    pcilib_value_t copy = {0};
    err = pcilib_copy_value(ctx, &copy, val);
    if (err) {
        if (ret) *ret = err;
        return 0.;
    }
    err = pcilib_convert_value_type(ctx, &copy, PCILIB_TYPE_LONG);
    if (err) {
        if (ret) *ret = err;
        return 0.;
    }
    if (ret) *ret = 0;
    res = copy.ival;
    if (copy.ival < 0)
        pcilib_warning("Data corruption while converting negative polymorph value (%li) to the register type, result %u", copy.ival, res);
    pcilib_clean_value(ctx, &copy);
    return res;
}
References pcilib_value_t::ival, pcilib_clean_value(), pcilib_convert_value_type(), pcilib_copy_value(), PCILIB_TYPE_LONG, and pcilib_warning.
pcilib_set_value_from_float()
int pcilib_set_value_from_float (pcilib_t * ctx, pcilib_value_t * val, double fval)
Initializes the polymorphic value from floating-point number.
If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] fval - initializer
Returns
- 0 on success or memory error
{
    pcilib_clean_value(ctx, value);
    value->type = PCILIB_TYPE_DOUBLE;
    value->fval = fval;
    return 0;
}
References pcilib_value_t::fval, pcilib_clean_value(), PCILIB_TYPE_DOUBLE, and pcilib_value_t::type.
Referenced by pcilib_py_eval_string(), and pcilib_set_value_from_pyobject().
pcilib_set_value_from_int()
int pcilib_set_value_from_int (pcilib_t * ctx, pcilib_value_t * val, long ival)
Initializes the polymorphic value from integer.
If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] ival - initializer
Returns
- 0 on success or memory error
{
    pcilib_clean_value(ctx, value);
    value->type = PCILIB_TYPE_LONG;
    value->ival = ival;
    return 0;
}
References pcilib_value_t::ival, pcilib_clean_value(), PCILIB_TYPE_LONG, and pcilib_value_t::type.
Referenced by pcilib_set_value_from_pyobject(), and pcilib_set_value_from_register_value().
pcilib_set_value_from_register_value()
int pcilib_set_value_from_register_value (pcilib_t * ctx, pcilib_value_t * val, pcilib_register_value_t regval)
Initializes the polymorphic value from the register value.
If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] regval - initializer
Returns
- 0 on success or memory error
{
    return pcilib_set_value_from_int(ctx, value, regval);
}
References pcilib_set_value_from_int().
pcilib_set_value_from_static_string()
int pcilib_set_value_from_static_string (pcilib_t * ctx, pcilib_value_t * val, const char * str)
Initializes the polymorphic value from the static string.
The string is not copied, but only referenced. If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] str - initializer
Returns
- 0 on success or memory error
{
    pcilib_clean_value(ctx, value);
    value->type = PCILIB_TYPE_STRING;
    value->sval = str;
    return 0;
}
References pcilib_clean_value(), PCILIB_TYPE_STRING, pcilib_value_t::sval, and pcilib_value_t::type.
Referenced by pcilib_get_xml_attr().
pcilib_set_value_from_string()
int pcilib_set_value_from_string (pcilib_t * ctx, pcilib_value_t * val, const char * str)
Initializes the polymorphic value from the string.
The string is copied. If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] str - initializer
Returns
- 0 on success or memory error
{
    size_t len;
    pcilib_clean_value(ctx, value);
    len = strlen(str) + 1;
    if (len < sizeof(value->str)) {
        memcpy(value->str, str, len);
        value->sval = value->str;
    } else {
        value->data = (void*)strdup(str);
        if (!value->data) return PCILIB_ERROR_MEMORY;
        value->size = strlen(str) + 1;
        value->sval = value->data;
    }
    value->type = PCILIB_TYPE_STRING;
    return 0;
}
References pcilib_value_t::data, pcilib_clean_value(), PCILIB_ERROR_MEMORY, PCILIB_TYPE_STRING, pcilib_value_t::size, pcilib_value_t::str, pcilib_value_t::sval, and pcilib_value_t::type.
Referenced by pcilib_set_value_from_pyobject().