pcilib: Public Register API
Public Register API
API for register manipulations.
Functions
pcilib_register_info_t * pcilib_get_register_list (pcilib_t *ctx, const char *bank, pcilib_list_flags_t flags)
Returns the list of registers provided by the hardware model.
pcilib_register_info_t * pcilib_get_register_info (pcilib_t *ctx, const char *bank, const char *reg, pcilib_list_flags_t flags)
Returns the information about the specified register.
void pcilib_free_register_info (pcilib_t *ctx, pcilib_register_info_t *info)
Cleans up the memory occupied by register list returned from the pcilib_get_register_list() and pcilib_get_register_info() calls.
pcilib_register_t pcilib_find_register (pcilib_t *ctx, const char *bank, const char *reg)
Finds register id corresponding to the specified bank and register names.
int pcilib_get_register_attr_by_id (pcilib_t *ctx, pcilib_register_t reg, const char *attr, pcilib_value_t *val)
Extracts additional information about the specified register.
int pcilib_get_register_attr (pcilib_t *ctx, const char *bank, const char *regname, const char *attr, pcilib_value_t *val)
Extracts additional information about the specified register.
int pcilib_read_register_space (pcilib_t *ctx, const char *bank, pcilib_register_addr_t addr, size_t n, pcilib_register_value_t *buf)
Reads one or multiple sequential registers from the specified register bank.
int pcilib_write_register_space (pcilib_t *ctx, const char *bank, pcilib_register_addr_t addr, size_t n, const pcilib_register_value_t *buf)
Writes one or multiple sequential registers from the specified register bank.
int pcilib_read_register_by_id (pcilib_t *ctx, pcilib_register_t reg, pcilib_register_value_t *value)
Reads the specified register.
int pcilib_write_register_by_id (pcilib_t *ctx, pcilib_register_t reg, pcilib_register_value_t value)
Writes to the specified register.
int pcilib_read_register (pcilib_t *ctx, const char *bank, const char *regname, pcilib_register_value_t *value)
Reads the specified register.
int pcilib_write_register (pcilib_t *ctx, const char *bank, const char *regname, pcilib_register_value_t value)
Writes to the specified register.
int pcilib_read_register_view_by_id (pcilib_t *ctx, pcilib_register_t reg, const char *view, pcilib_value_t *value)
Reads a view of the specified register.
int pcilib_write_register_view_by_id (pcilib_t *ctx, pcilib_register_t reg, const char *view, const pcilib_value_t *value)
Writes the specified register using value represented in the specified view.
int pcilib_read_register_view (pcilib_t *ctx, const char *bank, const char *regname, const char *view, pcilib_value_t *value)
Reads a view of the specified register.
int pcilib_write_register_view (pcilib_t *ctx, const char *bank, const char *regname, const char *view, const pcilib_value_t *value)
Writes the specified register using value represented in the specified view.
Detailed Description
API for register manipulations.
Function Documentation
pcilib_find_register()
pcilib_register_t pcilib_find_register (pcilib_t * ctx, const char * bank, const char * reg)
Finds register id corresponding to the specified bank and register names.
It is faster to access registers by id instead of names. Therefore, in long running applications it is preferred to resolve names of all required registers during initialization and access them using ids only.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] reg - the name of the register
Returns
- register id or PCILIB_REGISTER_INVALID if register is not found
{
    pcilib_register_t i;
    pcilib_register_bank_t bank_id;
    pcilib_register_bank_addr_t bank_addr = 0;
    pcilib_register_context_t *reg_ctx;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    const pcilib_register_description_t *registers =  model_info->registers;
    if (bank) {
        bank_id = pcilib_find_register_bank(ctx, bank);
        if (bank_id == PCILIB_REGISTER_BANK_INVALID) {
            pcilib_error("Invalid bank (%s) is specified", bank);
            return PCILIB_REGISTER_INVALID;
        }
        bank_addr = model_info->banks[bank_id].addr;
            // ToDo: we can use additionaly per-bank hashes
        for (i = 0; registers[i].bits; i++) {
            if ((!strcasecmp(registers[i].name, reg))&&((!bank)||(registers[i].bank == bank_addr))) return i;
        }
    } else {
        HASH_FIND_STR(ctx->reg_hash, reg, reg_ctx);
        if (reg_ctx) return reg_ctx->reg;
    }
    return PCILIB_REGISTER_INVALID;
};
References pcilib_register_bank_description_t::addr, pcilib_model_description_t::banks, pcilib_register_description_t::bits, pcilib_error, pcilib_find_register_bank(), pcilib_get_model_description(), PCILIB_REGISTER_BANK_INVALID, PCILIB_REGISTER_INVALID, pcilib_register_context_t::reg, pcilib_s::reg_hash, and pcilib_model_description_t::registers.
Referenced by pcilib_get_register_attr(), pcilib_get_register_info(), pcilib_read_register(), pcilib_read_register_view(), pcilib_resolve_register_address(), pcilib_write_register(), and pcilib_write_register_view().
pcilib_free_register_info()
void pcilib_free_register_info (pcilib_t * ctx, pcilib_register_info_t * info)
Cleans up the memory occupied by register list returned from the pcilib_get_register_list() and pcilib_get_register_info() calls.
Parameters
[in,out] ctx - pcilib context
[in,out] info - buffer to clean
{
    if (info)
        free(info);
}
pcilib_get_register_attr()
int pcilib_get_register_attr (pcilib_t * ctx, const char * bank, const char * regname, const char * attr, pcilib_value_t * val)
Extracts additional information about the specified register.
Equivalent to the pcilib_get_register_attr_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - register name
[in] attr - requested attribute name
[in,out] val - the value of attribute is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    pcilib_register_t reg;
    reg = pcilib_find_register(ctx, bank, regname);
    if (reg == PCILIB_REGISTER_INVALID) {
        pcilib_error("Register (%s) is not found", regname);
        return PCILIB_ERROR_NOTFOUND;
    }
    return pcilib_get_register_attr_by_id(ctx, reg, attr, val);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register(), pcilib_get_register_attr_by_id(), and PCILIB_REGISTER_INVALID.
pcilib_get_register_attr_by_id()
int pcilib_get_register_attr_by_id (pcilib_t * ctx, pcilib_register_t reg, const char * attr, pcilib_value_t * val)
Extracts additional information about the specified register.
The additional information is model-specific and are provided as extra XML attributes in XML-described registers. The available attributes are only restricted by used XSD schema.
Parameters
[in,out] ctx - pcilib context
[in] reg - register id
[in] attr - requested attribute name
[in,out] val - the value of attribute is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    int err;
    assert(reg < ctx->num_reg);
    err = pcilib_get_xml_attr(ctx, ctx->register_ctx[reg].xml, attr, val);
/*
        // Shall we return from parrent register if not found?
    if ((err == PCILIB_ERROR_NOTFOUND)&&(ctx->registers[reg].type == PCILIB_REGISTER_TYPE_BITS)) {
        pcilib_register_t parent = pcilib_find_standard_register_by_addr(ctx, ctx->registers[reg].addr);
        err = pcilib_get_xml_attr(ctx, ctx->register_ctx[parent].xml, attr, val);
    }
*/
    return err;
}
References pcilib_get_xml_attr(), pcilib_s::register_ctx, and pcilib_register_context_t::xml.
Referenced by pcilib_get_register_attr().
pcilib_get_register_info()
pcilib_register_info_t * pcilib_get_register_info (pcilib_t * ctx, const char * bank, const char * reg, pcilib_list_flags_t flags)
Returns the information about the specified register.
Parameters
[in,out] ctx - pcilib context
[in] bank - indicates the bank where to look for register, autodetected if NULL is passed
[in] reg - the name of the register
[in] flags - currently ignored
Returns
- information about the specified register which should be cleaned with pcilib_free_register_info() or NULL in the case of error
{
    pcilib_register_t i, from, to, pos = 0;
    pcilib_register_info_t *info;
    pcilib_register_bank_t bank;
    pcilib_register_bank_addr_t bank_addr;
    const char *bank_name;
    info = (pcilib_register_info_t*)malloc((ctx->num_reg + 1) * sizeof(pcilib_register_info_t));
    if (!info) return NULL;
    if (req_bank_name) {
        bank = pcilib_find_register_bank_by_name(ctx, req_bank_name);
        if (bank == PCILIB_REGISTER_BANK_INVALID) {
            pcilib_error("The specified bank (%s) is not found", req_bank_name);
            return NULL;
        }
        bank_addr = ctx->banks[bank].addr;
        bank_name = req_bank_name;
    } else {
        bank_addr = PCILIB_REGISTER_BANK_INVALID;
        bank_name = NULL;
    }
    if (req_reg_name) {
        pcilib_register_t reg = pcilib_find_register(ctx, req_bank_name, req_reg_name);
        if (reg == PCILIB_REGISTER_INVALID) {
            pcilib_error("The specified register (%s) is not found", req_reg_name);
            return NULL;
        }
        from = reg;
        to = reg + 1;
    } else {
        from = 0;
        to = ctx->num_reg;
    }
    for (i = from; i < to; i++) {
        const pcilib_register_value_range_t *range = &ctx->register_ctx[i].range;
        const pcilib_register_value_name_t *names = NULL;
        if (req_bank_name) {
            if (ctx->registers[i].bank != bank_addr) continue;
        } else {
            if (ctx->registers[i].bank != bank_addr) {
                bank_addr = ctx->registers[i].bank;
                bank = pcilib_find_register_bank_by_addr(ctx, bank_addr);
                if (bank == PCILIB_REGISTER_BANK_INVALID) bank_name = NULL;
                else bank_name = ctx->banks[bank].name;
            }
        }
        if (ctx->registers[i].views) {
            int j;
            for (j = 0; ctx->registers[i].views[j].view; j++) {
                pcilib_view_t view = pcilib_find_view_by_name(ctx, ctx->registers[i].views[j].view);
                if ((view != PCILIB_VIEW_INVALID)&&((ctx->views[view]->api == &pcilib_enum_view_xml_api)||(ctx->views[view]->api == &pcilib_enum_view_static_api)))
                    names = ((pcilib_enum_view_description_t*)(ctx->views[view]))->names;
            }
        }
        if (range->min == range->max)
            range = NULL;
        info[pos++] = (pcilib_register_info_t){
            .id = i,
            .name = ctx->registers[i].name,
            .description = ctx->registers[i].description,
            .bank = bank_name,
            .mode = ctx->registers[i].mode,
            .defvalue = ctx->registers[i].defvalue,
            .range = range,
            .values = names
        };
    }
    memset(&info[pos], 0, sizeof(pcilib_register_info_t));
    return info;
}
References pcilib_register_bank_description_t::addr, pcilib_view_description_s::api, pcilib_register_description_t::bank, pcilib_s::banks, pcilib_register_description_t::defvalue, pcilib_register_description_t::description, pcilib_register_info_t::id, pcilib_register_value_range_t::max, pcilib_register_value_range_t::min, pcilib_register_description_t::mode, pcilib_register_bank_description_t::name, pcilib_register_description_t::name, pcilib_s::num_reg, pcilib_error, pcilib_find_register(), pcilib_find_register_bank_by_addr(), pcilib_find_register_bank_by_name(), pcilib_find_view_by_name(), PCILIB_REGISTER_BANK_INVALID, PCILIB_REGISTER_INVALID, PCILIB_VIEW_INVALID, pcilib_register_context_t::range, pcilib_s::register_ctx, pcilib_s::registers, pcilib_view_reference_t::view, pcilib_s::views, and pcilib_register_description_t::views.
Referenced by pcilib_get_register_list().
pcilib_get_register_list()
pcilib_register_info_t * pcilib_get_register_list (pcilib_t * ctx, const char * bank, pcilib_list_flags_t flags)
Returns the list of registers provided by the hardware model.
Parameters
[in,out] ctx - pcilib context
[in] bank - if set, only register within the specified bank will be returned
[in] flags - currently ignored
Returns
- the list of the register which should be cleaned with pcilib_free_register_info() or NULL in the case of error
{
    return pcilib_get_register_info(ctx, req_bank_name, NULL, flags);
}
References pcilib_get_register_info().
pcilib_read_register()
int pcilib_read_register (pcilib_t * ctx, const char * bank, const char * regname, pcilib_register_value_t * value)
Reads the specified register.
Equivalent to the pcilib_read_register_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - the name of the register
[out] value - the register value is returned here
Returns
- error code or 0 on success
{
    int reg;
    reg = pcilib_find_register(ctx, bank, regname);
    if (reg == PCILIB_REGISTER_INVALID) {
        pcilib_error("Register (%s) is not found", regname);
        return PCILIB_ERROR_NOTFOUND;
    }
    return pcilib_read_register_by_id(ctx, reg, value);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register(), pcilib_read_register_by_id(), and PCILIB_REGISTER_INVALID.
Referenced by pcilib_start().
pcilib_read_register_by_id()
int pcilib_read_register_by_id (pcilib_t * ctx, pcilib_register_t reg, pcilib_register_value_t * value)
Reads the specified register.
Parameters
[in,out] ctx - pcilib context
[in] reg - register id
[out] value - the register value is returned here
Returns
- error code or 0 on success
{
    int err;
    size_t i, n;
    pcilib_register_size_t bits;
    pcilib_register_value_t res;
    pcilib_register_bank_t bank;
    const pcilib_register_description_t *r;
    const pcilib_register_bank_description_t *b;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    r = model_info->registers + reg;
    bank = pcilib_find_register_bank_by_addr(ctx, r->bank);
    if (bank == PCILIB_REGISTER_BANK_INVALID) return PCILIB_ERROR_INVALID_BANK;
    b = model_info->banks + bank;
    n = r->bits / b->access;
    bits = r->bits % b->access;
    pcilib_register_value_t buf[n + 1];
    err = pcilib_read_register_space_internal(ctx, bank, r->addr, n, r->offset, bits, buf);
    if ((b->endianess == PCILIB_BIG_ENDIAN)||((b->endianess == PCILIB_HOST_ENDIAN)&&(ntohs(1) == 1))) {
        pcilib_error("Big-endian byte order support is not implemented");
        return PCILIB_ERROR_NOTSUPPORTED;
    } else {
        res = 0;
        if (bits) ++n;
        for (i = 0; i < n; i++) {
            res |= buf[i] << (i * b->access);
        }
    }
    *value = res;
    return err;
}
References pcilib_register_bank_description_t::access, pcilib_register_description_t::addr, pcilib_register_description_t::bank, pcilib_model_description_t::banks, pcilib_register_description_t::bits, pcilib_register_bank_description_t::endianess, pcilib_register_description_t::offset, PCILIB_BIG_ENDIAN, pcilib_error, PCILIB_ERROR_INVALID_BANK, PCILIB_ERROR_NOTSUPPORTED, pcilib_find_register_bank_by_addr(), pcilib_get_model_description(), PCILIB_HOST_ENDIAN, PCILIB_REGISTER_BANK_INVALID, and pcilib_model_description_t::registers.
Referenced by pcilib_read_register(), and pcilib_read_register_view_by_id().
pcilib_read_register_space()
int pcilib_read_register_space (pcilib_t * ctx, const char * bank, pcilib_register_addr_t addr, size_t n, pcilib_register_value_t * buf)
Reads one or multiple sequential registers from the specified register bank.
This function may provide access to the undefined registers in the bank. In other cases, the pcilib_read_register() / pcilib_read_register_by_id() calls are preferred.
Parameters
[in,out] ctx - pcilib context
[in] bank - the bank to read (should be specified, no autodetection)
[in] addr - the register address within the bank, addresses are counted in bytes not registers (i.e. it is offset in bytes from the start of register bank)
[in] n - number of registers to read; i.e. n * register_size bytes will be read, where register_size is defined in the bank configuration (see pcilib_register_bank_description_t)
[out] buf - the buffer of n * register_size bytes long where the data will be stored
Returns
- error code or 0 on success
{
    pcilib_register_bank_t bank_id = pcilib_find_register_bank(ctx, bank);
    if (bank_id == PCILIB_REGISTER_BANK_INVALID) {
        if (bank) pcilib_error("Invalid register bank is specified (%s)", bank);
        else pcilib_error("Register bank should be specified");
        return PCILIB_ERROR_INVALID_BANK;
    }
    return pcilib_read_register_space_internal(ctx, bank_id, addr, n, 0, 0, buf);
}
References pcilib_error, PCILIB_ERROR_INVALID_BANK, pcilib_find_register_bank(), and PCILIB_REGISTER_BANK_INVALID.
pcilib_read_register_view()
int pcilib_read_register_view (pcilib_t * ctx, const char * bank, const char * regname, const char * view, pcilib_value_t * value)
Reads a view of the specified register.
The views allow to convert values to standard units or get self-explanatory names associated with the values (enums). Equivalent to the pcilib_read_register_view_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - the name of the register
[in] view - specifies the name of the view associated with register or desired units
[out] value - the register value is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use
Returns
- error code or 0 on success
{
    pcilib_register_t reg;
    if (regname) {
        reg = pcilib_find_register(ctx, bank, regname);
        if (reg == PCILIB_REGISTER_INVALID) {
            pcilib_error("Register (%s) is not found", regname);
            return PCILIB_ERROR_NOTFOUND;
        }
    } else {
        reg = PCILIB_REGISTER_INVALID;
    }
    return pcilib_read_register_view_by_id(ctx, reg, view, val);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register(), pcilib_read_register_view_by_id(), and PCILIB_REGISTER_INVALID.
Referenced by pcilib_get_property().
pcilib_read_register_view_by_id()
int pcilib_read_register_view_by_id (pcilib_t * ctx, pcilib_register_t reg, const char * view, pcilib_value_t * value)
Reads a view of the specified register.
The views allow to convert values to standard units or get self-explanatory names associated with the values (enums).
Parameters
[in,out] ctx - pcilib context
[in] reg - register id
[in] view - specifies the name of the view associated with register or desired units
[out] value - the register value is returned here (see Polymorphic values), pcilib_clean_value() will be executed if val contains data. Therefore it should be always initialized to 0 before first use.
Returns
- error code or 0 on success
{
    int err;
    const char *regname;
    pcilib_view_description_t *v;
    pcilib_view_configuration_t cfg;
    pcilib_register_value_t regvalue = 0;
    if (reg == PCILIB_REGISTER_INVALID) regname = NULL;
    else regname = ctx->registers[reg].name;
    err = pcilib_detect_view_configuration(ctx, reg, view, NULL, 0, &cfg);
    if (err) return err;
    v = ctx->views[cfg.view->view];
    if (!v->api->read_from_reg) {
        pcilib_error("The view (%s) does not support reading from the register", view);
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if ((v->mode & PCILIB_REGISTER_R) == 0) {
        pcilib_error("The view (%s) does not allow reading from the register", view);
        return PCILIB_ERROR_NOTPERMITED;
    }
    if (regname) {
        err = pcilib_read_register_by_id(ctx, cfg.reg, &regvalue);
        if (err) {
            pcilib_error("Error (%i) reading register %s", err, regname);
            return err;
        }
    }
    pcilib_clean_value(ctx, val);
    err = v->api->read_from_reg(ctx, cfg.view, regvalue, val);
    if (err) {
        if (regname)
            pcilib_error("Error (%i) computing view (%s) of register %s", err, view, regname);
        else
            pcilib_error("Error (%i) computing view %s", err, view);
        return err;
    }
    if (v->unit) {
        val->unit = v->unit;
    }
    if (cfg.trans) {
        err = pcilib_transform_unit(ctx, cfg.trans, val);
        if (err) return err;
    }
    return 0;
}
References pcilib_view_description_s::api, pcilib_view_description_s::mode, pcilib_register_description_t::name, pcilib_clean_value(), pcilib_error, PCILIB_ERROR_NOTPERMITED, PCILIB_ERROR_NOTSUPPORTED, pcilib_read_register_by_id(), PCILIB_REGISTER_INVALID, PCILIB_REGISTER_R, pcilib_transform_unit(), pcilib_view_api_description_t::read_from_reg, pcilib_view_configuration_t::reg, pcilib_s::registers, pcilib_view_configuration_t::trans, pcilib_value_t::unit, pcilib_view_description_s::unit, pcilib_view_configuration_t::view, pcilib_view_context_s::view, and pcilib_s::views.
Referenced by pcilib_read_register_view().
pcilib_write_register()
int pcilib_write_register (pcilib_t * ctx, const char * bank, const char * regname, pcilib_register_value_t value)
Writes to the specified register.
Equivalent to the pcilib_write_register_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - the name of the register
[in] value - the register value to write
Returns
- error code or 0 on success
{
    int reg;
    reg = pcilib_find_register(ctx, bank, regname);
    if (reg == PCILIB_REGISTER_INVALID) {
        pcilib_error("Register (%s) is not found", regname);
        return PCILIB_ERROR_NOTFOUND;
    }
    return pcilib_write_register_by_id(ctx, reg, value);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register(), PCILIB_REGISTER_INVALID, and pcilib_write_register_by_id().
pcilib_write_register_by_id()
int pcilib_write_register_by_id (pcilib_t * ctx, pcilib_register_t reg, pcilib_register_value_t value)
Writes to the specified register.
Parameters
[in,out] ctx - pcilib context
[in] reg - register id
[in] value - the register value to write
Returns
- error code or 0 on success
{
    int err;
    size_t i, n;
    pcilib_register_size_t bits;
    pcilib_register_bank_t bank;
    pcilib_register_value_t res;
    const pcilib_register_description_t *r;
    const pcilib_register_bank_description_t *b;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    r = model_info->registers + reg;
    bank = pcilib_find_register_bank_by_addr(ctx, r->bank);
    if (bank == PCILIB_REGISTER_BANK_INVALID) return PCILIB_ERROR_INVALID_BANK;
    b = model_info->banks + bank;
    n = r->bits / b->access;
    bits = r->bits % b->access;
    pcilib_register_value_t buf[n + 1];
    memset(buf, 0, (n + 1) * sizeof(pcilib_register_value_t));
    if ((b->endianess == PCILIB_BIG_ENDIAN)||((b->endianess == PCILIB_HOST_ENDIAN)&&(ntohs(1) == 1))) {
        pcilib_error("Big-endian byte order support is not implemented");
        return PCILIB_ERROR_NOTSUPPORTED;
    } else {
        if (b->access == sizeof(pcilib_register_value_t) * 8) {
            buf[0] = value;
        } else {
            for (i = 0, res = value; (res > 0)&&(i <= n); ++i) {
                buf[i] = res & BIT_MASK(b->access);
                res >>= b->access;
            }
            if (res) {
                pcilib_error("Value %i is too big to fit in the register %s", value, r->name);
                return PCILIB_ERROR_OUTOFRANGE;
            }
        }
    }
    err = pcilib_write_register_space_internal(ctx, bank, r->addr, n, r->offset, bits, r->rwmask, buf);
    return err;
}
References pcilib_register_bank_description_t::access, pcilib_register_description_t::addr, pcilib_register_description_t::bank, pcilib_model_description_t::banks, BIT_MASK, pcilib_register_description_t::bits, pcilib_register_bank_description_t::endianess, pcilib_register_description_t::name, pcilib_register_description_t::offset, PCILIB_BIG_ENDIAN, pcilib_error, PCILIB_ERROR_INVALID_BANK, PCILIB_ERROR_NOTSUPPORTED, PCILIB_ERROR_OUTOFRANGE, pcilib_find_register_bank_by_addr(), pcilib_get_model_description(), PCILIB_HOST_ENDIAN, PCILIB_REGISTER_BANK_INVALID, pcilib_model_description_t::registers, and pcilib_register_description_t::rwmask.
Referenced by pcilib_write_register(), and pcilib_write_register_view_by_id().
pcilib_write_register_space()
int pcilib_write_register_space (pcilib_t * ctx, const char * bank, pcilib_register_addr_t addr, size_t n, const pcilib_register_value_t * buf)
Writes one or multiple sequential registers from the specified register bank.
This function may provide access to the undefined registers in the bank. In other cases, the pcilib_write_register() / pcilib_write_register_by_id() calls are preferred.
Parameters
[in,out] ctx - pcilib context
[in] bank - the bank to write (should be specified, no autodetection)
[in] addr - the register address within the bank, addresses are counted in bytes not registers (i.e. it is offset in bytes from the start of register bank)
[in] n - number of registers to write; i.e. n * register_size bytes will be written, where register_size is defined in the bank configuration (see pcilib_register_bank_description_t)
[in] buf - the buffer of n * register_size bytes long with the data
Returns
- error code or 0 on success
{
    pcilib_register_bank_t bank_id = pcilib_find_register_bank(ctx, bank);
    if (bank_id == PCILIB_REGISTER_BANK_INVALID) {
        if (bank) pcilib_error("Invalid register bank is specified (%s)", bank);
        else pcilib_error("Register bank should be specified");
        return PCILIB_ERROR_INVALID_BANK;
    }
    return pcilib_write_register_space_internal(ctx, bank_id, addr, n, 0, 0, 0, buf);
}
References pcilib_error, PCILIB_ERROR_INVALID_BANK, pcilib_find_register_bank(), and PCILIB_REGISTER_BANK_INVALID.
pcilib_write_register_view()
int pcilib_write_register_view (pcilib_t * ctx, const char * bank, const char * regname, const char * view, const pcilib_value_t * value)
Writes the specified register using value represented in the specified view.
The views allow to convert values from standard units or self-explanatory names associated with the values (enums). Equivalent to the pcilib_write_register_view_by_id(), but first resolves register id using the specified bank and name.
Parameters
[in,out] ctx - pcilib context
[in] bank - should specify the bank name if register with the same name may occur in multiple banks, NULL otherwise
[in] regname - the name of the register
[in] view - specifies the name of the view associated with register or the used units
[in] value - the register value in the specified view (see Polymorphic values)
Returns
- error code or 0 on success
{
    pcilib_register_t reg;
    if (regname) {
        reg = pcilib_find_register(ctx, bank, regname);
        if (reg == PCILIB_REGISTER_INVALID) {
            pcilib_error("Register (%s) is not found", regname);
            return PCILIB_ERROR_NOTFOUND;
        }
    } else {
        reg = PCILIB_REGISTER_INVALID;
    }
    return pcilib_write_register_view_by_id(ctx, reg, view, val);
}
References pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_find_register(), PCILIB_REGISTER_INVALID, and pcilib_write_register_view_by_id().
Referenced by pcilib_set_property().
pcilib_write_register_view_by_id()
int pcilib_write_register_view_by_id (pcilib_t * ctx, pcilib_register_t reg, const char * view, const pcilib_value_t * value)
Writes the specified register using value represented in the specified view.
The views allow to convert values from standard units or self-explanatory names associated with the values (enums).
Parameters
[in,out] ctx - pcilib context
[in] reg - register id
[in] view - specifies the name of the view associated with register or the used units
[in] value - the register value in the specified view (see Polymorphic values)
Returns
- error code or 0 on success
{
    int err;
    pcilib_value_t val = {0};
    const char *regname;
    pcilib_view_description_t *v;
    pcilib_view_configuration_t cfg;
    pcilib_register_value_t regvalue = 0;
    if (reg == PCILIB_REGISTER_INVALID) regname = NULL;
    else regname = ctx->registers[reg].name;
    err = pcilib_detect_view_configuration(ctx, reg, view, valarg->unit, 1, &cfg);
    if (err) return err;
    v = ctx->views[cfg.view->view];
    if (!v->api->write_to_reg) {
        pcilib_error("The view (%s) does not support writting to the register", view);
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if ((v->mode & PCILIB_REGISTER_W) == 0) {
        pcilib_error("The view (%s) does not allow writting to the register", view);
        return PCILIB_ERROR_NOTPERMITED;
    }
    err = pcilib_copy_value(ctx, &val, valarg);
    if (err) return err;
    err = pcilib_convert_value_type(ctx, &val, v->type);
    if (err) {
        pcilib_error("Error (%i) converting the value of type (%s) to type (%s) used by view (%s)", pcilib_get_type_name(val.type), pcilib_get_type_name(v->type), view);
        return err;
    }
    if (cfg.trans) {
        err = pcilib_transform_unit(ctx, cfg.trans, &val);
        if (err) return err;
    }
    err = v->api->write_to_reg(ctx, cfg.view, &regvalue, &val);
    if (err) {
        if (regname)
            pcilib_error("Error (%i) computing view (%s) of register %s", err, view, regname);
        else
            pcilib_error("Error (%i) computing view %s", err, view);
        return err;
    }
    if (regname) {
        err = pcilib_write_register_by_id(ctx, cfg.reg, regvalue);
        if (err) {
            pcilib_error("Error (%i) reading register %s", err, regname);
            return err;
        }
    }
    return 0;
}
References pcilib_view_description_s::api, pcilib_view_description_s::mode, pcilib_register_description_t::name, pcilib_convert_value_type(), pcilib_copy_value(), pcilib_error, PCILIB_ERROR_NOTPERMITED, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_type_name, PCILIB_REGISTER_INVALID, PCILIB_REGISTER_W, pcilib_transform_unit(), pcilib_write_register_by_id(), pcilib_view_configuration_t::reg, pcilib_s::registers, pcilib_view_configuration_t::trans, pcilib_value_t::type, pcilib_view_description_s::type, pcilib_value_t::unit, pcilib_view_configuration_t::view, pcilib_view_context_s::view, pcilib_s::views, and pcilib_view_api_description_t::write_to_reg.
Referenced by pcilib_write_register_view().