pcilib: Public API
Public API
Base pcilib functions which does not belong to the specific APIs.
Functions
pcilib_t * pcilib_open (const char *device, const char *model)
Initializes pcilib context, detects model configuration, and populates model-specific registers.
void pcilib_close (pcilib_t *ctx)
Destroy pcilib context and all memory associated with it.
int pcilib_reset (pcilib_t *ctx)
Should reset the hardware and software in default state.
Detailed Description
Base pcilib functions which does not belong to the specific APIs.
Function Documentation
pcilib_close()
void pcilib_close (pcilib_t * ctx)
Destroy pcilib context and all memory associated with it.
The function will stop event engine if necessary, but DMA engine stay running if it was already running before pcilib_open() was called
Parameters
[in,out] ctx - pcilib context
{
    pcilib_bar_t bar;
    if (ctx) {
        pcilib_dma_engine_t dma;
        const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
        const pcilib_event_api_description_t *eapi = model_info->api;
        const pcilib_dma_api_description_t *dapi = ctx->dma.api;
        if ((eapi)&&(eapi->free)) eapi->free(ctx->event_ctx);
        if ((dapi)&&(dapi->free)) dapi->free(ctx->dma_ctx);
        for  (dma = 0; dma < PCILIB_MAX_DMA_ENGINES; dma++) {
            if (ctx->dma_rlock[dma])
                pcilib_return_lock(ctx, PCILIB_LOCK_FLAGS_DEFAULT, ctx->dma_rlock[dma]);
            if (ctx->dma_wlock[dma])
                pcilib_return_lock(ctx, PCILIB_LOCK_FLAGS_DEFAULT, ctx->dma_wlock[dma]);
        }
        pcilib_free_register_banks(ctx, 0);
        if (ctx->event_plugin)
            pcilib_plugin_close(ctx->event_plugin);
        if (ctx->locks.kmem)
            pcilib_free_locking(ctx);
        if (ctx->kmem_list) {
            pcilib_warning("Not all kernel buffers are properly cleaned");
            while (ctx->kmem_list) {
                pcilib_free_kernel_memory(ctx, ctx->kmem_list, 0);
            }
        }
        for (bar = 0; bar < PCILIB_MAX_BARS; bar++) {
            if (ctx->bar_space[bar]) {
                char *ptr = ctx->bar_space[bar];
                ctx->bar_space[bar] = NULL;
                pcilib_unmap_bar(ctx, bar, ptr);
            }
        }
        if (ctx->pci_cfg_space_fd >= 0)
            close(ctx->pci_cfg_space_fd);
        if (ctx->units) {
            pcilib_clean_units(ctx, 0);
            free(ctx->units);
        }
        if (ctx->views) {
            pcilib_clean_views(ctx, 0);
            free(ctx->views);
        }
        pcilib_clean_registers(ctx, 0);
        if (ctx->register_ctx)
            free(ctx->register_ctx);
        if (ctx->registers)
            free(ctx->registers);
        if (ctx->model)
            free(ctx->model);
        pcilib_free_xml(ctx);
        pcilib_free_py(ctx);
        if (ctx->handle >= 0)
            close(ctx->handle);
        free(ctx);
    }
}
References pcilib_dma_description_t::api, pcilib_model_description_t::api, pcilib_s::bar_space, pcilib_s::dma, pcilib_s::dma_ctx, pcilib_s::dma_rlock, pcilib_s::dma_wlock, pcilib_s::event_ctx, pcilib_s::event_plugin, pcilib_event_api_description_t::free, pcilib_dma_api_description_t::free, pcilib_s::handle, pcilib_locking_s::kmem, pcilib_s::kmem_list, pcilib_s::locks, pcilib_s::model, pcilib_s::pci_cfg_space_fd, pcilib_clean_registers(), pcilib_clean_units(), pcilib_clean_views(), pcilib_free_kernel_memory(), pcilib_free_locking(), pcilib_free_py(), pcilib_free_register_banks(), pcilib_free_xml(), pcilib_get_model_description(), PCILIB_LOCK_FLAGS_DEFAULT, PCILIB_MAX_BARS, PCILIB_MAX_DMA_ENGINES, pcilib_plugin_close(), pcilib_return_lock(), pcilib_unmap_bar(), pcilib_warning, pcilib_s::register_ctx, pcilib_s::registers, pcilib_s::units, and pcilib_s::views.
Referenced by pcilib_open().
pcilib_open()
pcilib_t * pcilib_open (const char * device, const char * model)
Initializes pcilib context, detects model configuration, and populates model-specific registers.
Event and DMA engines will not be started automatically, but calls to pcilib_start() / pcilib_start_dma() are provided for this purpose. In the end, the context should be cleaned using pcilib_stop().
Parameters
[in] device - path to the device file [/dev/fpga0]
[in] model - specifies the model of hardware, autodetected if NULL is passed
Returns
- initialized context or NULL in the case of error
{
    int err, xmlerr;
    pcilib_t *ctx = malloc(sizeof(pcilib_t));
    const pcilib_board_info_t *board_info;
    const pcilib_driver_version_t *drv_version;
    if (!model)
        model = getenv("PCILIB_MODEL");
    if (ctx) {
        memset(ctx, 0, sizeof(pcilib_t));
        ctx->pci_cfg_space_fd = -1;
        ctx->handle = open(device, O_RDWR);
        if (ctx->handle < 0) {
            pcilib_error("Error opening device (%s)", device);
            free(ctx);
            return NULL;
        }
        drv_version = pcilib_get_driver_version(ctx);
        if (!drv_version) {
            pcilib_error("Driver verification has failed (%s)", device);
            free(ctx);
            return NULL;
        }
        ctx->page_mask = pcilib_get_page_mask();
        if ((model)&&(!strcasecmp(model, "maintenance"))) {
            ctx->model = strdup("maintenance");
            return ctx;
        }
        board_info = pcilib_get_board_info(ctx);
        if (!board_info) {
            pcilib_error("Failed to enumerate PCI device");
            pcilib_close(ctx);
            return NULL;
        }
            // Check if model is specified in the XML configuration
        if (!model)
            model = pcilib_detect_xml_model(ctx, board_info->vendor_id, board_info->device_id);
        err = pcilib_init_locking(ctx);
        if (err) {
            pcilib_error("Error (%i) initializing locking subsystem", err);
            pcilib_close(ctx);
            return NULL;
        }
        err = pcilib_init_py(ctx);
        if (err) {
            pcilib_warning("Error (%i) initializing python subsystem", err);
            pcilib_free_py(ctx);
        }
        ctx->alloc_reg = PCILIB_DEFAULT_REGISTER_SPACE;
        ctx->alloc_views = PCILIB_DEFAULT_VIEW_SPACE;
        ctx->alloc_units = PCILIB_DEFAULT_UNIT_SPACE;
        ctx->registers = (pcilib_register_description_t *)malloc(PCILIB_DEFAULT_REGISTER_SPACE * sizeof(pcilib_register_description_t));
        ctx->register_ctx = (pcilib_register_context_t *)malloc(PCILIB_DEFAULT_REGISTER_SPACE * sizeof(pcilib_register_context_t));
        ctx->views = (pcilib_view_description_t**)malloc(PCILIB_DEFAULT_VIEW_SPACE * sizeof(pcilib_view_description_t*));
        ctx->units = (pcilib_unit_description_t*)malloc(PCILIB_DEFAULT_UNIT_SPACE * sizeof(pcilib_unit_description_t));
        if ((!ctx->registers)||(!ctx->register_ctx)||(!ctx->views)||(!ctx->units)) {
            pcilib_error("Error allocating memory for register model");
            pcilib_close(ctx);
            return NULL;
        }
        memset(ctx->registers, 0, sizeof(pcilib_register_description_t));
        memset(ctx->units, 0, sizeof(pcilib_unit_t));
        memset(ctx->views, 0, sizeof(pcilib_view_t*));
        memset(ctx->banks, 0, sizeof(pcilib_register_bank_description_t));
        memset(ctx->ranges, 0, sizeof(pcilib_register_range_t));
        memset(ctx->register_ctx, 0, PCILIB_DEFAULT_REGISTER_SPACE * sizeof(pcilib_register_context_t));
        pcilib_add_register_protocols(ctx, PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT, 0, pcilib_standard_register_protocols, NULL);
        pcilib_add_register_banks(ctx, PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT, 0, pcilib_standard_register_banks, NULL);
        pcilib_add_registers(ctx, PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT, 0, pcilib_standard_registers, NULL);
        err = pcilib_detect_model(ctx, model);
        if ((err)&&(err != PCILIB_ERROR_NOTFOUND)) {
            pcilib_error("Error (%i) configuring model %s (%x:%x)", err, (model?model:""), board_info->vendor_id, board_info->device_id);
            pcilib_close(ctx);
            return NULL;
        }
        if (!ctx->model)
            ctx->model = strdup(model?model:"pci");
        err = pcilib_py_add_script_dir(ctx, NULL);
        if (err) {
            pcilib_warning("Error (%i) add script path to python path", err);
            pcilib_free_py(ctx);
            err = 0;
        }
        xmlerr = pcilib_init_xml(ctx, ctx->model);
        if ((xmlerr)&&(xmlerr != PCILIB_ERROR_NOTFOUND)) {
            pcilib_error("Error (%i) initializing XML subsystem for model %s", xmlerr, ctx->model);
            pcilib_close(ctx);
            return NULL;
        }
            // We have found neither standard model nor XML
        if ((err)&&(xmlerr)) {
            pcilib_error("The specified model (%s) is not available", model);
            pcilib_close(ctx);
            return NULL;
        }
        ctx->model_info.registers = ctx->registers;
        ctx->model_info.banks = ctx->banks;
        ctx->model_info.protocols = ctx->protocols;
        ctx->model_info.ranges = ctx->ranges;
        ctx->model_info.views = (const pcilib_view_description_t**)ctx->views;
        ctx->model_info.units = ctx->units;
        err = pcilib_init_register_banks(ctx);
        if (err) {
            pcilib_error("Error (%i) initializing regiser banks\n", err);
            pcilib_close(ctx);
            return NULL;
        }
        err = pcilib_init_event_engine(ctx);
        if (err) {
            pcilib_error("Error (%i) initializing event engine\n", err);
            pcilib_close(ctx);
            return NULL;
        }
    }
    return ctx;
}
References pcilib_s::alloc_reg, pcilib_s::alloc_units, pcilib_s::alloc_views, pcilib_model_description_t::banks, pcilib_s::banks, pcilib_s::handle, pcilib_s::model, pcilib_s::model_info, pcilib_s::page_mask, pcilib_s::pci_cfg_space_fd, pcilib_add_register_banks(), pcilib_add_register_protocols(), pcilib_add_registers(), pcilib_close(), PCILIB_DEFAULT_REGISTER_SPACE, PCILIB_DEFAULT_UNIT_SPACE, PCILIB_DEFAULT_VIEW_SPACE, pcilib_detect_xml_model(), pcilib_error, PCILIB_ERROR_NOTFOUND, pcilib_free_py(), pcilib_get_board_info(), pcilib_get_driver_version(), pcilib_get_page_mask(), pcilib_init_event_engine(), pcilib_init_locking(), pcilib_init_py(), pcilib_init_register_banks(), pcilib_init_xml(), PCILIB_MODEL_MODIFICATON_FLAGS_DEFAULT, pcilib_py_add_script_dir(), pcilib_standard_register_banks, pcilib_standard_register_protocols, pcilib_standard_registers, pcilib_warning, pcilib_model_description_t::protocols, pcilib_s::protocols, pcilib_model_description_t::ranges, pcilib_s::ranges, pcilib_s::register_ctx, pcilib_model_description_t::registers, pcilib_s::registers, pcilib_model_description_t::units, pcilib_s::units, pcilib_model_description_t::views, and pcilib_s::views.
pcilib_reset()
int pcilib_reset (pcilib_t * ctx)
Should reset the hardware and software in default state.
It is implementation-specific, but is not actively used in existing implementations because the hardware is initialized from bash scripts which are often changed by Michele and his band. On the software side, it probably should reset all software registers to default value and may be additionaly re-start and clear DMA. However, this is not implemented yet.
Parameters
[in,out] ctx - pcilib context
Returns
- error code or 0 on success
{
    const pcilib_event_api_description_t *api;
    const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
    api = model_info->api;
    if (!api) {
        pcilib_error("Event API is not supported by the selected model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (api->reset)
        return api->reset(ctx->event_ctx);
    return 0;
}
References pcilib_model_description_t::api, pcilib_s::event_ctx, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_model_description(), and pcilib_event_api_description_t::reset.