pcilib: Public IRQ API
Public IRQ API
This is actually part of DMA API.
Functions
int pcilib_enable_irq (pcilib_t *ctx, pcilib_irq_type_t irq_type, pcilib_dma_flags_t flags)
int pcilib_disable_irq (pcilib_t *ctx, pcilib_dma_flags_t flags)
int pcilib_wait_irq (pcilib_t *ctx, pcilib_irq_hw_source_t source, pcilib_timeout_t timeout, size_t *count)
int pcilib_acknowledge_irq (pcilib_t *ctx, pcilib_irq_type_t irq_type, pcilib_irq_source_t irq_source)
int pcilib_clear_irq (pcilib_t *ctx, pcilib_irq_hw_source_t source)
Detailed Description
This is actually part of DMA API.
IRQ handling is currently provided by DMA engine. However, the IRQs are barely used so far. Therefore, the API can be significantly changed when confronted with harsh reallity.
Function Documentation
pcilib_acknowledge_irq()
int pcilib_acknowledge_irq (pcilib_t * ctx, pcilib_irq_type_t irq_type, pcilib_irq_source_t irq_source)
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if ((!info)||(!info->api)||(!info->api->acknowledge_irq)) return 0;
    return info->api->acknowledge_irq(ctx->dma_ctx, irq_type, irq_source);
}
References pcilib_dma_api_description_t::acknowledge_irq, pcilib_dma_description_t::api, pcilib_s::dma_ctx, and pcilib_get_dma_description().
pcilib_clear_irq()
int pcilib_clear_irq (pcilib_t * ctx, pcilib_irq_hw_source_t source)
{
    int err;
    err = ioctl(ctx->handle, PCIDRIVER_IOC_CLEAR_IOQ, source);
    if (err) {
        pcilib_error("PCIDRIVER_IOC_CLEAR_IOQ ioctl have failed");
        return PCILIB_ERROR_FAILED;
    }
    return 0;
}
References pcilib_s::handle, pcilib_error, and PCILIB_ERROR_FAILED.
pcilib_disable_irq()
int pcilib_disable_irq (pcilib_t * ctx, pcilib_dma_flags_t flags)
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if ((!info)||(!info->api)||(!info->api->disable_irq)) return 0;
    return info->api->disable_irq(ctx->dma_ctx, flags);
}
References pcilib_dma_description_t::api, pcilib_dma_api_description_t::disable_irq, pcilib_s::dma_ctx, and pcilib_get_dma_description().
pcilib_enable_irq()
int pcilib_enable_irq (pcilib_t * ctx, pcilib_irq_type_t irq_type, pcilib_dma_flags_t flags)
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if ((!info)||(!info->api)||(!info->api->enable_irq)) return 0;
    return info->api->enable_irq(ctx->dma_ctx, irq_type, flags);
}
References pcilib_dma_description_t::api, pcilib_s::dma_ctx, pcilib_dma_api_description_t::enable_irq, and pcilib_get_dma_description().
pcilib_wait_irq()
int pcilib_wait_irq (pcilib_t * ctx, pcilib_irq_hw_source_t source, pcilib_timeout_t timeout, size_t * count)
{
    int err;
    interrupt_wait_t arg = { 0 };
    arg.source = source;
    arg.timeout = timeout;
    if (count) arg.count = 1;
    err = ioctl(ctx->handle, PCIDRIVER_IOC_WAITI, &arg);
    if (err) {
        pcilib_error("PCIDRIVER_IOC_WAITI ioctl have failed");
        return PCILIB_ERROR_FAILED;
    }
    if (!arg.count) return PCILIB_ERROR_TIMEOUT;
    if (count) *count = arg.count;
    return 0;
}
References pcilib_s::handle, pcilib_error, PCILIB_ERROR_FAILED, and PCILIB_ERROR_TIMEOUT.