pcilib: Public DMA API
Public DMA API
High speed interface for reading and writting unstructured data.
Functions
pcilib_dma_engine_t pcilib_find_dma_by_addr (pcilib_t *ctx, pcilib_dma_direction_t direction, pcilib_dma_engine_addr_t dma)
This function resolves the ID of DMA engine from its address and direction.
int pcilib_start_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Starts DMA engine.
int pcilib_stop_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Stops DMA engine or just cleans up the process-specific memory buffers (see pcilib_start_dma() for details).
int pcilib_skip_dma (pcilib_t *ctx, pcilib_dma_engine_t dma)
Tries to drop all pending data in the DMA channel.
int pcilib_stream_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, pcilib_dma_callback_t cb, void *cbattr)
Reads data from DMA buffers and pass it to the specified callback function.
int pcilib_read_dma_custom (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *rdsize)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
int pcilib_read_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void *buf, size_t *rdsize)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
int pcilib_push_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *wrsize)
Pushes new data to the DMA engine.
int pcilib_write_dma (pcilib_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void *buf, size_t *wrsize)
Pushes new data to the DMA engine and blocks until hardware gets it all.
double pcilib_benchmark_dma (pcilib_t *ctx, pcilib_dma_engine_addr_t dma, uintptr_t addr, size_t size, size_t iterations, pcilib_dma_direction_t direction)
Benchmarks the DMA implementation.
Detailed Description
High speed interface for reading and writting unstructured data.
Function Documentation
pcilib_benchmark_dma()
double pcilib_benchmark_dma (pcilib_t * ctx, pcilib_dma_engine_addr_t dma, uintptr_t addr, size_t size, size_t iterations, pcilib_dma_direction_t direction)
Benchmarks the DMA implementation.
The reported performance may be significantly affected by several environmental variables.
PCILIB_BENCHMARK_HARDWARE - if set will not copy the data out, but immediately drop as it lended in DMA buffers. This allows to remove influence of memcpy performance.
PCILIB_BENCHMARK_STREAMING - if set will not re-initialized the DMA on each iteration. If DMA is properly implemented this should have only marginal influence on performance
The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
Parameters
[in,out] ctx - pcilib context
[in] dma - Address of DMA engine
[in] addr - Benchmark will read and write data at the specified address (ignored by existing DMA engines)
[in] size - specifies how many bytes should be read and written at each iteration
[in] iterations - number of iterations to execute
[in] direction - Specifies if DMA reading or writting should be benchmarked, bi-directional benchmark is possible as well
Returns
- bandwidth in MiB/s (Mebibytes per second)
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return 0;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return -1;
    }
    if (!info->api->benchmark) {
        pcilib_error("The DMA benchmark is not supported by configured DMA engine");
        return -1;
    }
    return info->api->benchmark(ctx->dma_ctx, dma, addr, size, iterations, direction);
}
References pcilib_dma_description_t::api, pcilib_dma_api_description_t::benchmark, pcilib_s::dma_ctx, pcilib_error, and pcilib_get_dma_description().
pcilib_find_dma_by_addr()
pcilib_dma_engine_t pcilib_find_dma_by_addr (pcilib_t * ctx, pcilib_dma_direction_t direction, pcilib_dma_engine_addr_t dma)
This function resolves the ID of DMA engine from its address and direction.
It is a bit confusing, but addresses should be able to represent bi-directional DMA engines. Unfortunatelly, implementation often is limited to uni-directional engines. In this case, two DMA engines with different IDs can be virtually combined in a DMA engine with the uniq address. This will allow user to specify the same engine address in all types of accesses and we will resolve the appropriate engine ID depending on the requested direction.
Parameters
[in,out] ctx - pcilib context
[in] direction - DMA direction (to/from device)
[in] dma - address of DMA engine
Returns
- ID of DMA engine or PCILIB_DMA_INVALID if the specified engine does not exist
{
    pcilib_dma_engine_t i;
    const pcilib_dma_description_t *dma_info =  pcilib_get_dma_description(ctx);
    if (!dma_info) {
        pcilib_error("DMA Engine is not configured in the current model");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    for (i = 0; dma_info->engines[i].addr_bits; i++) {
        if ((dma_info->engines[i].addr == dma)&&((dma_info->engines[i].direction&direction)==direction)) break;
    }
    if (dma_info->engines[i].addr_bits) return i;
    return PCILIB_DMA_ENGINE_INVALID;
}
References pcilib_dma_engine_description_t::addr, pcilib_dma_engine_description_t::addr_bits, pcilib_dma_engine_description_t::direction, pcilib_dma_description_t::engines, PCILIB_DMA_ENGINE_INVALID, pcilib_error, PCILIB_ERROR_NOTSUPPORTED, and pcilib_get_dma_description().
pcilib_push_dma()
int pcilib_push_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void * buf, size_t * wrsize)
Pushes new data to the DMA engine.
The actual behavior is implementation dependent. The successful exit does not mean what all data have reached hardware, but only guarantees that it is stored in DMA buffers and the hardware is instructed to start reading buffers. The function may return PCILIB_ERROR_TIMEOUT is all DMA buffers are occupied and no buffers is read by the hardware within the specified timeout. Even if an error is returned, part of the data may be already send to DMA and can't be revoked back. Number of actually written bytes is always returned in the wrsize.
The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] addr - instructs DMA to start writting at the specified address (not supported by existing DMA engines)
[in] size - specifies how many bytes should be written
[in] flags - Various flags controlling the function behavior
PCILIB_DMA_FLAG_EOP indicates that this is the last data in the DMA packet
PCILIB_DMA_FLAG_WAIT requires function to block until the data actually reach hardware. PCILIB_ERROR_TIMEOUT may be returned if it takes longer when the specified timeout.
[in] timeout - specifies number of microseconds to wait before reporting timeout, special values PCILIB_TIMEOUT_IMMEDIATE and PCILIB_TIMEOUT_INFINITE are supported.
[out] buf - the buffer with the data
[out] wrsize - number of bytes which were actually written. The correct value will be reported in both case if function has finished successfully or if error has happened.
Returns
- error code or 0 on success. In both cases some data may be written to the DMA, check wrsize.
{
    int err;
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if (!info->api->push) {
        pcilib_error("The DMA write is not supported by configured DMA engine");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
            // DS: We should check we don't exceed allocated engine range
    if (!info->engines[dma].addr_bits) {
        pcilib_error("The DMA engine (%i) is not supported by device", dma);
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if ((info->engines[dma].direction&PCILIB_DMA_TO_DEVICE) == 0) {
        pcilib_error("The selected engine (%i) is C2S-only and does not support writes", dma);
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    err = pcilib_try_lock(ctx->dma_wlock[dma]);
    if (err) {
        if (err == PCILIB_ERROR_BUSY)
            pcilib_error("DMA engine (%i) is busy", dma);
        else
            pcilib_error("Error (%i) locking DMA engine (%i)", err, dma);
        return err;
    }
    err = info->api->push(ctx->dma_ctx, dma, addr, size, flags, timeout, buf, written);
    pcilib_unlock(ctx->dma_wlock[dma]);
    return err;
}
References pcilib_dma_engine_description_t::addr_bits, pcilib_dma_description_t::api, pcilib_dma_engine_description_t::direction, pcilib_s::dma_ctx, pcilib_s::dma_wlock, pcilib_dma_description_t::engines, PCILIB_DMA_TO_DEVICE, pcilib_error, PCILIB_ERROR_BUSY, PCILIB_ERROR_NOTAVAILABLE, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_dma_description(), pcilib_try_lock(), pcilib_unlock(), and pcilib_dma_api_description_t::push.
Referenced by pcilib_write_dma().
pcilib_read_dma()
int pcilib_read_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void * buf, size_t * rdsize)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
Please, check detailed explanation when reading is stopped in the description of pcilib_read_dma_custom(). The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
The function actually executes the pcilib_read_dma_custom() without special flags and with default DMA timeout
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] addr - instructs DMA to start reading at the specified address (not supported by existing DMA engines)
[in] size - specifies how many bytes should be read
[out] buf - the buffer of size bytes long to store the data
[out] rdsize - number of bytes which were actually read. The correct value will be reported in both case if function has finished successfully or if error has happened.
Returns
- error code or 0 on success. In both cases some data may be returned in the buffer, check rdsize.
{
    int err;
    pcilib_dma_read_callback_context_t opts = {
        size, buf, 0, 0
    };
    err = pcilib_stream_dma(ctx, dma, addr, size, PCILIB_DMA_FLAGS_DEFAULT, PCILIB_DMA_TIMEOUT, pcilib_dma_read_callback, &opts);
    if (read_bytes) *read_bytes = opts.pos;
    return err;
}
References PCILIB_DMA_FLAGS_DEFAULT, PCILIB_DMA_TIMEOUT, pcilib_stream_dma(), and pcilib_dma_read_callback_context_t::pos.
pcilib_read_dma_custom()
int pcilib_read_dma_custom (pcilib_t * ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void * buf, size_t * rdsize)
Reads data from DMA until timeout is hit, a full DMA packet is read, or the specified number of bytes are read.
The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
We can't read arbitrary number of bytes from DMA. A full DMA packet is always read. The DMA packet is not equal to DMA buffer, but may consist of multiple buffers and the size may vary during run time. This may cause problems if not treated properly. While the number of actually read bytes is bellow the specified size, the function may continue to read the data. But as the new packet is started, it should fit completely in the provided buffer space or PCILIB_ERROR_TOOBIG error will be returned. Therefore, it is a good practice to read only a single packet at once and provide buffer capable to store the larges possible packet.
Unless PCILIB_DMA_FLAG_MULTIPACKET flag is specified, the function will stop after the first full packet is read. Otherwise, the reading will continue until all size bytes are read or timeout is hit. The stanard DMA timeout should be met while reading DMA buffers belonging to the same packet. Otherwise, PCILIB_ERROR_TIMEOUT is returned and number of bytes read so far is returned in the rdsize. If PCILIB_DMA_FLAG_WAIT flag is specified, the number of microseconds specified in the timeout parameter are allowed for a new packet to come. If no new data arrived in the specified timeout, the function returns successfuly and number of read bytes is returned in the rdsize.
We can't put the read data back into the DMA. Therefore, even in the case of error some data may be returned. The number of actually read bytes is always reported in rdsize and the specified amount of data is always written to the provided buffer.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] addr - instructs DMA to start reading at the specified address (not supported by existing DMA engines)
[in] size - specifies how many bytes should be read
[in] flags - Various flags controlling the function behavior
PCILIB_DMA_FLAG_MULTIPACKET indicates that multiple DMA packets will be read (not recommended, use pcilib_stream_dma() in this case)
PCILIB_DMA_FLAG_WAIT indicates that we need to wait the specified timeout between consequitive DMA packets (default DMA timeout is used otherwise)
[in] timeout - specifies number of microseconds to wait before reporting timeout, special values PCILIB_TIMEOUT_IMMEDIATE and PCILIB_TIMEOUT_INFINITE are supported. This parameter specifies timeout between consequtive DMA packets, the standard DMA timeout is expected between buffers belonging to the same DMA packet.
[out] buf - the buffer of size bytes long to store the data
[out] rdsize - number of bytes which were actually read. The correct value will be reported in both case if function has finished successfully or if error has happened.
Returns
- error code or 0 on success. In both cases some data may be returned in the buffer, check rdsize.
{
    int err;
    pcilib_dma_read_callback_context_t opts = {
        size, buf, 0, flags
    };
    err = pcilib_stream_dma(ctx, dma, addr, size, flags, timeout, pcilib_dma_read_callback, &opts);
    if (read_bytes) *read_bytes = opts.pos;
    return err;
}
References pcilib_stream_dma(), and pcilib_dma_read_callback_context_t::pos.
pcilib_skip_dma()
int pcilib_skip_dma (pcilib_t * ctx, pcilib_dma_engine_t dma)
Tries to drop all pending data in the DMA channel.
It will drop not only data currently in the DMA buffers, but will allow hardware to write more and will drop the newly written data as well. The standard DMA timeout is allowed to receive new data. If hardware continuously writes data, after PCILIB_DMA_SKIP_TIMEOUT microseconds the function will exit with PCILIB_ERROR_TIMEOUT error.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
Returns
- error code or 0 on success
{
    int err;
    struct timeval tv, cur;
    gettimeofday(&tv, NULL);
    tv.tv_usec += PCILIB_DMA_SKIP_TIMEOUT;
    tv.tv_sec += tv.tv_usec / 1000000;
    tv.tv_usec += tv.tv_usec % 1000000;
    do {
            // IMMEDIATE timeout is not working properly, so default is set
        err = pcilib_stream_dma(ctx, dma, 0, 0, PCILIB_DMA_FLAGS_DEFAULT, PCILIB_DMA_TIMEOUT, pcilib_dma_skip_callback, &tv);
        gettimeofday(&cur, NULL);
    } while ((!err)&&((cur.tv_sec < tv.tv_sec)||((cur.tv_sec == tv.tv_sec)&&(cur.tv_usec < tv.tv_usec))));
    if ((cur.tv_sec > tv.tv_sec)||((cur.tv_sec == tv.tv_sec)&&(cur.tv_usec > tv.tv_usec))) return PCILIB_ERROR_TIMEOUT;
    return 0;
}
References PCILIB_DMA_FLAGS_DEFAULT, PCILIB_DMA_SKIP_TIMEOUT, PCILIB_DMA_TIMEOUT, PCILIB_ERROR_TIMEOUT, and pcilib_stream_dma().
pcilib_start_dma()
int pcilib_start_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Starts DMA engine.
This call will allocate DMA buffers and pass their bus addresses to the hardware.
During the call, the C2S engine may start writting data. The written buffers are marked as ready and can be read-out using pcilib_stream_dma() and pcilib_read_dma() calls. If no empty buffers left, the C2S DMA engine will stall until some buffers are read out.
The S2C engine waits until the data is pushed with pcilib_push_data() call
After pcilib_start_dma() call, the pcilib_stop_dma() function should be necessarily called. However, it will clean up the process memory, but only in some cases actually stop the DMA engine. This depends on flags passed to both pcilib_start_dma() and pcilib_stop_dma() calls. if PCILIB_DMA_FLAG_PERSISTENT flag is passed to the pcilib_start_dma(), the DMA engine will remain running unless the same flag is also passed to the pcilib_stop_dma() call. The allocated DMA buffers will stay intact and the hardware may continue reading / writting data while there is space/data left. However, the other functions of DMA API should not be called after pcilib_stop_dma() until new pcilib_start_dma() call is issued.
The process- and thread-safety is implementation depedent. However, currently the process- safety is ensured while accessing the kernel memory (todo: this may get complicated if we provide a way to perform DMA directly to the user-supplied pages). The thread-safety is not provided by currently implemented DMA engines. The DMA functions may be called from multiple threads, but it is user responsibility to ensure that only a single DMA-related call is running. On other hand, the DMA and register APIs may be used in parallel.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] flags - PCILIB_DMA_FLAG_PERSISTENT indicates that engine should be kept running after pcilib_stop_dma() call
Returns
- error code or 0 on success
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if (!info->api->start_dma) {
        return 0;
    }
    return info->api->start_dma(ctx->dma_ctx, dma, flags);
}
References pcilib_dma_description_t::api, pcilib_s::dma_ctx, pcilib_error, PCILIB_ERROR_NOTAVAILABLE, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_dma_description(), and pcilib_dma_api_description_t::start_dma.
pcilib_stop_dma()
int pcilib_stop_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Stops DMA engine or just cleans up the process-specific memory buffers (see pcilib_start_dma() for details).
No DMA API calls allowed after this point until pcilib_start_dma() is called anew.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] flags - PCILIB_DMA_FLAG_PERSISTENT indicates that engine should be actually stopped independent of the flags passed to pcilib_start_dma() call
Returns
- error code or 0 on success
{
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if (!info->api->stop_dma) {
        return 0;
    }
    return info->api->stop_dma(ctx->dma_ctx, dma, flags);
}
References pcilib_dma_description_t::api, pcilib_s::dma_ctx, pcilib_error, PCILIB_ERROR_NOTAVAILABLE, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_dma_description(), and pcilib_dma_api_description_t::stop_dma.
pcilib_stream_dma()
int pcilib_stream_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, pcilib_dma_callback_t cb, void * cbattr)
Reads data from DMA buffers and pass it to the specified callback function.
The return code of the callback function determines if streaming should continue and how much to wait for next data to arrive before triggering timeout. The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
The function waits the specified timeout microseconds for the first data. Afterwards, the waiting time for next portion of data depends on the last return code (ret) from callback function. If ret & PCILIB_STREAMING_TIMEOUT_MASK is
PCILIB_STREAMING_STOP - the streaming stops
PCILIB_STREAMING_CONTINUE - the standard DMA timeout will be used to wait for a new data
PCILIB_STREAMING_WAIT - the timeout specified in the function arguments will be used to wait for a new data
PCILIB_STREAMING_CHECK - the function will return if new data is not available immediately The function return code depends on the return code from the callback as well. If no data received within the specified timeout and no callback is called, the PCILIB_ERROR_TIMEOUT is returned. Otherwise, success is returned unless PCILIB_STREAMING_FAIL flag has been set in the callback return code before the timeout was triggered.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] addr - instructs DMA to start reading at the specified address (not supported by existing DMA engines)
[in] size - instructs DMA to read only size bytes (not supported by existing DMA engines)
[in] flags - not used by existing DMA engines
[in] timeout - specifies number of microseconds to wait before reporting timeout, special values PCILIB_TIMEOUT_IMMEDIATE and PCILIB_TIMEOUT_INFINITE are supported.
[in] cb - callback function to call
[in,out] cbattr - passed through as the first parameter of callback function
Returns
- error code or 0 on success
{
    int err;
    const pcilib_dma_description_t *info =  pcilib_get_dma_description(ctx);
    if (!info) {
        pcilib_error("DMA is not supported by the device");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    if (!info->api) {
        pcilib_error("DMA Engine is not configured in the current model");
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if (!info->api->stream) {
        pcilib_error("The DMA read is not supported by configured DMA engine");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
        // DS: We should check we are not going outside of allocated engine space
    if (!info->engines[dma].addr_bits) {
        pcilib_error("The DMA engine (%i) is not supported by device", dma);
        return PCILIB_ERROR_NOTAVAILABLE;
    }
    if ((info->engines[dma].direction&PCILIB_DMA_FROM_DEVICE) == 0) {
        pcilib_error("The selected engine (%i) is S2C-only and does not support reading", dma);
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    err = pcilib_try_lock(ctx->dma_rlock[dma]);
    if (err) {
        if ((err == PCILIB_ERROR_BUSY)||(err == PCILIB_ERROR_TIMEOUT))
            pcilib_error("DMA engine (%i) is busy", dma);
        else
            pcilib_error("Error (%i) locking DMA engine (%i)", err, dma);
        return err;
    }
    err = info->api->stream(ctx->dma_ctx, dma, addr, size, flags, timeout, cb, cbattr);
    pcilib_unlock(ctx->dma_rlock[dma]);
    return err;
}
References pcilib_dma_engine_description_t::addr_bits, pcilib_dma_description_t::api, pcilib_dma_engine_description_t::direction, pcilib_s::dma_ctx, pcilib_s::dma_rlock, pcilib_dma_description_t::engines, PCILIB_DMA_FROM_DEVICE, pcilib_error, PCILIB_ERROR_BUSY, PCILIB_ERROR_NOTAVAILABLE, PCILIB_ERROR_NOTSUPPORTED, PCILIB_ERROR_TIMEOUT, pcilib_get_dma_description(), pcilib_try_lock(), pcilib_unlock(), and pcilib_dma_api_description_t::stream.
Referenced by pcilib_read_dma(), pcilib_read_dma_custom(), and pcilib_skip_dma().
pcilib_write_dma()
int pcilib_write_dma (pcilib_t * ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, void * buf, size_t * wrsize)
Pushes new data to the DMA engine and blocks until hardware gets it all.
Even if an error has occured, a part of the data may be already had send to DMA and can't be revoked back. Number of actually written bytes is always returned in the wrsize.
The function is process- and thread-safe. The PCILIB_ERROR_BUSY will be returned immediately if DMA is used by another thread or process.
The function actually executes the pcilib_push_dma() with PCILIB_DMA_FLAG_EOP and PCILIB_DMA_FLAG_WAIT flags set and the default DMA timeout.
Parameters
[in,out] ctx - pcilib context
[in] dma - ID of DMA engine, the ID should first be resolved using pcilib_find_dma_by_addr()
[in] addr - instructs DMA to start writting at the specified address (not supported by existing DMA engines)
[in] size - specifies how many bytes should be written
[out] buf - the buffer with the data
[out] wrsize - number of bytes which were actually written. The correct value will be reported in both case if function has finished successfully or if error has happened.
Returns
- error code or 0 on success. In both cases some data may be written to the DMA, check wrsize.
{
    return pcilib_push_dma(ctx, dma, addr, size, PCILIB_DMA_FLAG_EOP|PCILIB_DMA_FLAG_WAIT, PCILIB_DMA_TIMEOUT, buf, written_bytes);
}
References PCILIB_DMA_FLAG_EOP, PCILIB_DMA_FLAG_WAIT, PCILIB_DMA_TIMEOUT, and pcilib_push_dma().