pcilib: kmem.h File Reference
kmem.h File Reference
Data Structures
struct pcilib_kmem_addr_t
struct pcilib_kmem_buffer_t
single allocation - we set only addr, n_blocks = 0 multiple allocation - addr is not set, blocks are set, n_blocks > 0 sgmap allocation - addr contains ua, but pa's are set in blocks, n_blocks > 0
struct pcilib_kmem_list_s
Macros
#define PCILIB_KMEM_PAGE_SIZE 0x1000
Default pages size is 4096 bytes.
#define PCILIB_KMEM_TYPE_MASK 0xFFFF0000
Mask selecting the general type in pcilib_kmem_type_t.
#define PCILIB_KMEM_USE_TYPE(use) (use >> 16)
Returns general use of the kernel buffers, for instance DMA buffer (see pcilib_kmem_use_t)
#define PCILIB_KMEM_USE_SUBTYPE(use) (use & 0xFFFF)
Additional information about the use of the kernel buffers.
#define PCILIB_KMEM_USE(type, subtype) ((pcilib_kmem_use_t)(((type) << 16)|(subtype)))
Constructs full use from use type and use subtype.
Typedefs
typedef struct pcilib_s pcilib_t
typedef struct pcilib_kmem_list_s pcilib_kmem_list_t
typedef void pcilib_kmem_handle_t
Enumerations
enum pcilib_tristate_t { PCILIB_TRISTATE_NO = 0 , PCILIB_TRISTATE_PARTIAL = 1 , PCILIB_TRISTATE_YES = 2 }
enum pcilib_kmem_type_t {
PCILIB_KMEM_TYPE_CONSISTENT = 0x00000 , PCILIB_KMEM_TYPE_PAGE = 0x10000 , PCILIB_KMEM_TYPE_DMA_S2C_PAGE = 0x10001 , PCILIB_KMEM_TYPE_DMA_C2S_PAGE = 0x10002 ,
PCILIB_KMEM_TYPE_REGION = 0x20000 , PCILIB_KMEM_TYPE_REGION_S2C = 0x20001 , PCILIB_KMEM_TYPE_REGION_C2S = 0x20002
}
enum pcilib_kmem_use_t {
PCILIB_KMEM_USE_STANDARD = 0 , PCILIB_KMEM_USE_DMA_RING = 1 , PCILIB_KMEM_USE_DMA_PAGES = 2 , PCILIB_KMEM_USE_SOFTWARE_REGISTERS = 3 ,
PCILIB_KMEM_USE_LOCKS = 4 , PCILIB_KMEM_USE_USER = 0x10
}
enum pcilib_kmem_sync_direction_t { PCILIB_KMEM_SYNC_BIDIRECTIONAL = 0 , PCILIB_KMEM_SYNC_TODEVICE = 1 , PCILIB_KMEM_SYNC_FROMDEVICE = 2 }
enum pcilib_kmem_flags_t {
PCILIB_KMEM_FLAG_REUSE = 1 , PCILIB_KMEM_FLAG_EXCLUSIVE = 2 , PCILIB_KMEM_FLAG_PERSISTENT = 4 , PCILIB_KMEM_FLAG_HARDWARE = 8 ,
PCILIB_KMEM_FLAG_FORCE = 16 , PCILIB_KMEM_FLAG_MASS = 32 , PCILIB_KMEM_FLAG_TRY = 64
}
enum pcilib_kmem_reuse_state_t {
PCILIB_KMEM_REUSE_ALLOCATED = PCILIB_TRISTATE_NO , PCILIB_KMEM_REUSE_REUSED = PCILIB_TRISTATE_YES , PCILIB_KMEM_REUSE_PARTIAL = PCILIB_TRISTATE_PARTIAL , PCILIB_KMEM_REUSE_PERSISTENT = 0x100 ,
PCILIB_KMEM_REUSE_HARDWARE = 0x200
}
Functions
pcilib_kmem_handle_t * pcilib_alloc_kernel_memory (pcilib_t *ctx, pcilib_kmem_type_t type, size_t nmemb, size_t size, size_t alignment, pcilib_kmem_use_t use, pcilib_kmem_flags_t flags)
This function either allocates new buffers in the kernel space or just re-uses existing buffers.
void pcilib_free_kernel_memory (pcilib_t *ctx, pcilib_kmem_handle_t *k, pcilib_kmem_flags_t flags)
This function either frees the allocated kernel memory or just releases some of the references.
int pcilib_clean_kernel_memory (pcilib_t *ctx, pcilib_kmem_use_t use, pcilib_kmem_flags_t flags)
Free / dereference all kernel memory buffers associated with the specified use.
int pcilib_kmem_sync_block (pcilib_t *ctx, pcilib_kmem_handle_t *k, pcilib_kmem_sync_direction_t dir, size_t block)
Synchronizes usage of the specified buffer between hardware and the system.
volatile void * pcilib_kmem_get_ua (pcilib_t *ctx, pcilib_kmem_handle_t *k)
Get a valid pointer on the user-space mapping of a single-buffer kernel memory.
uintptr_t pcilib_kmem_get_pa (pcilib_t *ctx, pcilib_kmem_handle_t *k)
Get a physical address of a single-buffer kernel memory.
uintptr_t pcilib_kmem_get_ba (pcilib_t *ctx, pcilib_kmem_handle_t *k)
Get a bus address of a single-buffer kernel memory.
volatile void * pcilib_kmem_get_block_ua (pcilib_t *ctx, pcilib_kmem_handle_t *k, size_t block)
Get a valid pointer on the user-space mapping of the specified kernel memory buffer.
uintptr_t pcilib_kmem_get_block_pa (pcilib_t *ctx, pcilib_kmem_handle_t *k, size_t block)
Get a physical address of the specified kernel memory buffer.
uintptr_t pcilib_kmem_get_block_ba (pcilib_t *ctx, pcilib_kmem_handle_t *k, size_t block)
Get a bus address of the specified kernel memory buffer.
size_t pcilib_kmem_get_block_size (pcilib_t *ctx, pcilib_kmem_handle_t *k, size_t block)
Get size of the specified kernel memory buffer.
pcilib_kmem_reuse_state_t pcilib_kmem_is_reused (pcilib_t *ctx, pcilib_kmem_handle_t *k)
Reports if the kernel memory was reused fully, partially, or allocated completely anew.
Macro Definition Documentation
PCILIB_KMEM_PAGE_SIZE
#define PCILIB_KMEM_PAGE_SIZE 0x1000
Default pages size is 4096 bytes.
PCILIB_KMEM_TYPE_MASK
#define PCILIB_KMEM_TYPE_MASK 0xFFFF0000
Mask selecting the general type in pcilib_kmem_type_t.
The subtype is may specify DMA mapping and other minor details of allocation
PCILIB_KMEM_USE
#define PCILIB_KMEM_USE (type, subtype) ((pcilib_kmem_use_t)(((type) << 16)|(subtype)))
Constructs full use from use type and use subtype.
PCILIB_KMEM_USE_SUBTYPE
#define PCILIB_KMEM_USE_SUBTYPE (use) (use & 0xFFFF)
Additional information about the use of the kernel buffers.
The actual meaning depends on general use, for instance in case of DMA buffers the subtype specifies DMA engine
PCILIB_KMEM_USE_TYPE
#define PCILIB_KMEM_USE_TYPE (use) (use >> 16)
Returns general use of the kernel buffers, for instance DMA buffer (see pcilib_kmem_use_t)
Typedef Documentation
pcilib_kmem_handle_t
typedef void pcilib_kmem_handle_t
pcilib_kmem_list_t
typedef struct pcilib_kmem_list_s pcilib_kmem_list_t
pcilib_t
typedef struct pcilib_s pcilib_t
Enumeration Type Documentation
pcilib_kmem_flags_t
enum pcilib_kmem_flags_t
Enumerator
PCILIB_KMEM_FLAG_REUSE
Try to reuse existing buffer with the same use & item.
PCILIB_KMEM_FLAG_EXCLUSIVE
Allow only a single application accessing a specified use & item.
PCILIB_KMEM_FLAG_PERSISTENT
Sets persistent mode.
PCILIB_KMEM_FLAG_HARDWARE
The buffer may be accessed by hardware, the hardware access will not occur any more if passed to _free function.
PCILIB_KMEM_FLAG_FORCE
Force memory cleanup even if references are present.
PCILIB_KMEM_FLAG_MASS
Apply to all buffers of selected use.
PCILIB_KMEM_FLAG_TRY
Do not allocate buffers, try to reuse and fail if not possible.
             {
    PCILIB_KMEM_FLAG_REUSE = 1,
    PCILIB_KMEM_FLAG_EXCLUSIVE = 2,
    PCILIB_KMEM_FLAG_PERSISTENT = 4,
    PCILIB_KMEM_FLAG_HARDWARE = 8,
    PCILIB_KMEM_FLAG_FORCE = 16,
    PCILIB_KMEM_FLAG_MASS = 32,
    PCILIB_KMEM_FLAG_TRY =  64
} pcilib_kmem_flags_t;
pcilib_kmem_reuse_state_t
enum pcilib_kmem_reuse_state_t
Enumerator
PCILIB_KMEM_REUSE_ALLOCATED
The kernel memory was allocated anew.
PCILIB_KMEM_REUSE_REUSED
Already allocated kernel memory was re-used.
PCILIB_KMEM_REUSE_PARTIAL
The kernel memory was partially re-used and partially allocated.
PCILIB_KMEM_REUSE_PERSISTENT
Flag indicating that persistent kmem was allocated/reused (will not be cleaned on pcilib_free_kernel_memory() unless forced with PCILIB_KMEM_FLAG_PERSISTENT.
PCILIB_KMEM_REUSE_HARDWARE
Flag indicating that kmem may be used by hardware device.
             {
    PCILIB_KMEM_REUSE_ALLOCATED = PCILIB_TRISTATE_NO,
    PCILIB_KMEM_REUSE_REUSED = PCILIB_TRISTATE_YES,
    PCILIB_KMEM_REUSE_PARTIAL = PCILIB_TRISTATE_PARTIAL,
    PCILIB_KMEM_REUSE_PERSISTENT = 0x100,
    PCILIB_KMEM_REUSE_HARDWARE = 0x200
} pcilib_kmem_reuse_state_t;
pcilib_kmem_sync_direction_t
enum pcilib_kmem_sync_direction_t
Enumerator
PCILIB_KMEM_SYNC_BIDIRECTIONAL
Two-way synchronization (should not be used)
PCILIB_KMEM_SYNC_TODEVICE
Allow device to read the data in the DMA-able buffer.
PCILIB_KMEM_SYNC_FROMDEVICE
Allow application to read the data written by device in the DMA-able buffer.
             {
    PCILIB_KMEM_SYNC_BIDIRECTIONAL = 0,
    PCILIB_KMEM_SYNC_TODEVICE = 1,
    PCILIB_KMEM_SYNC_FROMDEVICE = 2
} pcilib_kmem_sync_direction_t;
pcilib_kmem_type_t
enum pcilib_kmem_type_t
Enumerator
PCILIB_KMEM_TYPE_CONSISTENT
Consistent memory can be simultaneously accessed by the device and applications and is normally used for DMA descriptors.
PCILIB_KMEM_TYPE_PAGE
A number of physically consequitive pages of memory.
PCILIB_KMEM_TYPE_DMA_S2C_PAGE
Memory pages mapped for S2C DMA operation (device reads)
PCILIB_KMEM_TYPE_DMA_C2S_PAGE
Memory pages mapped for C2S DMA operation (device writes)
PCILIB_KMEM_TYPE_REGION
Just map buffers to the contiguous user-supplied memory region (normally reserved during the boot with option memmap=512M$2G)
PCILIB_KMEM_TYPE_REGION_S2C
Memory region mapped for S2C DMA operation (device reads)
PCILIB_KMEM_TYPE_REGION_C2S
Memory region mapped for C2S DMA operation (device writes.
             {
    PCILIB_KMEM_TYPE_CONSISTENT = 0x00000,
    PCILIB_KMEM_TYPE_PAGE = 0x10000,
    PCILIB_KMEM_TYPE_DMA_S2C_PAGE = 0x10001,
    PCILIB_KMEM_TYPE_DMA_C2S_PAGE = 0x10002,
    PCILIB_KMEM_TYPE_REGION = 0x20000,
    PCILIB_KMEM_TYPE_REGION_S2C = 0x20001,
    PCILIB_KMEM_TYPE_REGION_C2S = 0x20002
} pcilib_kmem_type_t;
pcilib_kmem_use_t
enum pcilib_kmem_use_t
Enumerator
PCILIB_KMEM_USE_STANDARD
Undefined use, buffers of standard use are not grouped together and can be used individually.
PCILIB_KMEM_USE_DMA_RING
The kmem used for DMA descriptor, the sub type specifies the id of considered DMA engine.
PCILIB_KMEM_USE_DMA_PAGES
The kmem used for DMA buffers, the sub type specifies the address of considered DMA engine (can be engine specific)
PCILIB_KMEM_USE_SOFTWARE_REGISTERS
The kmem used to store software registers, the sub type holds the bank address.
PCILIB_KMEM_USE_LOCKS
The kmem used to hold locks, the sub type is not used.
PCILIB_KMEM_USE_USER
Further uses can be defined by event engines.
             {
    PCILIB_KMEM_USE_STANDARD = 0,
    PCILIB_KMEM_USE_DMA_RING = 1,
    PCILIB_KMEM_USE_DMA_PAGES = 2,
    PCILIB_KMEM_USE_SOFTWARE_REGISTERS = 3,
    PCILIB_KMEM_USE_LOCKS = 4,
    PCILIB_KMEM_USE_USER = 0x10
} pcilib_kmem_use_t;
pcilib_tristate_t
enum pcilib_tristate_t
Enumerator
PCILIB_TRISTATE_NO
All values are evaluated as false.
PCILIB_TRISTATE_PARTIAL
Some values are evaluated as false and others as true.
PCILIB_TRISTATE_YES
All values are evaluated as true.
             {
    PCILIB_TRISTATE_NO = 0,
    PCILIB_TRISTATE_PARTIAL = 1,
    PCILIB_TRISTATE_YES = 2
} pcilib_tristate_t;
Function Documentation
pcilib_alloc_kernel_memory()
pcilib_kmem_handle_t * pcilib_alloc_kernel_memory (pcilib_t * ctx, pcilib_kmem_type_t type, size_t nmemb, size_t size, size_t alignment, pcilib_kmem_use_t use, pcilib_kmem_flags_t flags)
This function either allocates new buffers in the kernel space or just re-uses existing buffers.
Sometimes kernel memory is allocated for the specific use-case, for example to provide buffers for DMA engine. It is possible to specify intended use using use parameter. The kernel memory with the specified use (i.e. use != 0) can be declared persistent (flags include PCILIB_KMEM_FLAG_PERSISTENT). Such memory will not be de-allocated on clean-up and will be maintained by the kernel module across the runs of various pcilib applications. To re-use persistent kernel memory, PCILIB_KMEM_FLAG_REUSE should be set. In this case, the pcilib will either allocate new kernel memory or re-use the already allocated kernel buffers with the specified use. If PCILIB_KMEM_FLAG_REUSE is not set, but the kernel memory with the specified use is already allocated, an error will be returned.
It is also possible to allocate persistent kernel memory which can be execlusively used by a single process. The PCILIB_KMEM_FLAG_EXCLUSIVE flag have to be provided to pcilib_alloc_kernel_memory() function in this case. Only a single process may call hold a reference to kernel memory. Before next process would be able to obtain it, the process holding the reference should return it using pcilib_free_kernel_memory() call. For example, DMA engine uses exclusive kernel memory to guarantee that exactly one process is controlling DMA operations.
To clean up allocated persistent kernel memory, pcilib_free_kernel_memory() have to be called with PCILIB_KMEM_FLAG_PERSISTENT flag set.
Parameters
[in,out] ctx - pcilib context
[in] type - specifies type of allocation (simple pages, DMA pages, consistent memory, etc.)
[in] nmemb - specifies number of buffers to allocated
[in] size - specifies the size of each buffer in bytes
[in] alignment - specifies required alignment, the bus addresses are aligned for PCI-mapped buffers and physical addresses are aligned for the rest (if bounce buffers are used, the physical and bus addresses are not always have the same alignment)
[in] use - specifies how the memory will be used (to store software registers, locks, DMA buffers, etc.)
[in] flags - various flags defining how buffers should be re-used/allocated and, that, should happen on pcilib_free_kernel_memory()
Returns
- pointer on context with allocated kernel memory or NULL in case of error
{
    int err = 0;
    char error[256];
    int ret;
    size_t i, allocated = nmemb;
    void *addr;
    pcilib_tristate_t reused = PCILIB_TRISTATE_NO;
    int persistent = -1;
    int hardware = -1;
    kmem_handle_t kh = {0};
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)malloc(sizeof(pcilib_kmem_list_t) + nmemb * sizeof(pcilib_kmem_addr_t));
    if (!kbuf) {
        pcilib_error("Memory allocation has failed");
        return NULL;
    }
    memset(kbuf, 0, sizeof(pcilib_kmem_list_t) + nmemb * sizeof(pcilib_kmem_addr_t));
    err = pcilib_lock_global(ctx);
    if (err) {
        pcilib_error("Error (%i) acquiring mmap lock", err);
        return NULL;
    }
    ret = ioctl( ctx->handle, PCIDRIVER_IOC_MMAP_MODE, PCIDRIVER_MMAP_KMEM );
    if (ret) {
        pcilib_unlock_global(ctx);
        pcilib_error("PCIDRIVER_IOC_MMAP_MODE ioctl have failed");
        return NULL;
    }
    kh.type = type;
    kh.size = size;
    kh.align = alignment;
    kh.use = use;
    if ((type&PCILIB_KMEM_TYPE_MASK) == PCILIB_KMEM_TYPE_REGION) {
        kh.align = 0;
    } else if ((type&PCILIB_KMEM_TYPE_MASK) != PCILIB_KMEM_TYPE_PAGE) {
        kh.size += alignment;
    }
    for ( i = 0; (i < nmemb)||(flags&PCILIB_KMEM_FLAG_MASS); i++) {
        kh.item = i;
        kh.flags = flags;
        if (i >= nmemb)
            kh.flags |= KMEM_FLAG_TRY;
        if ((type&PCILIB_KMEM_TYPE_MASK) == PCILIB_KMEM_TYPE_REGION) {
            kh.pa = alignment + i * size;
        }
        ret = ioctl(ctx->handle, PCIDRIVER_IOC_KMEM_ALLOC, &kh);
        if (ret) {
            kbuf->buf.n_blocks = i;
            if ((i < nmemb)||(errno != ENOENT)) {
                err = PCILIB_ERROR_FAILED;
                if (errno == EINVAL) {
                    if (kh.type != type)
                        sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  we have requested type %u but buffer is of type %lu", use, i, type, kh.type);
                    else if (kh.size != size)
                        sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  we have requested size %lu but buffer is of size %lu", use, i, size, kh.size);
                    else if (kh.align != alignment)
                        sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  we have requested alignment %lu but buffer is of alignment %lu", use, i, size, kh.size);
                    else if ((kh.flags&KMEM_FLAG_EXCLUSIVE) != (flags&KMEM_FLAG_EXCLUSIVE))
                        sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  we have requested size %s but buffer is of size %s", use, i, ((flags&KMEM_FLAG_EXCLUSIVE)?"exclusive":"non-exclusive"), ((kh.flags&KMEM_FLAG_EXCLUSIVE)?"exclusive":"non exclusive"));
                    else
                        sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  unknown consistency error", use, i);
                } else if (errno == EBUSY) {
                    sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  reuse counter of kmem_entry is overflown", use, i);
                } else if (errno == ENOMEM) {
                    sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  memory allocation (%zu bytes) failed", use, i, size);
                } else {
                    sprintf(error, "Driver prevents us from re-using buffer (use 0x%x, block: %zu),  PCIDRIVER_IOC_KMEM_ALLOC ioctl have failed with errno %i", use, i, errno);
                }
            }
            break;
        }
        if (i >= allocated) {
            void *kbuf_new = realloc(kbuf, sizeof(pcilib_kmem_list_t) + 2 * allocated * sizeof(pcilib_kmem_addr_t));
            if (!kbuf_new) {
                kbuf->buf.n_blocks = i;
                err = PCILIB_ERROR_MEMORY;
                sprintf(error, "Failed to allocate extra %zu bytes of user-space memory for kmem structures", allocated * sizeof(pcilib_kmem_addr_t));
                break;
            }
            memset(kbuf_new + sizeof(pcilib_kmem_list_t) + allocated * sizeof(pcilib_kmem_addr_t) , 0, allocated * sizeof(pcilib_kmem_addr_t));
            kbuf = kbuf_new;
            allocated *= 2;
        }
        kbuf->buf.blocks[i].handle_id = kh.handle_id;
        kbuf->buf.blocks[i].pa = kh.pa;
        kbuf->buf.blocks[i].ba = kh.ba;
        kbuf->buf.blocks[i].size = kh.size;
        if (!i) reused = (kh.flags&KMEM_FLAG_REUSED)?PCILIB_TRISTATE_YES:PCILIB_TRISTATE_NO;
        if (kh.flags&KMEM_FLAG_REUSED) {
            if (!i) reused = PCILIB_TRISTATE_YES;
            else if (!reused) reused = PCILIB_TRISTATE_PARTIAL;
            if (persistent) {
                if (persistent < 0) {
                    /*if (((flags&PCILIB_KMEM_FLAG_PERSISTENT) == 0)&&(kh.flags&KMEM_FLAG_REUSED_PERSISTENT)) err = PCILIB_ERROR_INVALID_STATE;
                    else*/ persistent = (kh.flags&KMEM_FLAG_REUSED_PERSISTENT)?1:0;
                } else if ((kh.flags&KMEM_FLAG_REUSED_PERSISTENT) == 0) err = PCILIB_ERROR_INVALID_STATE;
            } else if (kh.flags&KMEM_FLAG_REUSED_PERSISTENT) err = PCILIB_ERROR_INVALID_STATE;
            if (err) {
                kbuf->buf.n_blocks = i + 1;
                sprintf(error,  "Mistmatch in persistent modes of the re-used kmem blocks. Current buffer (use 0x%x, block: %zu) is %s, but prior ones %s",
                    use, i, ((kh.flags&KMEM_FLAG_REUSED_PERSISTENT)?"persistent":"not persistent"), (persistent?"are":"are not"));
                break;
            }
            if (hardware) {
                if (hardware < 0) {
                    /*if (((flags&PCILIB_KMEM_FLAG_HARDWARE) == 0)&&(kh.flags&KMEM_FLAG_REUSED_HW)) err = PCILIB_ERROR_INVALID_STATE;
                    else*/ hardware = (kh.flags&KMEM_FLAG_REUSED_HW)?1:0;
                } else if ((kh.flags&KMEM_FLAG_REUSED_HW) == 0) err = PCILIB_ERROR_INVALID_STATE;
            } else if (kh.flags&KMEM_FLAG_REUSED_HW) err = PCILIB_ERROR_INVALID_STATE;
            if (err) {
                kbuf->buf.n_blocks = i + 1;
                sprintf(error,  "Mistmatch in hardware modes of the re-used kmem blocks. Current buffer (use 0x%x, block: %zu) is %s, but prior ones %s",
                    use, i, ((kh.flags&KMEM_FLAG_REUSED_HW)?"hardware-locked":"not hardware-locked"), (hardware?"are":"are not"));
                break;
            }
        } else {
            if (!i) reused = PCILIB_TRISTATE_NO;
            else if (reused) reused = PCILIB_TRISTATE_PARTIAL;
            if ((persistent > 0)&&((flags&PCILIB_KMEM_FLAG_PERSISTENT) == 0)) {
                err = PCILIB_ERROR_INVALID_STATE;
                sprintf(error, "Expecting to re-use persistent blocks, but buffer (use 0x%x, block: %zu) is not", use, i);
            }
            else if ((hardware > 0)&&((flags&PCILIB_KMEM_FLAG_HARDWARE) == 0)) {
                err = PCILIB_ERROR_INVALID_STATE;
                sprintf(error, "Expecting to re-use hardware-locked blocks, but buffer (use 0x%x, block: %zu) is not", use, i);
            }
            if (err) {
                kbuf->buf.n_blocks = i + 1;
                break;
            }
        }
        if ((kh.align)&&((kh.type&PCILIB_KMEM_TYPE_MASK) != PCILIB_KMEM_TYPE_PAGE)) {
                //  Physical or bus address here?
            if (kh.ba) {
                if (kh.ba % kh.align) kbuf->buf.blocks[i].alignment_offset = kh.align - kh.ba % kh.align;
            } else {
                if (kh.pa % kh.align) kbuf->buf.blocks[i].alignment_offset = kh.align - kh.pa % kh.align;
            }
            kbuf->buf.blocks[i].size -= kh.align;
        }
        addr = mmap( 0, kbuf->buf.blocks[i].size + kbuf->buf.blocks[i].alignment_offset, PROT_WRITE | PROT_READ, MAP_SHARED, ctx->handle, 0 );
        if ((!addr)||(addr == MAP_FAILED)) {
            kbuf->buf.n_blocks = i + 1;
            err = PCILIB_ERROR_FAILED;
            sprintf(error, "Driver prevents us from mmaping buffer (use 0x%x, block: %zu), mmap have failed with errno %i", use, i, errno);
            break;
        }
        kbuf->buf.blocks[i].ua = addr;
        kbuf->buf.blocks[i].mmap_offset = kh.pa & ctx->page_mask;
    }
    if (err) kbuf->buf.n_blocks = i + 1;
    else kbuf->buf.n_blocks = i;
        // Check if there are more unpicked buffers
    if ((!err)&&((flags&PCILIB_KMEM_FLAG_MASS) == 0)&&(reused == PCILIB_TRISTATE_YES)&&((type&PCILIB_KMEM_TYPE_MASK) != PCILIB_KMEM_TYPE_REGION)) {
        kh.item = kbuf->buf.n_blocks;
        kh.flags = KMEM_FLAG_REUSE|KMEM_FLAG_TRY;
        ret = ioctl(ctx->handle, PCIDRIVER_IOC_KMEM_ALLOC, &kh);
        if (!ret) {
            kh.flags = KMEM_FLAG_REUSE;
            ioctl(ctx->handle, PCIDRIVER_IOC_KMEM_FREE, &kh);
            reused = PCILIB_TRISTATE_PARTIAL;
        } else if (errno != ENOENT) {
            reused = PCILIB_TRISTATE_PARTIAL;
        }
    }
    pcilib_unlock_global(ctx);
        //This is possible in the case of error (nothing is allocated yet) or if buffers are not reused
    if (persistent < 0) persistent = 0;
    if (hardware < 0) hardware = 0;
    if (err) {
            // do not clean if we have reused (even partially) persistent/hardware-locked buffers
        if (((persistent)||(hardware))&&(reused != PCILIB_TRISTATE_NO)) {
            pcilib_cancel_kernel_memory(ctx, kbuf, KMEM_FLAG_REUSE, 0);
        } else {
            pcilib_kmem_flags_t free_flags = 0;
            if (flags&PCILIB_KMEM_FLAG_PERSISTENT) {
                free_flags |= PCILIB_KMEM_FLAG_PERSISTENT;
            }
            if (flags&PCILIB_KMEM_FLAG_HARDWARE) {
                free_flags |= PCILIB_KMEM_FLAG_HARDWARE;
            }
                // err indicates consistensy error. The last ioctl have succeeded and we need to clean it in a special way
            pcilib_cancel_kernel_memory(ctx, kbuf, free_flags, (err == PCILIB_ERROR_INVALID_STATE)?kh.flags:0);
        }
        pcilib_warning("Error %i: %s", err, error);
        return NULL;
    }
    if (nmemb == 1) {
        memcpy(&kbuf->buf.addr, &kbuf->buf.blocks[0], sizeof(pcilib_kmem_addr_t));
    }
    kbuf->buf.type = type;
    kbuf->buf.use = use;
    kbuf->buf.reused = reused|(persistent?PCILIB_KMEM_REUSE_PERSISTENT:0)|(hardware?PCILIB_KMEM_REUSE_HARDWARE:0);
    kbuf->prev = NULL;
    kbuf->next = ctx->kmem_list;
    if (ctx->kmem_list) ctx->kmem_list->prev = kbuf;
    ctx->kmem_list = kbuf;
    return (pcilib_kmem_handle_t*)kbuf;
}
References pcilib_kmem_buffer_t::addr, pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_addr_t::ba, pcilib_kmem_buffer_t::blocks, pcilib_kmem_list_s::buf, pcilib_s::handle, pcilib_kmem_addr_t::handle_id, pcilib_s::kmem_list, pcilib_kmem_addr_t::mmap_offset, pcilib_kmem_buffer_t::n_blocks, pcilib_kmem_list_s::next, pcilib_kmem_addr_t::pa, pcilib_s::page_mask, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_STATE, PCILIB_ERROR_MEMORY, PCILIB_KMEM_FLAG_HARDWARE, PCILIB_KMEM_FLAG_MASS, PCILIB_KMEM_FLAG_PERSISTENT, PCILIB_KMEM_REUSE_HARDWARE, PCILIB_KMEM_REUSE_PERSISTENT, PCILIB_KMEM_TYPE_MASK, PCILIB_KMEM_TYPE_PAGE, PCILIB_KMEM_TYPE_REGION, pcilib_lock_global(), PCILIB_TRISTATE_NO, PCILIB_TRISTATE_PARTIAL, PCILIB_TRISTATE_YES, pcilib_unlock_global(), pcilib_warning, pcilib_kmem_list_s::prev, pcilib_kmem_buffer_t::reused, pcilib_kmem_addr_t::size, pcilib_kmem_buffer_t::type, pcilib_kmem_addr_t::ua, and pcilib_kmem_buffer_t::use.
Referenced by pcilib_destroy_all_locks(), and pcilib_init_locking().
pcilib_clean_kernel_memory()
int pcilib_clean_kernel_memory (pcilib_t * ctx, pcilib_kmem_use_t use, pcilib_kmem_flags_t flags)
Free / dereference all kernel memory buffers associated with the specified use.
Parameters
[in,out] ctx - pcilib context
[in] use - use-number to clean
[in] flags - various flags defining which referenes to hold and return and if the memory should be dereferenced or freed
Returns
- error or 0 on success
{
    kmem_handle_t kh = {0};
    kh.use = use;
    kh.flags = flags|PCILIB_KMEM_FLAG_MASS;
    return ioctl(ctx->handle, PCIDRIVER_IOC_KMEM_FREE, &kh);
}
References pcilib_s::handle, and PCILIB_KMEM_FLAG_MASS.
pcilib_free_kernel_memory()
void pcilib_free_kernel_memory (pcilib_t * ctx, pcilib_kmem_handle_t * k, pcilib_kmem_flags_t flags)
This function either frees the allocated kernel memory or just releases some of the references.
Only reference tracking is performed If the PCILIB_KMEM_FLAG_REUSE flag is passed to the function. Otherwise, non-persistent memory is released when pcilib_free_kernel_memory() called. The persistent memory is released if PCILIB_KMEM_FLAG_PERSISTENT is passed in flags parameter unless the hold references are preventing us from releasing this memory. The error is reported in this case. The kernel memory can be freed irrespective of hold references if PCILIB_KMEM_FLAG_FORCE flag is specified.
There are several types of references:
The hardware reference - indicates that the memory may be used by DMA engine of the device. It is set if pcilib_alloc_kernel_memory() is executed with PCILIB_KMEM_FLAG_HARDWARE flag. The reference can be released if the same flag is passed to pcilib_free_kernel_memory()
The software references - are obtained when the memory is reused with pcilib_alloc_kernel_memory(). They are released when corresponding pcilib_free_kernel_memory() is called.
The mmap references - are obtained when the kernel memory is mapped to the virtual memory of application which is normally happen on pcilib_alloc_kernel_memory() and fork of the process. The references are returned when memory is unmapped. This happens on pcilib_free_kernel_memory() and termination of the process with still mmaped regions.
The software references are in a way replicate functionality of the mmap references. Currently, they are used to keep track of non-persistent memory allocated and re-used within the same application (which is actually discouraged). In this case the number of pcilib_alloc_kernel_memory() should be matched by number of pcilib_free_kernel_memory() calls and only on a last call the memory will be really released. Normally, all but last calls have to be accompanied by PCILIB_KMEM_FLAG_REUSE flag or the error is reported. But to keep code simpler, the pcilib will not complain until there are software references on hold. When the last software reference is released, we try actually clean up the memory and the error is reported if other types of references are still present. The software references may stuck if application crashes before calling pcilib_free_kernel_memory(). pcilib will prevent us from releasing the kernel memory with stuck references. Such memory can be cleaned only with PCILIB_KMEM_FLAG_FORCE flag or using pcilib_clean_kernel_memory() call.
Parameters
[in,out] ctx - pcilib context
[in,out] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] flags - various flags defining which referenes to hold and return and if the memory should be preserved or freed
{
    int ret, err = 0;
    int i;
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
        // if linked in to the list
    if (kbuf->next) kbuf->next->prev = kbuf->prev;
    if (kbuf->prev) kbuf->prev->next = kbuf->next;
    else if (ctx->kmem_list == kbuf) ctx->kmem_list = kbuf->next;
    for (i = 0; i < kbuf->buf.n_blocks; i++) {
        ret = pcilib_free_kernel_buffer(ctx, kbuf, i, flags);
        if ((ret)&&(!err)) err = ret;
    }
    free(kbuf);
    if (err) {
        pcilib_error("PCIDRIVER_IOC_KMEM_FREE ioctl have failed");
    }
}
References pcilib_kmem_list_s::buf, pcilib_s::kmem_list, pcilib_kmem_buffer_t::n_blocks, pcilib_kmem_list_s::next, pcilib_error, and pcilib_kmem_list_s::prev.
Referenced by pcilib_close(), pcilib_destroy_all_locks(), and pcilib_free_locking().
pcilib_kmem_get_ba()
uintptr_t pcilib_kmem_get_ba (pcilib_t * ctx, pcilib_kmem_handle_t * k)
Get a bus address of a single-buffer kernel memory.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
Returns
- bus address or 0 if no bus mapping
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    if (kbuf->buf.addr.ba)
        return kbuf->buf.addr.ba + kbuf->buf.addr.alignment_offset;
    return 0;
}
References pcilib_kmem_buffer_t::addr, pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_addr_t::ba, and pcilib_kmem_list_s::buf.
pcilib_kmem_get_block_ba()
uintptr_t pcilib_kmem_get_block_ba (pcilib_t * ctx, pcilib_kmem_handle_t * k, size_t block)
Get a bus address of the specified kernel memory buffer.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] block - specifies the buffer within the kernel memory (buffers are numbered from 0)
Returns
- bus address or 0 if no bus mapping
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    if (kbuf->buf.blocks[block].ba)
        return kbuf->buf.blocks[block].ba + kbuf->buf.blocks[block].alignment_offset;
    return 0;
}
References pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_addr_t::ba, pcilib_kmem_buffer_t::blocks, and pcilib_kmem_list_s::buf.
pcilib_kmem_get_block_pa()
uintptr_t pcilib_kmem_get_block_pa (pcilib_t * ctx, pcilib_kmem_handle_t * k, size_t block)
Get a physical address of the specified kernel memory buffer.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] block - specifies the buffer within the kernel memory (buffers are numbered from 0)
Returns
- physical address
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.blocks[block].pa + kbuf->buf.blocks[block].alignment_offset;
}
References pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_buffer_t::blocks, pcilib_kmem_list_s::buf, and pcilib_kmem_addr_t::pa.
pcilib_kmem_get_block_size()
size_t pcilib_kmem_get_block_size (pcilib_t * ctx, pcilib_kmem_handle_t * k, size_t block)
Get size of the specified kernel memory buffer.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] block - specifies the buffer within the kernel memory (buffers are numbered from 0)
Returns
- size in bytes
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.blocks[block].size;
}
References pcilib_kmem_buffer_t::blocks, pcilib_kmem_list_s::buf, and pcilib_kmem_addr_t::size.
pcilib_kmem_get_block_ua()
volatile void * pcilib_kmem_get_block_ua (pcilib_t * ctx, pcilib_kmem_handle_t * k, size_t block)
Get a valid pointer on the user-space mapping of the specified kernel memory buffer.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] block - specifies the buffer within the kernel memory (buffers are numbered from 0)
Returns
- user-space pointer
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.blocks[block].ua + kbuf->buf.blocks[block].alignment_offset + kbuf->buf.blocks[block].mmap_offset;
}
References pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_buffer_t::blocks, pcilib_kmem_list_s::buf, pcilib_kmem_addr_t::mmap_offset, and pcilib_kmem_addr_t::ua.
Referenced by pcilib_destroy_all_locks(), pcilib_get_lock_by_id(), and pcilib_init_locking().
pcilib_kmem_get_pa()
uintptr_t pcilib_kmem_get_pa (pcilib_t * ctx, pcilib_kmem_handle_t * k)
Get a physical address of a single-buffer kernel memory.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
Returns
- physical address
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.addr.pa + kbuf->buf.addr.alignment_offset;
}
References pcilib_kmem_buffer_t::addr, pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_list_s::buf, and pcilib_kmem_addr_t::pa.
pcilib_kmem_get_ua()
volatile void * pcilib_kmem_get_ua (pcilib_t * ctx, pcilib_kmem_handle_t * k)
Get a valid pointer on the user-space mapping of a single-buffer kernel memory.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
Returns
- user-space pointer
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.addr.ua + kbuf->buf.addr.alignment_offset + kbuf->buf.addr.mmap_offset;
}
References pcilib_kmem_buffer_t::addr, pcilib_kmem_addr_t::alignment_offset, pcilib_kmem_list_s::buf, pcilib_kmem_addr_t::mmap_offset, and pcilib_kmem_addr_t::ua.
pcilib_kmem_is_reused()
pcilib_kmem_reuse_state_t pcilib_kmem_is_reused (pcilib_t * ctx, pcilib_kmem_handle_t * k)
Reports if the kernel memory was reused fully, partially, or allocated completely anew.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
Returns
- re-use information
{
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    return kbuf->buf.reused;
}
References pcilib_kmem_list_s::buf, and pcilib_kmem_buffer_t::reused.
Referenced by pcilib_destroy_all_locks(), and pcilib_init_locking().
pcilib_kmem_sync_block()
int pcilib_kmem_sync_block (pcilib_t * ctx, pcilib_kmem_handle_t * k, pcilib_kmem_sync_direction_t dir, size_t block)
Synchronizes usage of the specified buffer between hardware and the system.
Parameters
[in,out] ctx - pcilib context
[in] k - kernel memory handle returned from pcilib_alloc_kernel_memory() call
[in] dir - synchronization direction (allows either device or system access)
[in] block - specifies the buffer within the kernel memory (buffers are numbered from 0)
Returns
- error or 0 on success
{
    int ret;
    kmem_sync_t ks;
    pcilib_kmem_list_t *kbuf = (pcilib_kmem_list_t*)k;
    switch (kbuf->buf.type) {
      case PCILIB_KMEM_TYPE_DMA_S2C_PAGE:
      case PCILIB_KMEM_TYPE_DMA_C2S_PAGE:
      case PCILIB_KMEM_TYPE_REGION_S2C:
      case PCILIB_KMEM_TYPE_REGION_C2S:
        ks.dir = dir;
        ks.handle.handle_id = kbuf->buf.blocks[block].handle_id;
        ks.handle.pa = kbuf->buf.blocks[block].pa;
        ret = ioctl(ctx->handle, PCIDRIVER_IOC_KMEM_SYNC, &ks);
        if (ret) {
            pcilib_error("PCIDRIVER_IOC_KMEM_SYNC ioctl have failed");
            return PCILIB_ERROR_FAILED;
        }
        break;
      default:
        ;
    }
    return 0;
}
References pcilib_kmem_buffer_t::blocks, pcilib_kmem_list_s::buf, pcilib_s::handle, pcilib_kmem_addr_t::handle_id, pcilib_kmem_addr_t::pa, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_KMEM_TYPE_DMA_C2S_PAGE, PCILIB_KMEM_TYPE_DMA_S2C_PAGE, PCILIB_KMEM_TYPE_REGION_C2S, PCILIB_KMEM_TYPE_REGION_S2C, and pcilib_kmem_buffer_t::type.