pcilib: lock.h File Reference
lock.h File Reference
this file is the header file for the functions that implement a semaphore API for the pcitool program, using pthread robust mutexes.
#include <pcilib.h>
Macros
#define PCILIB_LOCK_SIZE 128
size of one lock.
Typedefs
typedef struct pcilib_lock_s pcilib_lock_t
structure defining a lock
Enumerations
enum pcilib_lock_flags_t { PCILIB_LOCK_FLAGS_DEFAULT = 0 , PCILIB_LOCK_FLAG_UNLOCKED = 1 , PCILIB_LOCK_FLAG_PERSISTENT = 2 }
type that defines possible flags for a lock, defining how a lock should be handled by the locking functions
Functions
int pcilib_init_lock (pcilib_lock_t *lock, pcilib_lock_flags_t flags, const char *lock_id)
this function initializes a lock, by setting correctly its property given the flags associated.
void pcilib_free_lock (pcilib_lock_t *lock_ctx)
this function will unref the defined lock.
const char * pcilib_lock_get_name (pcilib_lock_t *lock)
this function gives the identifier name associated to a lock in the kernel space
void pcilib_lock_ref (pcilib_lock_t *lock)
Increment reference count(number of processes that may access the given lock).
void pcilib_lock_unref (pcilib_lock_t *lock)
Decrement reference count (number of processes that may access the given lock) Not thread/process safe unless system supports stdatomic (gcc 4.9+).
size_t pcilib_lock_get_refs (pcilib_lock_t *lock)
Return approximate number of lock references as the crashed applications will may not unref.
pcilib_lock_flags_t pcilib_lock_get_flags (pcilib_lock_t *lock)
gets the flags associated to the given lock
int pcilib_lock_custom (pcilib_lock_t *lock, pcilib_lock_flags_t flags, pcilib_timeout_t timeout)
this function will call different locking functions to acquire the given lock.
int pcilib_lock (pcilib_lock_t *lock)
function to acquire a lock, and wait till the lock can be acquire
int pcilib_try_lock (pcilib_lock_t *lock)
this function will try to take a lock for the mutex pointed by lockfunction to acquire a lock, but that returns immediatly if the lock can't be acquired on first try
void pcilib_unlock (pcilib_lock_t *lock)
this function unlocks the lock pointed by lock
Detailed Description
this file is the header file for the functions that implement a semaphore API for the pcitool program, using pthread robust mutexes.
the use of pthread robust mutexes was chosen due to the fact we privilege security over fastness, and that pthread mutexes permits to recover semaphores even with crash ,and that it does not require access to resources that can be easily accessible from extern usage as flock file locking mechanism. A possible other locking mechanism could be the sysv semaphores, but we have a problem of how determine a perfect hash for the init function, and more, benchmarks proves that sysv semaphore aren't that stable. For pure locking/unlocking, pthread is better in performance than sysV, but it suffers from big initialization times. In this sense, a kernel memory space is used for saving the locks, and persistence permits to avoid initializations over uses.
We considered that mutex implmentation is enough compared to a reader/writer implementation. If it should change, please go to sysv semaphore.
Basic explanation on how semaphores here work: a semaphore here is a positive integer, thus that can't go below zero, which is initiated with a value. when a process want access to the critical resource, it asks to decrement the value of the semaphore, and when it has finished, it reincrements it.basically, when the semaphore is equal to zero, any process must have to wait for it to be reincremented before decrementing it again. Here are defined two types of access to the semaphore corresponding to the reader/writer problem : an exclusive lock, which means that no other process than the one who have the resource can access it; a shared lock, which means that other processes who want to access to the resource with a shared lock can have the access, but a concurrent process who want to access the semaphore with an exclusive lock won't be able to. explanation on locks here : here locks are registered in kernel memory, where they are defined by a pthread_mutex_t and an identifier name, which corresponds most of the time to a mix of the register associated name and processus (but it's up to the user). The iterations like searching a lock are done on this id name.
Macro Definition Documentation
PCILIB_LOCK_SIZE
#define PCILIB_LOCK_SIZE 128
size of one lock.
indeed, as we can't allocate easily on the fly memory in the kernel, fixed size have been chosen. determines so the size of the identifier name in the way locks are registered. 40 bytes are necessary for the mutex structure, so we have an id name of length LOCK_SIZE-40
Typedef Documentation
pcilib_lock_t
typedef struct pcilib_lock_s pcilib_lock_t
structure defining a lock
Enumeration Type Documentation
pcilib_lock_flags_t
enum pcilib_lock_flags_t
type that defines possible flags for a lock, defining how a lock should be handled by the locking functions
Enumerator
PCILIB_LOCK_FLAGS_DEFAULT
Default flags.
PCILIB_LOCK_FLAG_UNLOCKED
Perform operations unlocked, thus without taking care of the lock (protected by global flock during initialization of locking subsystem)
PCILIB_LOCK_FLAG_PERSISTENT
Do not create robust mutexes, but preserve the lock across application launches.
             {
    PCILIB_LOCK_FLAGS_DEFAULT = 0,
    PCILIB_LOCK_FLAG_UNLOCKED = 1,
    PCILIB_LOCK_FLAG_PERSISTENT = 2
} pcilib_lock_flags_t;
Function Documentation
pcilib_free_lock()
void pcilib_free_lock (pcilib_lock_t * lock_ctx)
this function will unref the defined lock.
Any subsequent tries to lock it without reinitializaing it will fail.
Parameters
[in,out] lock_ctx - the pointer that points to the lock.
{
    int err;
    assert(lock);
//    if (lock->refs)
//      pcilib_error("Forbidding to destroy the referenced mutex...");
    if ((err = pthread_mutex_destroy(&lock->mutex))==-1)
        pcilib_warning("Can't destroy POSIX mutex, errno %i",errno);
}
References pcilib_lock_s::mutex, and pcilib_warning.
Referenced by pcilib_destroy_all_locks().
pcilib_init_lock()
int pcilib_init_lock (pcilib_lock_t * lock, pcilib_lock_flags_t flags, const char * lock_id)
this function initializes a lock, by setting correctly its property given the flags associated.
Parameters
[in,out] lock - pointer to lock to initialize
[in] flags - flags: if it's set to two, then not a robust mutex is created
[in] lock_id - lock identificator
Returns
error code or 0 on success
{
    int err;
    pthread_mutexattr_t attr;
    assert(lock);
    assert(lock_id);
    memset(lock, 0, PCILIB_LOCK_SIZE);
    if (strlen(lock_id) >= (PCILIB_LOCK_SIZE - offsetof(struct pcilib_lock_s, name))) {
        pcilib_error("The supplied lock id (%s) is too long...", lock_id);
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    if ((err = pthread_mutexattr_init(&attr))!=0) {
        pcilib_error("Can't initialize mutex attribute, errno %i", errno);
        return PCILIB_ERROR_FAILED;
    }
        /* we declare the mutex as possibly shared amongst different processes*/
    if ((err = pthread_mutexattr_setpshared(&attr, PTHREAD_PROCESS_SHARED))!=0) {
        pcilib_error("Can't configure a shared mutex attribute, errno %i", errno);
        return PCILIB_ERROR_FAILED;
    }
        /* we set the mutex as robust, so it would be automatically unlocked if the application crash*/
    if ((flags&PCILIB_LOCK_FLAG_PERSISTENT)==0) {
        if ((err = pthread_mutexattr_setrobust(&attr, PTHREAD_MUTEX_ROBUST))!=0) {
            pcilib_error("Can't configure a robust mutex attribute, errno: %i", errno);
            return PCILIB_ERROR_FAILED;
        }
    }
    if ((err = pthread_mutex_init(&lock->mutex, &attr))!=0) {
        pcilib_error("Can't create mutex, errno : %i",errno);
        return PCILIB_ERROR_FAILED;
    }
    strcpy(lock->name, lock_id);
    lock->refs = 1;
    lock->flags = flags;
    return 0;
}
References pcilib_lock_s::flags, pcilib_lock_s::mutex, pcilib_lock_s::name, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_LOCK_FLAG_PERSISTENT, PCILIB_LOCK_SIZE, and pcilib_lock_s::refs.
Referenced by pcilib_get_lock().
pcilib_lock()
int pcilib_lock (pcilib_lock_t * lock)
function to acquire a lock, and wait till the lock can be acquire
Parameters
[in] lock - the pointer to the mutex
Returns
error code or 0 for correctness
{
    return pcilib_lock_custom(lock, PCILIB_LOCK_FLAGS_DEFAULT, PCILIB_TIMEOUT_INFINITE);
}
References pcilib_lock_custom(), PCILIB_LOCK_FLAGS_DEFAULT, and PCILIB_TIMEOUT_INFINITE.
Referenced by pcilib_get_lock(), and pcilib_return_lock().
pcilib_lock_custom()
int pcilib_lock_custom (pcilib_lock_t * lock, pcilib_lock_flags_t flags, pcilib_timeout_t timeout)
this function will call different locking functions to acquire the given lock.
Given the flags, it is thus possible to: 1) the process requesting the lock will be held till it can acquire it 2)the lock is tried to be acquired, if the lock can be acquired then it is, if not, then the function returns immediatly and the lock is not taken at all 3) same than previous, but it's possible to define a waiting time to acquire the lock before returning
Parameters
[in] lock - the pointer to the mutex
[in] flags - define the type of lock wanted
[in] timeout - the waiting time if asked, before the function returns without having obtained the lock, in micro seconds
Returns
error code or 0 for correctness
{
    int err;
    if (!lock) {
        pcilib_error("The null lock pointer is passed to lock function");
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    struct timespec tm;
    switch (timeout) {
     case PCILIB_TIMEOUT_INFINITE:
        /* the process will be hold till it can gain acquire the lock*/
        err = pthread_mutex_lock(&lock->mutex);
        break;
     case PCILIB_TIMEOUT_IMMEDIATE:
        /* the function returns immediatly if it can't acquire the lock*/
        err = pthread_mutex_trylock(&lock->mutex);
        break;
     default:
        /* the process will be hold till it can acquire the lock and timeout is not reached*/
        clock_gettime(CLOCK_REALTIME, &tm);
        tm.tv_nsec += 1000 * (timeout%1000000);
        if (tm.tv_nsec < 1000000000)
            tm.tv_sec += timeout/1000000;
        else {
            tm.tv_sec += 1 + timeout/1000000;
            tm.tv_nsec -= 1000000000;
        }
        err = pthread_mutex_timedlock(&lock->mutex, &tm);
    }
    if (!err)
        return 0;
    switch (err) {
     case EOWNERDEAD:
        /*in the case an application with a lock acquired crashes, this lock becomes inconsistent. we have so to make it consistent again to use it again.*/
        err = pthread_mutex_consistent(&lock->mutex);
        if (err) {
            pcilib_error("Failed to mark mutex as consistent, errno %i", err);
            break;
        }
        return 0;
     case ETIMEDOUT:
     case EBUSY:
        return PCILIB_ERROR_TIMEOUT;
     default:
        pcilib_error("Failed to obtain mutex, errno %i", err);
    }
    return PCILIB_ERROR_FAILED;
}
References pcilib_lock_s::mutex, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_ERROR_TIMEOUT, PCILIB_TIMEOUT_IMMEDIATE, PCILIB_TIMEOUT_INFINITE, timespec::tv_nsec, and timespec::tv_sec.
Referenced by pcilib_lock(), and pcilib_try_lock().
pcilib_lock_get_flags()
pcilib_lock_flags_t pcilib_lock_get_flags (pcilib_lock_t * lock)
gets the flags associated to the given lock
Parameters
[in] lock - the lock we want to know the flags
Returns
value of the flag associated
{
    return lock->flags;
}
References pcilib_lock_s::flags.
Referenced by pcilib_get_lock().
pcilib_lock_get_name()
const char * pcilib_lock_get_name (pcilib_lock_t * lock)
this function gives the identifier name associated to a lock in the kernel space
Parameters
[in] lock - pointer to the lock we want the name
Returns
string corresponding to the name
{
    assert(lock);
    if (lock->name[0]) return lock->name;
    return NULL;
}
References pcilib_lock_s::name.
Referenced by pcilib_destroy_all_locks(), and pcilib_get_lock().
pcilib_lock_get_refs()
size_t pcilib_lock_get_refs (pcilib_lock_t * lock)
Return approximate number of lock references as the crashed applications will may not unref.
Parameters
[in,out] lock - pointer to initialized lock
Returns
the number of lock refs
{
    return lock->refs;
}
References pcilib_lock_s::refs.
Referenced by pcilib_destroy_all_locks().
pcilib_lock_ref()
void pcilib_lock_ref (pcilib_lock_t * lock)
Increment reference count(number of processes that may access the given lock).
Not thread/process safe unless system supports stdatomic (gcc 4.9+). In this case, the access should be synchronized by the caller.
Parameters
[in,out] lock - pointer to initialized lock
{
    assert(lock);
#ifdef HAVE_STDATOMIC_H
    atomic_fetch_add_explicit(&lock->refs, 1, memory_order_relaxed);
#else /* HAVE_STDATOMIC_H */
    lock->refs++;
#endif  /* HAVE_STDATOMIC_H */
}
References pcilib_lock_s::refs.
Referenced by pcilib_get_lock().
pcilib_lock_unref()
void pcilib_lock_unref (pcilib_lock_t * lock)
Decrement reference count (number of processes that may access the given lock) Not thread/process safe unless system supports stdatomic (gcc 4.9+).
In this case, the access should be synchronized by the caller
Parameters
[in,out] lock - pointer to initialized lock
{
    assert(lock);
    if (!lock->refs) {
        pcilib_warning("Lock is not referenced");
        return;
    }
#ifdef HAVE_STDATOMIC_H
    atomic_fetch_sub_explicit(&lock->refs, 1, memory_order_relaxed);
#else /* HAVE_STDATOMIC_H */
    lock->refs--;
#endif  /* HAVE_STDATOMIC_H */
}
References pcilib_warning, and pcilib_lock_s::refs.
Referenced by pcilib_return_lock().
pcilib_try_lock()
int pcilib_try_lock (pcilib_lock_t * lock)
this function will try to take a lock for the mutex pointed by lockfunction to acquire a lock, but that returns immediatly if the lock can't be acquired on first try
Parameters
[in] lock - the pointer to the mutex
Returns
error code or 0 for correctness
{
    return pcilib_lock_custom(lock, PCILIB_LOCK_FLAGS_DEFAULT, PCILIB_TIMEOUT_IMMEDIATE);
}
References pcilib_lock_custom(), PCILIB_LOCK_FLAGS_DEFAULT, and PCILIB_TIMEOUT_IMMEDIATE.
Referenced by pcilib_push_dma(), and pcilib_stream_dma().
pcilib_unlock()
void pcilib_unlock (pcilib_lock_t * lock)
this function unlocks the lock pointed by lock
Parameters
[in] lock - the integer that points to the semaphore
{
    int err;
    if (!lock)
        return;
    if ((err = pthread_mutex_unlock(&lock->mutex)) != 0) {
        switch (err) {
         case EPERM:
            pcilib_error("Trying to unlock not locked mutex (%s) or the mutex which was locked by a different thread", lock->name);
            break;
         default:
            pcilib_error("Can't unlock mutex, errno %i", err);
        }
    }
}
References pcilib_lock_s::mutex, pcilib_lock_s::name, and pcilib_error.
Referenced by pcilib_get_lock(), pcilib_push_dma(), pcilib_return_lock(), and pcilib_stream_dma().