pcilib: locking.h File Reference
locking.h File Reference
this file is the header file for functions that touch all locks allocated for software registers.
#include <pcilib/kmem.h>
#include <pcilib/lock.h>
Data Structures
struct pcilib_locking_s
structure defining the kernel space used for locks
Macros
#define PCILIB_MAX_LOCKS 64
number of maximum locks
#define PCILIB_LOCKS_PER_PAGE (PCILIB_KMEM_PAGE_SIZE/PCILIB_LOCK_SIZE)
number of locks per page of kernel memory
#define PCILIB_LOCK_PAGES ((PCILIB_MAX_LOCKS * PCILIB_LOCK_SIZE)/PCILIB_KMEM_PAGE_SIZE)
number of pages allocated for locks in kernel memory
Typedefs
typedef uint32_t pcilib_lock_id_t
type to represent the index of a lock in the table of locks in the kernel space
typedef struct pcilib_locking_s pcilib_locking_t
Functions
int pcilib_init_locking (pcilib_t *ctx)
this function gets the kernel space for the locks : if this space have been already initialized, then the previous space is returned.
void pcilib_free_locking (pcilib_t *ctx)
this function cleans the memory from all locks : the kernel space is freed, and locks references in pcilib_t are destroyed by setting memory to 0
int pcilib_lock_global (pcilib_t *ctx)
this function use flock locking mechanism on the ALPS platform device file, to make sure to not create two kernel spaces for locks
void pcilib_unlock_global (pcilib_t *ctx)
function to remove the lock created by flock on the ALPS platform device file
pcilib_lock_t * pcilib_get_lock_by_id (pcilib_t *ctx, pcilib_lock_id_t id)
this function returns the lock at the index in the kernel space equal to id
pcilib_lock_t * pcilib_get_lock (pcilib_t *ctx, pcilib_lock_flags_t flags, const char *lock_id,...)
this function verify if the lock requested exists in the kernel space.
void pcilib_return_lock (pcilib_t *ctx, pcilib_lock_flags_t flags, pcilib_lock_t *lock)
this function is to decrement the variable in a lock containing the number of processes that may access to this lock(refs)
int pcilib_destroy_all_locks (pcilib_t *ctx, int force)
this function destroy all the locks that have been created(unref the locks + set memory to 0), and so is used when we want to clean properly the kernel space.
Detailed Description
this file is the header file for functions that touch all locks allocated for software registers.
for more details about implementation choice, please read the file lock.h
Macro Definition Documentation
PCILIB_LOCK_PAGES
#define PCILIB_LOCK_PAGES ((PCILIB_MAX_LOCKS * PCILIB_LOCK_SIZE)/PCILIB_KMEM_PAGE_SIZE)
number of pages allocated for locks in kernel memory
PCILIB_LOCKS_PER_PAGE
#define PCILIB_LOCKS_PER_PAGE (PCILIB_KMEM_PAGE_SIZE/PCILIB_LOCK_SIZE)
number of locks per page of kernel memory
PCILIB_MAX_LOCKS
#define PCILIB_MAX_LOCKS 64
number of maximum locks
Typedef Documentation
pcilib_lock_id_t
typedef uint32_t pcilib_lock_id_t
type to represent the index of a lock in the table of locks in the kernel space
pcilib_locking_t
typedef struct pcilib_locking_s pcilib_locking_t
Function Documentation
pcilib_destroy_all_locks()
int pcilib_destroy_all_locks (pcilib_t * ctx, int force)
this function destroy all the locks that have been created(unref the locks + set memory to 0), and so is used when we want to clean properly the kernel space.
If force is set to 1, then we don't care about other processes that may request locks. If not, if there is locks that may be requested by other processes, then the operation is stopped. Of course, destroying locks that may be requested by other processes results in an undefined behaviour. Thus, it is user responsibility to issue this command with force set to 1
Parameters
[in,out] ctx - the pcilib_t structure running
[in] force - should the operation be forced or not
Returns
error code : 0 if everything was ok
{
    int err;
    pcilib_lock_id_t i;
    pcilib_kmem_reuse_state_t reused;
    if (strcasecmp(ctx->model, "maintenance")) {
        pcilib_error("Can't destroy locks while locking subsystem is initialized, use maintenance model");
        return PCILIB_ERROR_INVALID_STATE;
    }
    err = pcilib_lock_global(ctx);
    if (err) return err;
        // ToDo: We should check here that no other instances of pcitool are running, the driver can provide this information
    ctx->locks.kmem = pcilib_alloc_kernel_memory(ctx, PCILIB_KMEM_TYPE_PAGE, PCILIB_LOCK_PAGES, PCILIB_KMEM_PAGE_SIZE, 0, PCILIB_KMEM_USE(PCILIB_KMEM_USE_LOCKS,0), PCILIB_KMEM_FLAG_REUSE|PCILIB_KMEM_FLAG_PERSISTENT);
    if (!ctx->locks.kmem) {
        pcilib_unlock_global(ctx);
        pcilib_error("Failed to allocate kernel memory of locking subsystem");
        return PCILIB_ERROR_FAILED;
    }
    reused = pcilib_kmem_is_reused(ctx, ctx->locks.kmem);
    if (reused & PCILIB_KMEM_REUSE_PARTIAL) {
        pcilib_unlock_global(ctx);
        pcilib_error("Inconsistent kernel memory for locking subsystem is found (only part of the required buffers is available)");
        return PCILIB_ERROR_INVALID_STATE;
    }
    if ((reused & PCILIB_KMEM_REUSE_REUSED) == 0) {
        pcilib_free_kernel_memory(ctx, ctx->locks.kmem, PCILIB_KMEM_FLAG_REUSE|PCILIB_KMEM_FLAG_PERSISTENT);
        pcilib_unlock_global(ctx);
        return 0;
    }
        /* if we run in non-forced case, then if it may be still processes that can have access to the locks, they are not destroyed*/
    if (!force) {
        for (i = 0; i < PCILIB_MAX_LOCKS; i++) {
            pcilib_lock_t *lock = pcilib_get_lock_by_id(ctx, i);
            const char *name = pcilib_lock_get_name(lock);
            if (!name) break;
            size_t refs = pcilib_lock_get_refs(lock);
            if (refs > 0) {
                char *stmp = strdup(name);
                pcilib_free_locking(ctx);
                pcilib_unlock_global(ctx);
                pcilib_error("Lock (%s) has %zu references, destroying references may result in crashes and data corruption", stmp, refs);
                free(stmp);
                return PCILIB_ERROR_BUSY;
            }
        }
    }
        // Do we really need this? I guess zeroing should be enough
    for (i = 0; i < PCILIB_MAX_LOCKS; i++) {
        pcilib_lock_t *lock = pcilib_get_lock_by_id(ctx, i);
        const char *name = pcilib_lock_get_name(lock);
        if (!name) break;
        pcilib_free_lock(lock);
    }
    for (i = 0; i < PCILIB_LOCK_PAGES; i++) {
        void *addr = (void*)pcilib_kmem_get_block_ua(ctx, ctx->locks.kmem, i);
        memset(addr, 0, PCILIB_KMEM_PAGE_SIZE);
    }
    pcilib_free_locking(ctx);
    pcilib_unlock_global(ctx);
    return 0;
}
References pcilib_locking_s::kmem, pcilib_s::locks, pcilib_s::model, pcilib_alloc_kernel_memory(), pcilib_error, PCILIB_ERROR_BUSY, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_STATE, pcilib_free_kernel_memory(), pcilib_free_lock(), pcilib_free_locking(), pcilib_get_lock_by_id(), PCILIB_KMEM_FLAG_PERSISTENT, PCILIB_KMEM_FLAG_REUSE, pcilib_kmem_get_block_ua(), pcilib_kmem_is_reused(), PCILIB_KMEM_PAGE_SIZE, PCILIB_KMEM_REUSE_PARTIAL, PCILIB_KMEM_REUSE_REUSED, PCILIB_KMEM_TYPE_PAGE, PCILIB_KMEM_USE, PCILIB_KMEM_USE_LOCKS, pcilib_lock_get_name(), pcilib_lock_get_refs(), pcilib_lock_global(), PCILIB_LOCK_PAGES, PCILIB_MAX_LOCKS, and pcilib_unlock_global().
pcilib_free_locking()
void pcilib_free_locking (pcilib_t * ctx)
this function cleans the memory from all locks : the kernel space is freed, and locks references in pcilib_t are destroyed by setting memory to 0
Parameters
[in,out] ctx - the pcilib_t structure running
{
    if (ctx->locks.locking)
        pcilib_return_lock(ctx, PCILIB_LOCK_FLAGS_DEFAULT, ctx->locks.locking);
    if (ctx->locks.kmem) {
        pcilib_free_kernel_memory(ctx, ctx->locks.kmem, PCILIB_KMEM_FLAG_REUSE);
    }
    memset(&ctx->locks, 0, sizeof(pcilib_locking_t));
}
References pcilib_locking_s::kmem, pcilib_locking_s::locking, pcilib_s::locks, pcilib_free_kernel_memory(), PCILIB_KMEM_FLAG_REUSE, PCILIB_LOCK_FLAGS_DEFAULT, and pcilib_return_lock().
Referenced by pcilib_close(), and pcilib_destroy_all_locks().
pcilib_get_lock()
pcilib_lock_t * pcilib_get_lock (pcilib_t * ctx, pcilib_lock_flags_t flags, const char * lock_id, ...)
this function verify if the lock requested exists in the kernel space.
If yes, then nothing is done, else we create the lock in the kernel space. This function also gives the number of processes that may request the lock afterwards, including the one that just created it.
Parameters
[in] ctx - the pcilib_t structure running
[in] flags - the flag defining the property of the lock
[in] lock_id - the identifier name for the lock
Returns
the corresponding lock, or a new one if it did not exist before
{
    pcilib_lock_id_t i;
    int err, ret;
    pcilib_lock_t *lock;
    char buffer[PCILIB_LOCK_SIZE];
        /* we construct the complete lock_id given the parameters of the function*/
    va_list pa;
    va_start(pa, lock_id);
    ret = vsnprintf(buffer, PCILIB_LOCK_SIZE, lock_id, pa);
    va_end(pa);
    if (ret < 0) {
        pcilib_error("Failed to construct the lock id, probably arguments does not match the format string (%s)...", lock_id);
        return NULL;
    }
        /* we iterate through locks to see if there is one already with the same name*/
        // Would be nice to have hash here
    for (i = 0; i < PCILIB_MAX_LOCKS; i++) {
        lock = pcilib_get_lock_by_id(ctx, i);
        const char *name = pcilib_lock_get_name(lock);
        if (!name) break;
        if (!strcmp(buffer, name)) {
            if ((pcilib_lock_get_flags(lock)&PCILIB_LOCK_FLAG_PERSISTENT) != (flags&PCILIB_LOCK_FLAG_PERSISTENT)) {
                if (flags&PCILIB_LOCK_FLAG_PERSISTENT)
                    pcilib_error("Requesting persistent lock (%s), but requested lock is already existing and is robust", name);
                else
                    pcilib_error("Requesting robust lock (%s), but requested lock is already existing and is persistent", name);
                return NULL;
            }
#ifndef HAVE_STDATOMIC_H
            if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0) {
                err = pcilib_lock(ctx->locks.locking);
                if (err) {
                    pcilib_error("Error (%i) obtaining global lock", err);
                    return NULL;
                }
            }
#endif /* ! HAVE_STDATOMIC_H */
        /* if yes, we increment its ref variable*/
            pcilib_lock_ref(lock);
#ifndef HAVE_STDATOMIC_H
            if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
                pcilib_unlock(ctx->locks.locking);
#endif /* ! HAVE_STDATOMIC_H */
            return lock;
        }
    }
    if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0) {
        err = pcilib_lock(ctx->locks.locking);
        if (err) {
            pcilib_error("Error (%i) obtaining global lock", err);
            return NULL;
        }
    }
        // Make sure it was not allocated meanwhile
    for (; i < PCILIB_MAX_LOCKS; i++) {
        lock = pcilib_get_lock_by_id(ctx, i);
        const char *name = pcilib_lock_get_name(lock);
        if (!name) break;
        if (!strcmp(buffer, name)) {
            if ((pcilib_lock_get_flags(lock)&PCILIB_LOCK_FLAG_PERSISTENT) != (flags&PCILIB_LOCK_FLAG_PERSISTENT)) {
                if (flags&PCILIB_LOCK_FLAG_PERSISTENT)
                    pcilib_error("Requesting persistent lock (%s), but requested lock is already existing and is robust", name);
                else
                    pcilib_error("Requesting robust lock (%s), but requested lock is already existing and is persistent", name);
                if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
                    pcilib_unlock(ctx->locks.locking);
                return NULL;
            }
            pcilib_lock_ref(lock);
            if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
                pcilib_unlock(ctx->locks.locking);
            return lock;
        }
    }
    if (i == PCILIB_MAX_LOCKS) {
        if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
            pcilib_unlock(ctx->locks.locking);
        pcilib_error("Failed to create lock (%s), only %u locks is supported", buffer, PCILIB_MAX_LOCKS);
        return NULL;
    }
        /* if the lock did not exist before, then we create it*/
    err = pcilib_init_lock(lock, flags, buffer);
    if (err) {
        pcilib_error("Lock initialization failed with error %i", err);
        if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
            pcilib_unlock(ctx->locks.locking);
        return NULL;
    }
    if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
        pcilib_unlock(ctx->locks.locking);
    return lock;
}
References pcilib_locking_s::locking, pcilib_s::locks, pcilib_error, pcilib_get_lock_by_id(), pcilib_init_lock(), pcilib_lock(), PCILIB_LOCK_FLAG_PERSISTENT, PCILIB_LOCK_FLAG_UNLOCKED, pcilib_lock_get_flags(), pcilib_lock_get_name(), pcilib_lock_ref(), PCILIB_LOCK_SIZE, PCILIB_MAX_LOCKS, and pcilib_unlock().
Referenced by pcilib_init_dma(), and pcilib_init_locking().
pcilib_get_lock_by_id()
pcilib_lock_t * pcilib_get_lock_by_id (pcilib_t * ctx, pcilib_lock_id_t id)
this function returns the lock at the index in the kernel space equal to id
Parameters
[in] ctx - the pcilib_t structure running
[in] id - the index of the lock
Returns
the lock structure corresponding
{
    int page = id / PCILIB_LOCKS_PER_PAGE;
    int offset = id - page * PCILIB_LOCKS_PER_PAGE;
    volatile void *addr = pcilib_kmem_get_block_ua(ctx, ctx->locks.kmem, page);
    pcilib_lock_t *lock = (pcilib_lock_t*)(addr + offset * PCILIB_LOCK_SIZE);
    return lock;
}
References pcilib_locking_s::kmem, pcilib_s::locks, pcilib_kmem_get_block_ua(), PCILIB_LOCK_SIZE, and PCILIB_LOCKS_PER_PAGE.
Referenced by pcilib_destroy_all_locks(), and pcilib_get_lock().
pcilib_init_locking()
int pcilib_init_locking (pcilib_t * ctx)
this function gets the kernel space for the locks : if this space have been already initialized, then the previous space is returned.
If not, the space is created. this function has to be protected, in order to avoid the simultaneous creation of 2 kernel spaces. For that, we use pcilib_lock_global.
Parameters
[in,out] ctx - the pcilib_t structure running, getting filled with a ref to locks' kernel space
{
    int i;
    int err;
    pcilib_kmem_reuse_state_t reused;
    assert(PCILIB_LOCK_PAGES * PCILIB_KMEM_PAGE_SIZE >= PCILIB_MAX_LOCKS * PCILIB_LOCK_SIZE);
        /*protection against multiple creations of kernel space*/
    err = pcilib_lock_global(ctx);
    if (err) return err;
        /* by default, this kernel space is persistent and will be reused, in order to avoid the big initialization times for robust mutexes each time we run pcitool*/
    ctx->locks.kmem = pcilib_alloc_kernel_memory(ctx, PCILIB_KMEM_TYPE_PAGE, PCILIB_LOCK_PAGES, PCILIB_KMEM_PAGE_SIZE, 0, PCILIB_KMEM_USE(PCILIB_KMEM_USE_LOCKS,0), PCILIB_KMEM_FLAG_REUSE|PCILIB_KMEM_FLAG_PERSISTENT);
    if (!ctx->locks.kmem) {
        pcilib_unlock_global(ctx);
        pcilib_error("Allocation of kernel memory for locking subsystem has failed");
        return PCILIB_ERROR_FAILED;
    }
    reused = pcilib_kmem_is_reused(ctx, ctx->locks.kmem);
    if (reused & PCILIB_KMEM_REUSE_PARTIAL) {
        pcilib_unlock_global(ctx);
        pcilib_error("Inconsistent kernel memory for locking subsystem is found (only part of the required buffers is available)");
        return PCILIB_ERROR_INVALID_STATE;
    }
    if ((reused & PCILIB_KMEM_REUSE_REUSED) == 0) {
        for (i = 0; i < PCILIB_LOCK_PAGES; i++) {
            void *addr = (void*)pcilib_kmem_get_block_ua(ctx, ctx->locks.kmem, i);
            memset(addr, 0, PCILIB_KMEM_PAGE_SIZE);
        }
    }
        /* the lock that has been used for the creation of kernel space is declared unlocked, has we shouldnot use it anymore*/
    ctx->locks.locking = pcilib_get_lock(ctx, PCILIB_LOCK_FLAG_UNLOCKED, "locking");
    pcilib_unlock_global(ctx);
    if ((!ctx->locks.locking)) {
        pcilib_error("Locking subsystem has failed to initialized mandatory global locks");
        return PCILIB_ERROR_FAILED;
    }
    return 0;
}
References pcilib_locking_s::kmem, pcilib_locking_s::locking, pcilib_s::locks, pcilib_alloc_kernel_memory(), pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_STATE, pcilib_get_lock(), PCILIB_KMEM_FLAG_PERSISTENT, PCILIB_KMEM_FLAG_REUSE, pcilib_kmem_get_block_ua(), pcilib_kmem_is_reused(), PCILIB_KMEM_PAGE_SIZE, PCILIB_KMEM_REUSE_PARTIAL, PCILIB_KMEM_REUSE_REUSED, PCILIB_KMEM_TYPE_PAGE, PCILIB_KMEM_USE, PCILIB_KMEM_USE_LOCKS, PCILIB_LOCK_FLAG_UNLOCKED, pcilib_lock_global(), PCILIB_LOCK_PAGES, PCILIB_LOCK_SIZE, PCILIB_MAX_LOCKS, and pcilib_unlock_global().
Referenced by pcilib_open().
pcilib_lock_global()
int pcilib_lock_global (pcilib_t * ctx)
this function use flock locking mechanism on the ALPS platform device file, to make sure to not create two kernel spaces for locks
Parameters
[in,out] ctx - the pcilib_t structure running
{
    int err;
    /* we flock() on the board's device file to make sure to not have two initialization in the same time (possible long time to init) */
    if ((err = flock(ctx->handle, LOCK_EX))==-1) {
        pcilib_error("Can't get flock on device file");
        return PCILIB_ERROR_FAILED;
    }
    return 0;
}
References pcilib_s::handle, pcilib_error, and PCILIB_ERROR_FAILED.
Referenced by pcilib_alloc_kernel_memory(), pcilib_destroy_all_locks(), pcilib_init_locking(), pcilib_map_area(), and pcilib_map_bar().
pcilib_return_lock()
void pcilib_return_lock (pcilib_t * ctx, pcilib_lock_flags_t flags, pcilib_lock_t * lock)
this function is to decrement the variable in a lock containing the number of processes that may access to this lock(refs)
Parameters
[in] ctx - the pcilib_t structure running
[in] flags - the flag defining the property of the lock
[in] lock - pointer to the lock we want to modify
{
#ifndef HAVE_STDATOMIC_H
        int err;
        if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0) {
            err = pcilib_lock(ctx->locks.locking);
            if (err) {
                pcilib_error("Error (%i) obtaining global lock", err);
                return;
            }
        }
#endif /* ! HAVE_STDATOMIC_H */
        pcilib_lock_unref(lock);
#ifndef HAVE_STDATOMIC_H
        if ((flags&PCILIB_LOCK_FLAG_UNLOCKED)==0)
            pcilib_unlock(ctx->locks.locking);
#endif /* ! HAVE_STDATOMIC_H */
}
References pcilib_locking_s::locking, pcilib_s::locks, pcilib_error, pcilib_lock(), PCILIB_LOCK_FLAG_UNLOCKED, pcilib_lock_unref(), and pcilib_unlock().
Referenced by pcilib_close(), and pcilib_free_locking().
pcilib_unlock_global()
void pcilib_unlock_global (pcilib_t * ctx)
function to remove the lock created by flock on the ALPS platform device file
Parameters
[in,out] ctx - the pcilib_t structure running
{
    if (flock(ctx->handle, LOCK_UN) == -1)
        pcilib_warning("Could not correctly remove lock from the device file");
}
References pcilib_s::handle, and pcilib_warning.
Referenced by pcilib_alloc_kernel_memory(), pcilib_destroy_all_locks(), pcilib_init_locking(), pcilib_map_area(), and pcilib_map_bar().