pcilib: memcpy.c File Reference
memcpy.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <assert.h>
#include <ctype.h>
#include <time.h>
#include <sched.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include "pci.h"
#include "tools.h"
#include "error.h"
Macros
#define _POSIX_C_SOURCE 200112L
#define _GNU_SOURCE
Typedefs
typedef void *(* pcilib_memcpy_routine_t) (void *dst, void const *src, size_t bytes)
Functions
void * pcilib_memcpy8 (void *dst, void const *src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
void * pcilib_memcpy32 (void *dst, void const *src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
void * pcilib_memcpy64 (void *dst, void const *src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
void * pcilib_memcpy (void *dst, void const *src, uint8_t access, size_t n)
The collection of slow memcpy functions to move the data between BAR and system memory.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200112L
Typedef Documentation
pcilib_memcpy_routine_t
typedef void *(* pcilib_memcpy_routine_t) (void *dst, void const *src, size_t bytes)
Function Documentation
pcilib_memcpy()
void * pcilib_memcpy (void * dst, void const * src, uint8_t access, size_t n)
The collection of slow memcpy functions to move the data between BAR and system memory.
The hardware may restrict access width or expose different behavior depending on the access width. These functions access memory using the specified word width only. 8-, 16-, 32-, and 64-bit wide access is supported.
Parameters
[out] dst - the destination memory region
[in] src - the source memory region
[in] access - the size of word (a single memory access) in bytes
[in] n - the number of words to copy (n * access bytes are copied).
Returns
- dst or NULL on error
{
    size_t pos = 0, size = n * access;
    pcilib_memcpy_routine_t routine;
    assert((access)&&(access <= 8));
    while (access >>= 1) ++pos;
    routine = pcilib_memcpy_routines[pos];
    return routine(dst, src, size);
}
Referenced by pcilib_read(), pcilib_read_fifo(), pcilib_write(), and pcilib_write_fifo().
pcilib_memcpy32()
void * pcilib_memcpy32 (void * dst, void const * src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
The hardware may restrict access width or expose different behavior depending on the access width. This function only perform 32-bit memory accesses.
Parameters
[out] dst - the destination memory region
[in] src - the source memory region
[in] len - the number of bytes to copy
Returns
- dst or NULL on error
{
    uint32_t * plDst = (uint32_t *) dst;
    uint32_t const * plSrc = (uint32_t const *) src;
    while (len >= 4) {
//        *plDst = ntohl(*plSrc);
        *plDst = *plSrc;
        plSrc++;
        plDst++;
        len -= 4;
    }
    char * pcDst = (char *) plDst;
    char const * pcSrc = (char const *) plSrc;
    while (len--) {
        *pcDst++ = *pcSrc++;
    }
    return (dst);
}
pcilib_memcpy64()
void * pcilib_memcpy64 (void * dst, void const * src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
The hardware may restrict access width or expose different behavior depending on the access width. This function only perform 64-bit memory accesses.
Parameters
[out] dst - the destination memory region
[in] src - the source memory region
[in] len - the number of bytes to copy
Returns
- dst or NULL on error
{
    uint64_t * plDst = (uint64_t *) dst;
    uint64_t const * plSrc = (uint64_t const *) src;
    while (len >= 8) {
        *plDst++ = *plSrc++;
        len -= 8;
    }
    char * pcDst = (char *) plDst;
    char const * pcSrc = (char const *) plSrc;
    while (len--) {
        *pcDst++ = *pcSrc++;
    }
    return (dst);
}
pcilib_memcpy8()
void * pcilib_memcpy8 (void * dst, void const * src, size_t len)
The collection of slow memcpy functions to move the data between BAR and system memory.
The hardware may restrict access width or expose different behavior depending on the access width. This function only perform 8-bit memory accesses.
Parameters
[out] dst - the destination memory region
[in] src - the source memory region
[in] len - the number of bytes to copy
Returns
- dst or NULL on error
{
    int i;
    for (i = 0; i < len; i++) ((char*)dst)[i] = ((char*)src)[i];
    return dst;
}