pcilib: model.c File Reference
model.c File Reference
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>
#include "pcilib.h"
#include "pci.h"
#include "tools.h"
#include "error.h"
Functions
const pcilib_model_description_t * pcilib_get_model_description (pcilib_t *ctx)
Function Documentation
pcilib_get_model_description()
const pcilib_model_description_t * pcilib_get_model_description (pcilib_t * ctx)
{
    return &ctx->model_info;
}
References pcilib_s::model_info.
Referenced by pcilib_close(), pcilib_configure_autostop(), pcilib_configure_preprocessing_threads(), pcilib_configure_rawdata_callback(), pcilib_copy_data(), pcilib_copy_data_with_argument(), pcilib_find_event(), pcilib_find_event_data_type(), pcilib_find_register(), pcilib_find_register_bank(), pcilib_get_data(), pcilib_get_data_with_argument(), pcilib_get_next_event(), pcilib_init_dma(), pcilib_init_event_engine(), pcilib_map_register_space(), pcilib_read_register_by_id(), pcilib_reset(), pcilib_return_data(), pcilib_start(), pcilib_stop(), pcilib_stream(), pcilib_trigger(), and pcilib_write_register_by_id().