pcilib: pci.h File Reference
pci.h File Reference
#include <uthash.h>
#include "linux-3.10.h"
#include "driver/ioctl.h"
#include "timing.h"
#include "cpu.h"
#include "bar.h"
#include "pcilib.h"
#include "register.h"
#include "kmem.h"
#include "irq.h"
#include "dma.h"
#include "event.h"
#include "model.h"
#include "export.h"
#include "locking.h"
#include "xml.h"
#include "py.h"
#include "view.h"
#include "memcpy.h"
Data Structures
struct pcilib_pcie_link_info_t
struct pcilib_s
Macros
#define PCILIB_DEFAULT_CPU_COUNT 2
#define PCILIB_EVENT_TIMEOUT 1000000
us
#define PCILIB_TRIGGER_TIMEOUT 100000
us
#define PCILIB_DMA_TIMEOUT 10000
us
#define PCILIB_DMA_SKIP_TIMEOUT 1000000
us
#define PCILIB_MAX_BARS 6
this is defined by PCI specification
#define PCILIB_DEFAULT_REGISTER_SPACE 1024
number of registers to allocate on init
#define PCILIB_DEFAULT_VIEW_SPACE 128
number of views to allocate on init
#define PCILIB_DEFAULT_UNIT_SPACE 128
number of units to allocate on init
#define PCILIB_MAX_REGISTER_BANKS 32
maximum number of register banks to allocate space for
#define PCILIB_MAX_REGISTER_RANGES 32
maximum number of register ranges to allocate space for
#define PCILIB_MAX_REGISTER_PROTOCOLS 32
maximum number of register protocols to support
#define PCILIB_MAX_DMA_ENGINES 32
maximum number of supported DMA engines
Functions
pcilib_context_t * pcilib_get_implementation_context (pcilib_t *ctx)
const pcilib_driver_version_t * pcilib_get_driver_version (pcilib_t *ctx)
const pcilib_board_info_t * pcilib_get_board_info (pcilib_t *ctx)
const pcilib_pcie_link_info_t * pcilib_get_pcie_link_info (pcilib_t *ctx)
int pcilib_get_device_state (pcilib_t *ctx, pcilib_device_state_t *state)
int pcilib_map_register_space (pcilib_t *ctx)
int pcilib_map_data_space (pcilib_t *ctx, uintptr_t addr)
int pcilib_set_dma_mask (pcilib_t *ctx, int mask)
int pcilib_set_mps (pcilib_t *ctx, int mps)
Macro Definition Documentation
PCILIB_DEFAULT_CPU_COUNT
#define PCILIB_DEFAULT_CPU_COUNT 2
PCILIB_DEFAULT_REGISTER_SPACE
#define PCILIB_DEFAULT_REGISTER_SPACE 1024
number of registers to allocate on init
PCILIB_DEFAULT_UNIT_SPACE
#define PCILIB_DEFAULT_UNIT_SPACE 128
number of units to allocate on init
PCILIB_DEFAULT_VIEW_SPACE
#define PCILIB_DEFAULT_VIEW_SPACE 128
number of views to allocate on init
PCILIB_DMA_SKIP_TIMEOUT
#define PCILIB_DMA_SKIP_TIMEOUT 1000000
us
PCILIB_DMA_TIMEOUT
#define PCILIB_DMA_TIMEOUT 10000
us
PCILIB_EVENT_TIMEOUT
#define PCILIB_EVENT_TIMEOUT 1000000
us
PCILIB_MAX_BARS
#define PCILIB_MAX_BARS 6
this is defined by PCI specification
PCILIB_MAX_DMA_ENGINES
#define PCILIB_MAX_DMA_ENGINES 32
maximum number of supported DMA engines
PCILIB_MAX_REGISTER_BANKS
#define PCILIB_MAX_REGISTER_BANKS 32
maximum number of register banks to allocate space for
PCILIB_MAX_REGISTER_PROTOCOLS
#define PCILIB_MAX_REGISTER_PROTOCOLS 32
maximum number of register protocols to support
PCILIB_MAX_REGISTER_RANGES
#define PCILIB_MAX_REGISTER_RANGES 32
maximum number of register ranges to allocate space for
PCILIB_TRIGGER_TIMEOUT
#define PCILIB_TRIGGER_TIMEOUT 100000
us
Function Documentation
pcilib_get_board_info()
const pcilib_board_info_t * pcilib_get_board_info (pcilib_t * ctx)
{
    int ret;
    if (!ctx->board_info_ready) {
        ret = ioctl( ctx->handle, PCIDRIVER_IOC_PCI_INFO, &ctx->board_info );
        if (ret) {
            pcilib_error("PCIDRIVER_IOC_PCI_INFO ioctl have failed");
            return NULL;
        }
        ctx->board_info_ready = 1;
    }
    return &ctx->board_info;
}
References pcilib_s::board_info, pcilib_s::board_info_ready, pcilib_s::handle, and pcilib_error.
Referenced by pcilib_detect_address(), pcilib_detect_bar(), pcilib_get_bar_list(), pcilib_map_bar(), pcilib_map_data_space(), pcilib_open(), and pcilib_unmap_bar().
pcilib_get_device_state()
int pcilib_get_device_state (pcilib_t * ctx, pcilib_device_state_t * state)
{
    int ret = ioctl( ctx->handle, PCIDRIVER_IOC_DEVICE_STATE, state);
    if (ret < 0) {
        pcilib_error("PCIDRIVER_IOC_DEVICE_STATE ioctl have failed");
        return PCILIB_ERROR_FAILED;
    }
    return 0;
}
References pcilib_s::handle, pcilib_error, and PCILIB_ERROR_FAILED.
pcilib_get_driver_version()
const pcilib_driver_version_t * pcilib_get_driver_version (pcilib_t * ctx)
{
    int ret;
    if (!ctx->driver_version.version) {
        ret = ioctl( ctx->handle, PCIDRIVER_IOC_VERSION, &ctx->driver_version );
        if (ret) {
            pcilib_error("PCIDRIVER_IOC_DRIVER_VERSION ioctl have failed");
            return NULL;
        }
        if (ctx->driver_version.interface != PCIDRIVER_INTERFACE_VERSION) {
            pcilib_error("Using pcilib (version: %u.%u.%u, driver interface: 0x%lx) with incompatible driver (version: %u.%u.%u, interface: 0x%lx)",
                PCILIB_VERSION_GET_MAJOR(PCILIB_VERSION),
                PCILIB_VERSION_GET_MINOR(PCILIB_VERSION),
                PCILIB_VERSION_GET_MICRO(PCILIB_VERSION),
                PCIDRIVER_INTERFACE_VERSION,
                PCILIB_VERSION_GET_MAJOR(ctx->driver_version.version),
                PCILIB_VERSION_GET_MINOR(ctx->driver_version.version),
                PCILIB_VERSION_GET_MICRO(ctx->driver_version.version),
                ctx->driver_version.interface
            );
            return NULL;
        }
    }
    return &ctx->driver_version;
}
References pcilib_s::driver_version, pcilib_s::handle, and pcilib_error.
Referenced by pcilib_open().
pcilib_get_implementation_context()
pcilib_context_t * pcilib_get_implementation_context (pcilib_t * ctx)
{
    return ctx->event_ctx;
}
References pcilib_s::event_ctx.
pcilib_get_pcie_link_info()
const pcilib_pcie_link_info_t * pcilib_get_pcie_link_info (pcilib_t * ctx)
{
    int err;
    const uint32_t *cap;
    err = pcilib_update_pci_configuration_space(ctx);
    if (err) {
        pcilib_error("Error (%i) updating PCI configuration space", err);
        return NULL;
    }
    cap = pcilib_get_pcie_capabilities(ctx);
    if (!cap) return NULL;
        // Generally speaking this can be updated during the application life time
    ctx->link_info.max_payload = (cap[1] & 0x07) + 7;
    ctx->link_info.payload = ((cap[2] >> 5) & 0x07) + 7;
    ctx->link_info.link_speed = (cap[3]&0xF);
    ctx->link_info.link_width = (cap[3]&0x3F0) >> 4;
    ctx->link_info.max_link_speed = (cap[4]&0xF0000) >> 16;
    ctx->link_info.max_link_width = (cap[4]&0x3F00000) >> 20;
    return &ctx->link_info;
}
References pcilib_s::link_info, pcilib_pcie_link_info_t::link_speed, pcilib_pcie_link_info_t::link_width, pcilib_pcie_link_info_t::max_link_speed, pcilib_pcie_link_info_t::max_link_width, pcilib_pcie_link_info_t::max_payload, pcilib_pcie_link_info_t::payload, and pcilib_error.
pcilib_map_data_space()
int pcilib_map_data_space (pcilib_t * ctx, uintptr_t addr)
{
    int err;
    pcilib_bar_t i;
    if (!ctx->data_bar_mapped) {
        const pcilib_board_info_t *board_info = pcilib_get_board_info(ctx);
        if (!board_info) return PCILIB_ERROR_FAILED;
        err = pcilib_map_register_space(ctx);
        if (err) {
            pcilib_error("Error mapping register space");
            return err;
        }
        int data_bar = -1;
        for (i = 0; i < PCILIB_MAX_BARS; i++) {
            if ((ctx->bar_space[i])||(!board_info->bar_length[i])) continue;
            if (addr) {
                if (board_info->bar_start[i] == addr) {
                    data_bar = i;
                    break;
                }
            } else {
                if (data_bar >= 0) {
                    data_bar = -1;
                    break;
                }
                data_bar = i;
            }
        }
        if (data_bar < 0) {
            if (addr) pcilib_error("Unable to find the specified data space (%lx)", addr);
            else pcilib_error("Unable to find the data space");
            return PCILIB_ERROR_NOTFOUND;
        }
        ctx->data_bar = data_bar;
        if (!ctx->bar_space[data_bar]) {
            char *data_space = pcilib_map_bar(ctx, data_bar);
            if (data_space) ctx->bar_space[data_bar] = data_space;
            else {
                pcilib_error("Unable to map the data space");
                return PCILIB_ERROR_FAILED;
            }
        }
        ctx->data_bar_mapped = 0;
    }
    return 0;
}
References pcilib_s::bar_space, pcilib_s::data_bar, pcilib_s::data_bar_mapped, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_NOTFOUND, pcilib_get_board_info(), pcilib_map_bar(), pcilib_map_register_space(), and PCILIB_MAX_BARS.
Referenced by pcilib_resolve_data_space().
pcilib_map_register_space()
int pcilib_map_register_space (pcilib_t * ctx)
{
    int err;
    pcilib_register_bank_t i;
    if (!ctx->reg_bar_mapped)  {
        const pcilib_model_description_t *model_info = pcilib_get_model_description(ctx);
        const pcilib_register_bank_description_t *banks = model_info->banks;
        for (i = 0; ((banks)&&(banks[i].access)); i++) {
//          uint32_t buf[2];
            void *reg_space;
            pcilib_bar_t bar = banks[i].bar;
            if (bar == PCILIB_BAR_NOBAR)
                continue;
            if (bar == PCILIB_BAR_DETECT) {
                uintptr_t addr = banks[0].read_addr;
                err = pcilib_detect_address(ctx, &bar, &addr, 1);
                if (err) return err;
                if (!ctx->bar_space[bar]) {
                    reg_space = pcilib_map_bar(ctx, bar);
//                  pcilib_memcpy(&buf, reg_space, 8);
                    if (reg_space) {
                        ctx->bar_space[bar] = reg_space;
                    } else {
                        return PCILIB_ERROR_FAILED;
                    }
                }
            } else if (!ctx->bar_space[bar]) {
                reg_space = pcilib_map_bar(ctx, bar);
                if (reg_space) {
                    ctx->bar_space[bar] = reg_space;
                } else {
                    return PCILIB_ERROR_FAILED;
                }
//              pcilib_memcpy(&buf, reg_space, 8);
            }
            if (!i) ctx->reg_bar = bar;
        }
        ctx->reg_bar_mapped = 1;
    }
    return 0;
}
References pcilib_model_description_t::banks, pcilib_register_bank_description_t::bar, pcilib_s::bar_space, PCILIB_BAR_DETECT, PCILIB_BAR_NOBAR, pcilib_detect_address(), PCILIB_ERROR_FAILED, pcilib_get_model_description(), pcilib_map_bar(), pcilib_register_bank_description_t::read_addr, pcilib_s::reg_bar, and pcilib_s::reg_bar_mapped.
Referenced by pcilib_init_register_banks(), and pcilib_map_data_space().
pcilib_set_dma_mask()
int pcilib_set_dma_mask (pcilib_t * ctx, int mask)
{
    if (ioctl(ctx->handle, PCIDRIVER_IOC_DMA_MASK, mask) < 0)
        return PCILIB_ERROR_FAILED;
    return 0;
}
References pcilib_s::handle, and PCILIB_ERROR_FAILED.
pcilib_set_mps()
int pcilib_set_mps (pcilib_t * ctx, int mps)
{
    if (ioctl(ctx->handle, PCIDRIVER_IOC_MPS, mps) < 0)
        return PCILIB_ERROR_FAILED;
    return 0;
}
References pcilib_s::handle, and PCILIB_ERROR_FAILED.