pcilib: pci.c File Reference
pci.c File Reference
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>
#include <stdint.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <arpa/inet.h>
#include <errno.h>
#include <assert.h>
#include "pcilib.h"
#include "pci.h"
#include "tools.h"
#include "error.h"
#include "model.h"
#include "plugin.h"
#include "bar.h"
#include "xml.h"
#include "locking.h"
Macros
#define _XOPEN_SOURCE 700
#define _BSD_SOURCE
#define _DEFAULT_SOURCE
#define _POSIX_C_SOURCE 200809L
Functions
pcilib_t * pcilib_open (const char *device, const char *model)
Initializes pcilib context, detects model configuration, and populates model-specific registers.
const pcilib_driver_version_t * pcilib_get_driver_version (pcilib_t *ctx)
const pcilib_board_info_t * pcilib_get_board_info (pcilib_t *ctx)
pcilib_context_t * pcilib_get_implementation_context (pcilib_t *ctx)
void pcilib_close (pcilib_t *ctx)
Destroy pcilib context and all memory associated with it.
const pcilib_pcie_link_info_t * pcilib_get_pcie_link_info (pcilib_t *ctx)
int pcilib_get_device_state (pcilib_t *ctx, pcilib_device_state_t *state)
int pcilib_set_dma_mask (pcilib_t *ctx, int mask)
int pcilib_set_mps (pcilib_t *ctx, int mps)
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
Function Documentation
pcilib_get_board_info()
const pcilib_board_info_t * pcilib_get_board_info (pcilib_t * ctx)
{
    int ret;
    if (!ctx->board_info_ready) {
        ret = ioctl( ctx->handle, PCIDRIVER_IOC_PCI_INFO, &ctx->board_info );
        if (ret) {
            pcilib_error("PCIDRIVER_IOC_PCI_INFO ioctl have failed");
            return NULL;
        }
        ctx->board_info_ready = 1;
    }
    return &ctx->board_info;
}
References pcilib_s::board_info, pcilib_s::board_info_ready, pcilib_s::handle, and pcilib_error.
Referenced by pcilib_detect_address(), pcilib_detect_bar(), pcilib_get_bar_list(), pcilib_map_bar(), pcilib_map_data_space(), pcilib_open(), and pcilib_unmap_bar().
pcilib_get_device_state()
int pcilib_get_device_state (pcilib_t * ctx, pcilib_device_state_t * state)
{
    int ret = ioctl( ctx->handle, PCIDRIVER_IOC_DEVICE_STATE, state);
    if (ret < 0) {
        pcilib_error("PCIDRIVER_IOC_DEVICE_STATE ioctl have failed");
        return PCILIB_ERROR_FAILED;
    }
    return 0;
}
References pcilib_s::handle, pcilib_error, and PCILIB_ERROR_FAILED.
pcilib_get_driver_version()
const pcilib_driver_version_t * pcilib_get_driver_version (pcilib_t * ctx)
{
    int ret;
    if (!ctx->driver_version.version) {
        ret = ioctl( ctx->handle, PCIDRIVER_IOC_VERSION, &ctx->driver_version );
        if (ret) {
            pcilib_error("PCIDRIVER_IOC_DRIVER_VERSION ioctl have failed");
            return NULL;
        }
        if (ctx->driver_version.interface != PCIDRIVER_INTERFACE_VERSION) {
            pcilib_error("Using pcilib (version: %u.%u.%u, driver interface: 0x%lx) with incompatible driver (version: %u.%u.%u, interface: 0x%lx)",
                PCILIB_VERSION_GET_MAJOR(PCILIB_VERSION),
                PCILIB_VERSION_GET_MINOR(PCILIB_VERSION),
                PCILIB_VERSION_GET_MICRO(PCILIB_VERSION),
                PCIDRIVER_INTERFACE_VERSION,
                PCILIB_VERSION_GET_MAJOR(ctx->driver_version.version),
                PCILIB_VERSION_GET_MINOR(ctx->driver_version.version),
                PCILIB_VERSION_GET_MICRO(ctx->driver_version.version),
                ctx->driver_version.interface
            );
            return NULL;
        }
    }
    return &ctx->driver_version;
}
References pcilib_s::driver_version, pcilib_s::handle, and pcilib_error.
Referenced by pcilib_open().
pcilib_get_implementation_context()
pcilib_context_t * pcilib_get_implementation_context (pcilib_t * ctx)
{
    return ctx->event_ctx;
}
References pcilib_s::event_ctx.
pcilib_get_pcie_link_info()
const pcilib_pcie_link_info_t * pcilib_get_pcie_link_info (pcilib_t * ctx)
{
    int err;
    const uint32_t *cap;
    err = pcilib_update_pci_configuration_space(ctx);
    if (err) {
        pcilib_error("Error (%i) updating PCI configuration space", err);
        return NULL;
    }
    cap = pcilib_get_pcie_capabilities(ctx);
    if (!cap) return NULL;
        // Generally speaking this can be updated during the application life time
    ctx->link_info.max_payload = (cap[1] & 0x07) + 7;
    ctx->link_info.payload = ((cap[2] >> 5) & 0x07) + 7;
    ctx->link_info.link_speed = (cap[3]&0xF);
    ctx->link_info.link_width = (cap[3]&0x3F0) >> 4;
    ctx->link_info.max_link_speed = (cap[4]&0xF0000) >> 16;
    ctx->link_info.max_link_width = (cap[4]&0x3F00000) >> 20;
    return &ctx->link_info;
}
References pcilib_s::link_info, pcilib_pcie_link_info_t::link_speed, pcilib_pcie_link_info_t::link_width, pcilib_pcie_link_info_t::max_link_speed, pcilib_pcie_link_info_t::max_link_width, pcilib_pcie_link_info_t::max_payload, pcilib_pcie_link_info_t::payload, and pcilib_error.
pcilib_set_dma_mask()
int pcilib_set_dma_mask (pcilib_t * ctx, int mask)
{
    if (ioctl(ctx->handle, PCIDRIVER_IOC_DMA_MASK, mask) < 0)
        return PCILIB_ERROR_FAILED;
    return 0;
}
References pcilib_s::handle, and PCILIB_ERROR_FAILED.
pcilib_set_mps()
int pcilib_set_mps (pcilib_t * ctx, int mps)
{
    if (ioctl(ctx->handle, PCIDRIVER_IOC_MPS, mps) < 0)
        return PCILIB_ERROR_FAILED;
    return 0;
}
References pcilib_s::handle, and PCILIB_ERROR_FAILED.