pcilib: plugin.c File Reference
plugin.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <dirent.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include "model.h"
#include "error.h"
#include "pci.h"
#include "config.h"
Functions
void * pcilib_plugin_load (const char *name)
Loads the specified plugin The plugin symbols are loaded localy and not available for symbol resolution, but should be requested with pcilib_plugin_get_symbol() instead.
void pcilib_plugin_close (void *plug)
Cleans up the loaded plugin.
void * pcilib_plugin_get_symbol (void *plug, const char *symbol)
Resolves the specified symbol in the plugin.
const pcilib_model_description_t * pcilib_get_plugin_model (pcilib_t *pcilib, void *plug, unsigned short vendor_id, unsigned short device_id, const char *model)
Verifies if plugin can handle the hardware and requests appropriate model description.
const pcilib_model_description_t * pcilib_find_plugin_model (pcilib_t *pcilib, unsigned short vendor_id, unsigned short device_id, const char *model)
Finds the appropriate plugin and returns model description.
Function Documentation
pcilib_find_plugin_model()
const pcilib_model_description_t * pcilib_find_plugin_model (pcilib_t * ctx, unsigned short vendor_id, unsigned short device_id, const char * model)
Finds the appropriate plugin and returns model description.
The function sequentially loads plugins available in ::PCILIB_PLUGIN_DIR and checks if they support the installed hardware and requested model. If hardware is not supported, the plugin is immideately unloaded. On a first success the model description is returned to caller and no further plguins are loaded. If no suitable plugin is found, the NULL is returned.
If model is specified, first a plugin with the same name is loaded and check performed if it can handle the installed hardware. If not, we iterate over all available plugins as usual.
Parameters
[in,out] ctx - pcilib context
[in] vendor_id - Vendor ID reported by hardware
[in] device_id - Device ID reported by hardware
[in] model - the requested pcilib model or NULL for autodetction
Returns
- the appropriate model description or NULL if no plugin found able to handle the installed hardware or requested model
{
    DIR *dir;
    const char *path;
    struct dirent *entry;
    void *plugin;
    const pcilib_model_description_t *model_info = NULL;
    path = getenv("PCILIB_PLUGIN_DIR");
    if (!path) path = PCILIB_PLUGIN_DIR;
    if (model) {
        plugin = pcilib_plugin_load(model);
        if (plugin) {
            model_info = pcilib_get_plugin_model(pcilib, plugin, vendor_id, device_id, model);
            if (model_info) {
                pcilib->event_plugin = plugin;
                return model_info;
            }
            pcilib_plugin_close(plugin);
        }
    }
    dir = opendir(path);
    if (!dir) return NULL;
    while ((entry = readdir(dir))) {
        const char *suffix = strstr(entry->d_name, ".so");
        if ((!suffix)||(strlen(suffix) != 3)) continue;
        if ((model)&&(!strcmp(entry->d_name, model)))
            continue;
        plugin = pcilib_plugin_load(entry->d_name);
        if (plugin) {
            model_info = pcilib_get_plugin_model(pcilib, plugin, vendor_id, device_id, model);
            if (model_info) {
                pcilib->event_plugin = plugin;
                break;
            }
            pcilib_plugin_close(plugin);
        }
    }
    closedir(dir);
    return model_info;
}
References pcilib_s::event_plugin, pcilib_get_plugin_model(), pcilib_plugin_close(), and pcilib_plugin_load().
pcilib_get_plugin_model()
const pcilib_model_description_t * pcilib_get_plugin_model (pcilib_t * ctx, void * plug, unsigned short vendor_id, unsigned short device_id, const char * model)
Verifies if plugin can handle the hardware and requests appropriate model description.
Parameters
[in,out] ctx - pcilib context
[in] plug - plugin loaded with pcilib_plugin_load()
[in] vendor_id - Vendor ID reported by hardware
[in] device_id - Device ID reported by hardware
[in] model - the requested pcilib model or NULL for autodetction
Returns
- the appropriate model description or NULL if the plugin does not handle the installed hardware or requested model
{
    void *get_model;
    const pcilib_model_description_t *model_info;
    if (!plug) return NULL;
    get_model = dlsym(plug, "pcilib_get_event_model");
    if (!get_model) return NULL;
    model_info = ((const pcilib_model_description_t *(*)(pcilib_t *pcilib, unsigned short vendor_id, unsigned short device_id, const char *model))get_model)(pcilib, vendor_id, device_id, model);
    if (!model_info) return model_info;
    if ((PCILIB_VERSION_GET_MAJOR(model_info->interface_version) != PCILIB_VERSION_MAJOR)||(PCILIB_VERSION_GET_MINOR(model_info->interface_version) != PCILIB_VERSION_MINOR)) {
        printf("%u %u\n", model_info->interface_version, PCILIB_EVENT_INTERFACE_VERSION);
        pcilib_warning("Plugin %s exposes outdated interface version (%u.%u.%u), pcilib interface version is (%u.%u.%u)", model_info->name,
                PCILIB_VERSION_GET_MAJOR(model_info->interface_version),
                PCILIB_VERSION_GET_MINOR(model_info->interface_version),
                PCILIB_VERSION_GET_MICRO(model_info->interface_version),
                PCILIB_VERSION_GET_MAJOR(PCILIB_EVENT_INTERFACE_VERSION),
                PCILIB_VERSION_GET_MINOR(PCILIB_EVENT_INTERFACE_VERSION),
                PCILIB_VERSION_GET_MICRO(PCILIB_EVENT_INTERFACE_VERSION)
        );
        return NULL;
    }
    return model_info;
}
References pcilib_model_description_t::interface_version, pcilib_model_description_t::name, PCILIB_EVENT_INTERFACE_VERSION, and pcilib_warning.
Referenced by pcilib_find_plugin_model().
pcilib_plugin_close()
void pcilib_plugin_close (void * plug)
Cleans up the loaded plugin.
Parameters
[in] plug - plugin loaded with pcilib_plugin_load()
{
    if (plug)
        dlclose(plug);
}
Referenced by pcilib_close(), and pcilib_find_plugin_model().
pcilib_plugin_get_symbol()
void * pcilib_plugin_get_symbol (void * plug, const char * symbol)
Resolves the specified symbol in the plugin.
Parameters
[in] plug - plugin loaded with pcilib_plugin_load()
[in] symbol - name of the symbol
Returns
- pointer to the symbol or NULL if not found
{
    if ((!plug)||(!symbol)) return NULL;
    return dlsym(plug, symbol);
}
pcilib_plugin_load()
void * pcilib_plugin_load (const char * name)
Loads the specified plugin The plugin symbols are loaded localy and not available for symbol resolution, but should be requested with pcilib_plugin_get_symbol() instead.
Parameters
[in] name - the plugin name (with extension, but without path)
Returns
- dlopen'ed plugin or NULL in the case of error
{
    void *plug;
    char *fullname;
    const char *path;
    path = getenv("PCILIB_PLUGIN_DIR");
    if (!path) path = PCILIB_PLUGIN_DIR;
    fullname = malloc(strlen(path) + strlen(name) + 2);
    if (!fullname) return NULL;
    sprintf(fullname, "%s/%s", path, name);
    plug = dlopen(fullname, RTLD_LAZY|RTLD_LOCAL);
    free(fullname);
    return plug;
}
Referenced by pcilib_find_plugin_model().