pcilib: property.h File Reference
property.h File Reference
Functions
int pcilib_add_properties_from_registers (pcilib_t *ctx, size_t n, const pcilib_register_bank_t *banks, const pcilib_register_description_t *registers)
This is an internal function used to add property views for all model registers.
int pcilib_add_registers_from_properties (pcilib_t *ctx, size_t n, pcilib_view_context_t *const *view_ctx, pcilib_view_description_t *const *view)
This is an internal function used to add registers providing alternative access to values of the properties.
Function Documentation
pcilib_add_properties_from_registers()
int pcilib_add_properties_from_registers (pcilib_t * ctx, size_t n, const pcilib_register_bank_t * banks, const pcilib_register_description_t * registers)
This is an internal function used to add property views for all model registers.
It is automatically called from pcilib_add_registers and should not be called by the users. On error no new views are initalized.
Parameters
[in,out] ctx - pcilib context
[in] n - number of views to initialize.
[in] banks - array containing a bank id for each of the considered registers
[in] registers - register descriptions
Returns
- error or 0 on success
{
    int err;
    pcilib_register_t i;
    pcilib_view_t cur_view = ctx->num_views;
    if (!n)
        return PCILIB_ERROR_INVALID_ARGUMENT;
    for (i = 0; i < n; i++) {
        char *view_name;
        pcilib_access_mode_t mode = 0;
        pcilib_register_view_description_t v = {{0}};
        pcilib_register_bank_description_t *b = &ctx->banks[banks[i]];
        if (registers[i].type == PCILIB_REGISTER_PROPERTY) continue;
        view_name = malloc(strlen(registers[i].name) + strlen(b->name) + 13);
        if (!view_name) {
            pcilib_clean_views(ctx, cur_view);
            return PCILIB_ERROR_MEMORY;
        }
        sprintf(view_name, "/registers/%s/%s", b->name, registers[i].name);
        if ((registers[i].views)&&(registers[i].views[0].view)) {
            pcilib_view_t view = pcilib_find_view_by_name(ctx, registers[i].views[0].view);
            if (view == PCILIB_VIEW_INVALID) return PCILIB_ERROR_NOTFOUND;
            memcpy(&v, ctx->views[view], sizeof(pcilib_view_description_t));
            v.view = registers[i].views[0].name;
            if (ctx->views[view]->api->read_from_reg) mode |= PCILIB_ACCESS_R;
            if (ctx->views[view]->api->write_to_reg) mode |= PCILIB_ACCESS_W;
            mode &= ctx->views[view]->mode;
        } else {
            v.base.type = PCILIB_TYPE_LONG;
            mode = PCILIB_ACCESS_RW;
        }
        v.base.api = &pcilib_register_view_api;
        v.base.name = view_name;
        v.base.description = registers[i].description;
        v.base.mode = registers[i].mode&mode;
        v.base.flags |= PCILIB_VIEW_FLAG_PROPERTY;
        v.reg = registers[i].name;
        v.bank = b->name;
        err = pcilib_add_views(ctx, 1, (pcilib_view_description_t*)&v);
        if (err) {
            free(view_name);
            pcilib_clean_views(ctx, cur_view);
            return err;
        }
/*
        pcilib_view_context_t *view_ctx = pcilib_find_view_context_by_name(ctx, v.base.name);
        view_ctx->flags |= PCILIB_VIEW_FLAG_PROPERTY;
*/
    }
    return 0;
}
References pcilib_view_description_s::api, pcilib_s::banks, pcilib_register_description_t::description, pcilib_register_description_t::mode, pcilib_view_description_s::mode, pcilib_register_bank_description_t::name, pcilib_view_reference_t::name, pcilib_register_description_t::name, pcilib_s::num_views, PCILIB_ACCESS_R, PCILIB_ACCESS_RW, PCILIB_ACCESS_W, pcilib_add_views(), pcilib_clean_views(), PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_ERROR_MEMORY, PCILIB_ERROR_NOTFOUND, pcilib_find_view_by_name(), PCILIB_REGISTER_PROPERTY, PCILIB_TYPE_LONG, PCILIB_VIEW_FLAG_PROPERTY, PCILIB_VIEW_INVALID, pcilib_view_api_description_t::read_from_reg, pcilib_s::views, pcilib_register_description_t::views, and pcilib_view_api_description_t::write_to_reg.
Referenced by pcilib_add_registers().
pcilib_add_registers_from_properties()
int pcilib_add_registers_from_properties (pcilib_t * ctx, size_t n, pcilib_view_context_t *const * view_ctx, pcilib_view_description_t *const * view)
This is an internal function used to add registers providing alternative access to values of the properties.
To reduce number of required interfaces, some of the property views may be also mapped into the model as registers. The client application, then, is able to use either register or property APIs to access them. This is an internal function which processes the supplied views, finds which views have to be mapped in the register space, and finally pushes corresponding registers into the model. The function is automatically called from pcilib_add_views and should never be called by the user. On error no new registers are added.
Parameters
[in,out] ctx - pcilib context
[in] n - number of views to analyze.
[in] view_ctx - views to analyze
[in] view - array of pointers to corresponding view descriptions
Returns
- error or 0 on success
{
    int err;
    pcilib_view_t i;
    pcilib_register_t pos = 0;
    pcilib_register_description_t regs[n];
    int access;
    pcilib_register_bank_t bank;
    bank = pcilib_find_register_bank_by_addr(ctx, pcilib_property_register_bank.addr);
    if (bank == PCILIB_REGISTER_BANK_INVALID) {
        err = pcilib_add_register_banks(ctx, 0, 1, &pcilib_property_register_bank, &bank);
        if (err) {
            pcilib_error("Error (%i) adding register bank (%s)", err, pcilib_property_register_bank.name);
            return err;
        }
    }
    access = ctx->banks[bank].access / 8;
    for (i = 0; i < n; i++) {
        if ((v[i]->flags&PCILIB_VIEW_FLAG_REGISTER) == 0) continue;
        regs[pos++] = (pcilib_register_description_t){
            .addr = view_ctx[i]->view * access,
            .bits = 8 * sizeof(pcilib_register_value_t),
            .mode = v[i]->mode,
            .type = PCILIB_REGISTER_PROPERTY,
            .bank = PCILIB_REGISTER_BANK_PROPERTY,
            .name = (v[i]->regname?v[i]->regname:v[i]->name),
            .description = v[i]->description
        };
    }
    if (pos)
        return pcilib_add_registers(ctx, 0, pos, regs, NULL);
    return 0;
}
References pcilib_register_bank_description_t::access, pcilib_register_bank_description_t::addr, pcilib_register_description_t::addr, pcilib_s::banks, pcilib_view_description_s::description, pcilib_register_bank_description_t::name, pcilib_add_register_banks(), pcilib_add_registers(), pcilib_error, pcilib_find_register_bank_by_addr(), pcilib_property_register_bank, PCILIB_REGISTER_BANK_INVALID, PCILIB_REGISTER_BANK_PROPERTY, PCILIB_REGISTER_PROPERTY, PCILIB_VIEW_FLAG_REGISTER, and pcilib_view_context_s::view.
Referenced by pcilib_add_views_custom().