pcilib: py.h File Reference
py.h File Reference
#include <pcilib.h>
#include <pcilib/error.h>
Macros
#define pcilib_python_error(...) pcilib_log_python_error(__FILE__, __LINE__, PCILIB_LOG_DEFAULT, PCILIB_LOG_ERROR, __VA_ARGS__)
#define pcilib_python_warning(...) pcilib_log_python_error(__FILE__, __LINE__, PCILIB_LOG_DEFAULT, PCILIB_LOG_WARNING, __VA_ARGS__)
Typedefs
typedef struct pcilib_py_s pcilib_py_t
typedef void pcilib_py_object
Functions
void pcilib_log_python_error (const char *file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char *msg,...)
int pcilib_init_py (pcilib_t *ctx)
Initializes Python engine.
void pcilib_free_py (pcilib_t *ctx)
Cleans up memory used by various python structures and finalyzes python environment if pcilib is not started from python script.
int pcilib_py_add_script_dir (pcilib_t *ctx, const char *location)
Add an additional path to look for python scripts.
int pcilib_py_load_script (pcilib_t *ctx, const char *name)
Loads the specified python script.
int pcilib_py_get_transform_script_properties (pcilib_t *ctx, const char *name, pcilib_access_mode_t *mode)
Check if the specified script can be used as transform view and detects transform configuration.
pcilib_py_object * pcilib_get_value_as_pyobject (pcilib_t *ctx, pcilib_value_t *val, int *err)
Get the PyObject from the polymorphic type.
int pcilib_set_value_from_pyobject (pcilib_t *ctx, pcilib_value_t *val, pcilib_py_object *pyval)
Initializes the polymorphic value from PyObject.
int pcilib_py_eval_string (pcilib_t *ctx, const char *codestr, pcilib_value_t *val)
Evaluates the specified python code and returns result in val.
int pcilib_py_eval_func (pcilib_t *ctx, const char *script, const char *func, pcilib_value_t *val)
Execute the specified function in the Python script which was loaded with pcilib_py_load_script() call.
Macro Definition Documentation
pcilib_python_error
#define pcilib_python_error (...) pcilib_log_python_error(__FILE__, __LINE__, PCILIB_LOG_DEFAULT, PCILIB_LOG_ERROR, __VA_ARGS__)
pcilib_python_warning
#define pcilib_python_warning (...) pcilib_log_python_error(__FILE__, __LINE__, PCILIB_LOG_DEFAULT, PCILIB_LOG_WARNING, __VA_ARGS__)
Typedef Documentation
pcilib_py_object
typedef void pcilib_py_object
pcilib_py_t
typedef struct pcilib_py_s pcilib_py_t
Function Documentation
pcilib_free_py()
void pcilib_free_py (pcilib_t * ctx)
Cleans up memory used by various python structures and finalyzes python environment if pcilib is not started from python script.
Parameters
[in] ctx - the pcilib_t context
{
#ifdef HAVE_PYTHON
    if (ctx->py) {
        PyGILState_STATE gstate;
        gstate = PyGILState_Ensure();
        if (ctx->py->script_hash) {
            pcilib_script_t *script, *script_tmp;
            HASH_ITER(hh, ctx->py->script_hash, script, script_tmp) {
                Py_DECREF(script->module);
                HASH_DEL(ctx->py->script_hash, script);
                free(script);
            }
            ctx->py->script_hash = NULL;
        }
        PyGILState_Release(gstate);
#if PY_MAJOR_VERSION < 3
        pcilib_py_clean_default_modules(ctx);
#endif /* PY_MAJOR_VERSION < 3 */
        if (ctx->py->finalyze) {
#if PY_MAJOR_VERSION < 3
            Py_Finalize();
#else /* PY_MAJOR_VERSION < 3 */
//          PyThreadState_Delete(ctx->py->tstate);
                // singal python init thread to stop and wait it to finish
            pthread_cond_signal(&(ctx->py->cond));
            pthread_mutex_unlock(&(ctx->py->lock));
            pthread_join(ctx->py->pth, NULL);
                // destroy synchronization primitives
            pthread_cond_destroy(&(ctx->py->cond));
            pthread_mutex_destroy(&(ctx->py->lock));
#endif /* PY_MAJOR_VERSION < 3 */
        }
        free(ctx->py);
        ctx->py = NULL;
    }
#endif /* HAVE_PYTHON */
}
References pcilib_s::py.
Referenced by pcilib_close(), pcilib_init_py(), and pcilib_open().
pcilib_get_value_as_pyobject()
pcilib_py_object * pcilib_get_value_as_pyobject (pcilib_t * ctx, pcilib_value_t * val, int * err)
Get the PyObject from the polymorphic type.
The returned value should be cleaned with Py_XDECREF()
Parameters
[in] ctx - pcilib context
[in] val - initialized polymorphic value of arbitrary type
[out] err - error code or 0 on sccuess
Returns
- valid PyObject or NULL in the case of error
{
#ifdef HAVE_PYTHON
    int err = 0;
    PyObject *res = NULL;
    PyGILState_STATE gstate;
    long ival;
    double fval;
    if (!ctx->py) return NULL;
    gstate = PyGILState_Ensure();
    switch(val->type) {
     case PCILIB_TYPE_LONG:
        ival = pcilib_get_value_as_int(ctx, val, &err);
        if (!err) res = (PyObject*)PyLong_FromLong(ival);
        break;
     case PCILIB_TYPE_DOUBLE:
        fval = pcilib_get_value_as_float(ctx, val, &err);
        if (!err) res = (PyObject*)PyFloat_FromDouble(fval);
        break;
     default:
        PyGILState_Release(gstate);
        pcilib_error("Can't convert pcilib value of type (%lu) to PyObject", val->type);
        if (ret) *ret = PCILIB_ERROR_NOTSUPPORTED;
        return NULL;
    }
    PyGILState_Release(gstate);
    if (err) {
        if (ret) *ret = err;
        return NULL;
    } else if (!res) {
        if (ret) *ret = PCILIB_ERROR_MEMORY;
        return res;
    }
    if (ret) *ret = 0;
    return res;
#else /* HAVE_PYTHON */
    pcilib_error("Python is not supported");
    return NULL;
#endif /* HAVE_PYTHON */
}
References pcilib_error, PCILIB_ERROR_MEMORY, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_value_as_float(), pcilib_get_value_as_int(), PCILIB_TYPE_DOUBLE, PCILIB_TYPE_LONG, pcilib_s::py, and pcilib_value_t::type.
Referenced by pcilib_py_eval_func().
pcilib_init_py()
int pcilib_init_py (pcilib_t * ctx)
Initializes Python engine.
This function will return success if Python support is disabled. Only functions executing python call, like pcilib_py_eval_string(), return errors. Either way, no script directories are configured. The pcilib_add_script_dir() call is used for this purpose.
Parameters
[in,out] ctx - pcilib context
Returns
- error or 0 on success
{
#ifdef HAVE_PYTHON
    int err = 0;
    ctx->py = (pcilib_py_t*)malloc(sizeof(pcilib_py_t));
    if (!ctx->py) return PCILIB_ERROR_MEMORY;
    memset(ctx->py, 0, sizeof(pcilib_py_t));
    if (!Py_IsInitialized()) {
# if PY_MAJOR_VERSION < 3
        Py_Initialize();
            // Since python is being initializing from c programm, it needs to initialize threads to work properly with c threads
        PyEval_InitThreads();
        PyEval_ReleaseLock();
        err = pcilib_py_load_default_modules(ctx);
# else /* PY_MAJOR_VERSION < 3 */
        int err = pthread_mutex_init(&(ctx->py->lock), NULL);
        if (err) return PCILIB_ERROR_FAILED;
        err = pthread_cond_init(&(ctx->py->cond), NULL);
        if (err) {
            pthread_mutex_destroy(&(ctx->py->lock));
            return PCILIB_ERROR_FAILED;
        }
        err = pthread_mutex_lock(&(ctx->py->lock));
        if (err) {
            pthread_cond_destroy(&(ctx->py->cond));
            pthread_mutex_destroy(&(ctx->py->lock));
            return PCILIB_ERROR_FAILED;
        }
            // Create initalizer thread and wait until it releases the Lock
        err = pthread_create(&(ctx->py->pth), NULL, pcilib_py_run_init_thread, (void*)ctx);
        if (err) {
            pthread_mutex_unlock(&(ctx->py->lock));
            pthread_cond_destroy(&(ctx->py->cond));
            pthread_mutex_destroy(&(ctx->py->lock));
            return PCILIB_ERROR_FAILED;
        }
            // Wait until initialized and keep the lock afterwards until free executed
        pthread_cond_wait(&(ctx->py->cond), &(ctx->py->lock));
        err = ctx->py->status;
//      ctx->py->tstate =  PyThreadState_New(ctx->py->istate);
# endif /* PY_MAJOR_VERSION < 3 */
        ctx->py->finalyze = 1;
    } else {
        err = pcilib_py_load_default_modules(ctx);
    }
    if (err) {
        pcilib_free_py(ctx);
        return err;
    }
#endif /* HAVE_PYTHON */
    return 0;
}
References PCILIB_ERROR_FAILED, PCILIB_ERROR_MEMORY, pcilib_free_py(), and pcilib_s::py.
Referenced by pcilib_open().
pcilib_log_python_error()
void pcilib_log_python_error (const char * file, int line, pcilib_log_flags_t flags, pcilib_log_priority_t prio, const char * msg, ...)
{
    va_list va;
    const char *type = NULL;
    const char *val = NULL;
#ifdef HAVE_PYTHON
    PyGILState_STATE gstate;
    PyObject *pytype = NULL;
    PyObject *pyval = NULL;
    PyObject *pystr = NULL;
    PyObject *pytraceback = NULL;
    gstate = PyGILState_Ensure();
    if (PyErr_Occurred()) {
        PyErr_Fetch(&pytype, &pyval, &pytraceback);
        PyErr_NormalizeException(&pytype, &pyval, &pytraceback);
        if (pyval) pystr = PyObject_Str(pyval);
# if PY_MAJOR_VERSION >= 3
        if (pytype) {
            if (PyUnicode_Check(pytype))
                type = PyUnicode_AsUTF8(pytype);
            else
                type = PyExceptionClass_Name(pytype);
        }
        if (pystr) {
            val = PyUnicode_AsUTF8(pystr);
        }
# else /* PY_MAJOR_VERSION >= 3 */
        if (pytype) {
            if (PyString_Check(pytype))
                type = PyString_AsString(pytype);
            else
                type = PyExceptionClass_Name(pytype);
        }
        if (pystr) {
            val = PyString_AsString(pystr);
        }
# endif /*PY_MAJOR_VERSION >= 3*/
    }
    PyGILState_Release(gstate);
#endif /* HAVE_PYTHON */
    va_start(va, msg);
    if (type) {
        char *str;
        size_t len = 32;
        if (msg) len += strlen(msg);
        if (type) len += strlen(type);
        if (val) len += strlen(val);
        str = alloca(len * sizeof(char));
        if (str) {
            if (msg&&val)
                sprintf(str, "%s <%s: %s>", msg, type, val);
            else if (msg)
                sprintf(str, "%s <%s>", msg, type);
            else if (val)
                sprintf(str, "Python error %s: %s", type, val);
            else
                sprintf(str, "Python error %s", type);
            pcilib_log_vmessage(file, line, flags, prio, str, va);
        }
    } else  {
        pcilib_log_vmessage(file, line, flags, prio, msg, va);
    }
    va_end(va);
#ifdef HAVE_PYTHON
    if (pystr) Py_DECREF(pystr);
    if (pytype) Py_DECREF(pytype);
    if (pyval) Py_DECREF(pyval);
    if (pytraceback) Py_DECREF(pytraceback);
#endif /* HAVE_PYTHON */
}
References pcilib_log_vmessage().
pcilib_py_add_script_dir()
int pcilib_py_add_script_dir (pcilib_t * ctx, const char * location)
Add an additional path to look for python scripts.
The default location for python files is /usr/local/share/pcilib/models/model. This can be altered using CMake PCILIB_MODEL_DIR variable while building or using PCILIB_MODEL_DIR environmental variable dynamicly. The default location is added with location = NULL. Additional directories can be added as well either by specifying relative path from the default directory or absolute path in the system.
Parameters
[in,out] ctx - pcilib context
[in] location - NULL or path to additional scripts
Returns
- error or 0 on success
{
#ifdef HAVE_PYTHON
    int err = 0;
    PyObject *pypath, *pynewdir;
    PyObject *pydict, *pystr, *pyret = NULL;
    char *script_dir;
    if (!ctx->py) return 0;
    const char *model_dir = getenv("PCILIB_MODEL_DIR");
    if (!model_dir) model_dir = PCILIB_MODEL_DIR;
    if (!dir) dir = ctx->model;
    if (*dir == '/') {
        script_dir = (char*)dir;
    } else {
        script_dir = alloca(strlen(model_dir) + strlen(dir) + 2);
        if (!script_dir) return PCILIB_ERROR_MEMORY;
        sprintf(script_dir, "%s/%s", model_dir, dir);
    }
    PyGILState_STATE gstate = PyGILState_Ensure();
    pypath = PySys_GetObject("path");
    if (!pypath) {
        PyGILState_Release(gstate);
        pcilib_python_warning("Can't get python path");
        return PCILIB_ERROR_FAILED;
    }
    pynewdir = PyUnicode_FromString(script_dir);
    if (!pynewdir) {
        PyGILState_Release(gstate);
        pcilib_python_warning("Can't create python string");
        return PCILIB_ERROR_MEMORY;
    }
    // Checking if the directory already in the path?
    pydict = PyDict_New();
    if (pydict) {
        pystr = PyUnicode_FromString("cur");
        if (pystr) {
            PyDict_SetItem(pydict, pystr, pynewdir);
            Py_DECREF(pystr);
        }
        pystr = PyUnicode_FromString("path");
        if (pystr) {
            PyDict_SetItem(pydict, pystr, pypath);
            Py_DECREF(pystr);
        }
        pyret = PyRun_String("cur in path", Py_eval_input, ctx->py->global_dict, pydict);
        Py_DECREF(pydict);
    }
    if ((pyret == Py_False)&&(PyList_Append(pypath, pynewdir) == -1))
        err = PCILIB_ERROR_FAILED;
    if (pyret) Py_DECREF(pyret);
    Py_DECREF(pynewdir);
    PyGILState_Release(gstate);
    if (err) {
        pcilib_python_warning("Can't add directory (%s) to python path", script_dir);
        return err;
    }
#endif /* HAVE_PYTHON */
    return 0;
}
References pcilib_s::model, PCILIB_ERROR_FAILED, PCILIB_ERROR_MEMORY, pcilib_python_warning, and pcilib_s::py.
Referenced by pcilib_open().
pcilib_py_eval_func()
int pcilib_py_eval_func (pcilib_t * ctx, const char * script, const char * func, pcilib_value_t * val)
Execute the specified function in the Python script which was loaded with pcilib_py_load_script() call.
The function is expected to accept two paramters. The first parameter is pcipywrap context and the val is passed as the second parameter. The return value of the script will be returned in the val as well. If function returns Py_None, the value of val will be unchanged.
Parameters
[in,out] ctx - pcilib context
[in] script - script name
[in] func - function name
[in,out] val - Should contain the value of second parameter of the function before call and on successful return will contain the returned value
Returns
- error or 0 on success
{
#ifdef HAVE_PYTHON
    int err = 0;
    PyObject *pyfunc;
    PyObject *pyval = NULL, *pyret;
    pcilib_script_t *module = NULL;
    if (!ctx->py) return PCILIB_ERROR_NOTINITIALIZED;
    HASH_FIND_STR(ctx->py->script_hash, script_name, module);
    if (!module) {
        pcilib_error("Script (%s) is not loaded", script_name);
        return PCILIB_ERROR_NOTFOUND;
    }
    if (val) {
        pyval = pcilib_get_value_as_pyobject(ctx, val, &err);
        if (err) return err;
    }
    PyGILState_STATE gstate = PyGILState_Ensure();
    pyfunc = PyUnicode_FromString(func_name);
    if (!pyfunc) {
        if (pyval) Py_DECREF(pyval);
        PyGILState_Release(gstate);
        return PCILIB_ERROR_MEMORY;
    }
    pyret = PyObject_CallMethodObjArgs(module->module, pyfunc, ctx->py->pcilib_pywrap, pyval, NULL);
    Py_DECREF(pyfunc);
    Py_DECREF(pyval);
    if (!pyret) {
        PyGILState_Release(gstate);
        pcilib_python_error("Error executing function (%s) of python script (%s)", func_name, script_name);
        return PCILIB_ERROR_FAILED;
    }
    if ((val)&&(pyret != Py_None))
        err = pcilib_set_value_from_pyobject(ctx, val, pyret);
    Py_DECREF(pyret);
    PyGILState_Release(gstate);
    return err;
#else /* HAVE_PYTHON */
    pcilib_error("Python is not supported");
    return PCILIB_ERROR_NOTSUPPORTED;
#endif /* HAVE_PYTHON */
}
References pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_MEMORY, PCILIB_ERROR_NOTFOUND, PCILIB_ERROR_NOTINITIALIZED, PCILIB_ERROR_NOTSUPPORTED, pcilib_get_value_as_pyobject(), pcilib_python_error, pcilib_set_value_from_pyobject(), and pcilib_s::py.
pcilib_py_eval_string()
int pcilib_py_eval_string (pcilib_t * ctx, const char * codestr, pcilib_value_t * val)
Evaluates the specified python code and returns result in val.
The python code may include special variables which will be substituted by pcitool before executing Python interpreter $value - will be replaced by the current value of the val parameter $reg - will be replaced by the current value of the specified register reg ${/prop/temp} - will be replaced by the current value of the specified property /prop/temp ${/prop/temp:C} - will be replaced by the current value of the specified property /prop/temp in the given units
Parameters
[in,out] ctx - pcilib context
[in] codestr - python code to evaluate
[in,out] val - Should contain the value which will be substituted in place of $value and on successful execution will contain the computed value
Returns
- error or 0 on success
{
#ifdef HAVE_PYTHON
    int err;
    PyGILState_STATE gstate;
    char *code;
    PyObject* obj;
    if (!ctx->py) return PCILIB_ERROR_NOTINITIALIZED;
    code = pcilib_py_parse_string(ctx, codestr, value);
    if (!code) {
        pcilib_error("Failed to parse registers in the code: %s", codestr);
        return PCILIB_ERROR_FAILED;
    }
    gstate = PyGILState_Ensure();
    obj = PyRun_String(code, Py_eval_input, ctx->py->global_dict, ctx->py->global_dict);
    PyGILState_Release(gstate);
    if (!obj) {
        pcilib_error("Failed to run the Python code: %s", code);
        free(code);
        return PCILIB_ERROR_FAILED;
    }
    pcilib_debug(VIEWS, "Evaluating a Python string \'%s\' to %lf=\'%s\'", codestr, PyFloat_AsDouble(obj), code);
    err = pcilib_set_value_from_float(ctx, value, PyFloat_AsDouble(obj));
    Py_DECREF(obj);
    free(code);
    return err;
#else /* HAVE_PYTHON */
        pcilib_error("Current build not support python.");
    return PCILIB_ERROR_NOTAVAILABLE;
#endif /* HAVE_PYTHON */
}
References pcilib_debug, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_NOTAVAILABLE, PCILIB_ERROR_NOTINITIALIZED, pcilib_set_value_from_float(), and pcilib_s::py.
Referenced by pcilib_transform_unit().
pcilib_py_get_transform_script_properties()
int pcilib_py_get_transform_script_properties (pcilib_t * ctx, const char * name, pcilib_access_mode_t * mode)
Check if the specified script can be used as transform view and detects transform configuration.
Parameters
[in,out] ctx - pcilib context
[in] name - script name
[out] mode - supported access mode (read/write/read-write)
Returns
- error or 0 on success
{
    pcilib_access_mode_t mode = 0;
#ifdef HAVE_PYTHON
    PyObject *dict;
    PyObject *pystr;
    pcilib_script_t *module;
    PyGILState_STATE gstate;
    if (!ctx->py) {
        if (mode_ret) *mode_ret = mode;
        return 0;
    }
    HASH_FIND_STR(ctx->py->script_hash, script_name, module);
    if(!module) {
        pcilib_error("Script (%s) is not loaded yet", script_name);
        return PCILIB_ERROR_NOTFOUND;
    }
    gstate = PyGILState_Ensure();
    dict = PyModule_GetDict(module->module);
    if (!dict) {
        PyGILState_Release(gstate);
        pcilib_python_error("Error getting dictionary for script (%s)", script_name);
        return PCILIB_ERROR_FAILED;
    }
    pystr = PyUnicode_FromString("read_from_register");
    if (pystr) {
        if (PyDict_Contains(dict, pystr)) mode |= PCILIB_ACCESS_R;
        Py_DECREF(pystr);
    }
    pystr = PyUnicode_FromString("write_to_register");
    if (pystr) {
        if (PyDict_Contains(dict, pystr)) mode |= PCILIB_ACCESS_W;
        Py_DECREF(pystr);
    }
    PyGILState_Release(gstate);
#endif /* HAVE_PYTHON */
//    pcilib_py_load_default_modules(py->ctx);
    if (mode_ret) *mode_ret = mode;
    return 0;
}
References PCILIB_ACCESS_R, PCILIB_ACCESS_W, pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_NOTFOUND, pcilib_python_error, and pcilib_s::py.
pcilib_py_load_script()
int pcilib_py_load_script (pcilib_t * ctx, const char * name)
Loads the specified python script.
Once loaded the script is available until pcilib context is destryoed.
Parameters
[in,out] ctx - pcilib context
[in] name - script name, the passed variable is referenced and, hence, should have static duration
Returns
- error or 0 on success
{
#ifdef HAVE_PYTHON
    PyObject* pymodule;
    pcilib_script_t *module = NULL;
    PyGILState_STATE gstate;
    if (!ctx->py) return 0;
    char *module_name = strdupa(script_name);
    if (!module_name) return PCILIB_ERROR_MEMORY;
    char *py = strrchr(module_name, '.');
    if ((!py)||(strcasecmp(py, ".py"))) {
        pcilib_error("Invalid script name (%s) is specified", script_name);
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    *py = 0;
    HASH_FIND_STR(ctx->py->script_hash, script_name, module);
    if (module) return 0;
    gstate = PyGILState_Ensure();
    pymodule = PyImport_ImportModule(module_name);
    if (!pymodule) {
        PyGILState_Release(gstate);
        pcilib_python_error("Error importing script (%s)", script_name);
        return PCILIB_ERROR_FAILED;
    }
    module = (pcilib_script_t*)malloc(sizeof(pcilib_script_t));
    if (!module) {
        Py_DECREF(pymodule);
        PyGILState_Release(gstate);
        return PCILIB_ERROR_MEMORY;
    }
    PyGILState_Release(gstate);
    module->module = pymodule;
    module->name = script_name;
    HASH_ADD_KEYPTR(hh, ctx->py->script_hash, module->name, strlen(module->name), module);
#endif /* HAVE_PYTHON */
    return 0;
}
References pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_ERROR_MEMORY, pcilib_python_error, and pcilib_s::py.
pcilib_set_value_from_pyobject()
int pcilib_set_value_from_pyobject (pcilib_t * ctx, pcilib_value_t * val, pcilib_py_object * pyval)
Initializes the polymorphic value from PyObject.
If val already contains the value, cleans it first. Therefore, before first usage the value should be always initialized to 0.
Parameters
[in] ctx - pcilib context
[in,out] val - initialized polymorphic value
[in] pyval - valid PyObject* containing PyInt, PyFloat, or PyString
Returns
- 0 on success or memory error
{
#ifdef HAVE_PYTHON
    int err = 0;
    PyObject *pyval = (PyObject*)pval;
    PyGILState_STATE gstate;
    if (!ctx->py) return PCILIB_ERROR_NOTINITIALIZED;
    gstate = PyGILState_Ensure();
    if (PyLong_Check(pyval)) {
        err = pcilib_set_value_from_int(ctx, val, PyLong_AsLong(pyval));
    } else if (PyFloat_Check(pyval)) {
        err = pcilib_set_value_from_float(ctx, val, PyFloat_AsDouble(pyval));
#if PY_MAJOR_VERSION < 3
    } else if (PyInt_Check(pyval)) {
        err = pcilib_set_value_from_int(ctx, val, PyInt_AsLong(pyval));
    } else if (PyString_Check(pyval)) {
        err = pcilib_set_value_from_string(ctx, val, PyString_AsString(pyval));
    } else if (PyUnicode_Check(pyval)) {
        PyObject *buf = PyUnicode_AsASCIIString(pyval);
        if (buf) {
            err = pcilib_set_value_from_string(ctx, val, PyString_AsString(buf));
            Py_DecRef(buf);
        } else {
            err = PCILIB_ERROR_FAILED;
        }
#else /* PY_MAJOR_VERSION < 3 */
    } else if (PyUnicode_Check(pyval)) {
        err = pcilib_set_value_from_string(ctx, val, PyUnicode_AsUTF8(pyval));
#endif /* PY_MAJOR_VERSION < 3 */
    } else {
        PyGILState_Release(gstate);
        pcilib_error("Can't convert PyObject to polymorphic pcilib value");
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    PyGILState_Release(gstate);
    return err;
#else /* HAVE_PYTHON */
    pcilib_error("Python is not supported");
    return PCILIB_ERROR_NOTSUPPORTED;
#endif /* HAVE_PYTHON */
}
References pcilib_error, PCILIB_ERROR_FAILED, PCILIB_ERROR_NOTINITIALIZED, PCILIB_ERROR_NOTSUPPORTED, pcilib_set_value_from_float(), pcilib_set_value_from_int(), pcilib_set_value_from_string(), and pcilib_s::py.
Referenced by pcilib_py_eval_func().