pcilib: register.h File Reference
register.h File Reference
#include <uthash.h>
#include <pcilib.h>
#include <pcilib/bank.h>
Data Structures
struct pcilib_view_reference_t
struct pcilib_register_description_t
struct pcilib_register_context_t
Macros
#define PCILIB_REGISTER_NO_BITS 0
#define PCILIB_REGISTER_ALL_BITS ((pcilib_register_value_t)-1)
Enumerations
enum pcilib_register_type_t { PCILIB_REGISTER_STANDARD = 0 , PCILIB_REGISTER_FIFO , PCILIB_REGISTER_BITS , PCILIB_REGISTER_PROPERTY }
Functions
int pcilib_add_registers (pcilib_t *ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_description_t *registers, pcilib_register_t *ids)
Use this function to add new registers into the model.
void pcilib_clean_registers (pcilib_t *ctx, pcilib_register_t start)
Destroys data associated with registers.
Macro Definition Documentation
PCILIB_REGISTER_ALL_BITS
#define PCILIB_REGISTER_ALL_BITS ((pcilib_register_value_t)-1)
PCILIB_REGISTER_NO_BITS
#define PCILIB_REGISTER_NO_BITS 0
Enumeration Type Documentation
pcilib_register_type_t
enum pcilib_register_type_t
Enumerator
PCILIB_REGISTER_STANDARD
Standard register.
PCILIB_REGISTER_FIFO
FIFO register.
PCILIB_REGISTER_BITS
Besides a big standard register, the register bit-fields may be described by bit registers.
PCILIB_REGISTER_PROPERTY
A special register bound to a property and gettings/setting it value through it.
             {
    PCILIB_REGISTER_STANDARD = 0,
    PCILIB_REGISTER_FIFO,
    PCILIB_REGISTER_BITS,
    PCILIB_REGISTER_PROPERTY
} pcilib_register_type_t;
Function Documentation
pcilib_add_registers()
int pcilib_add_registers (pcilib_t * ctx, pcilib_model_modification_flags_t flags, size_t n, const pcilib_register_description_t * registers, pcilib_register_t * ids)
Use this function to add new registers into the model.
Currently, it is considered a error to re-add already defined register. If it will turn out to be useful to redefine some registers from the model, it may change in the future. However, we should think how to treat bit-registers in this case. The function will copy the context of registers structure, but name, description, and other strings in the structure are considered to have static duration and will not be copied. On error no new registers are initalized.
Parameters
[in,out] ctx - pcilib context
[in] flags - not used now, but in future may instruct if existing registers should be reported as error (default), overriden or ignored
[in] n - number of registers to initialize. It is OK to pass 0 if registers array is NULL terminated (last member of the array have all members set to 0)
[in] registers - register descriptions
[out] ids - if specified will contain the ids of the newly registered and overriden registers
Returns
- error or 0 on success
{
        // DS: Overrride existing registers
        // Registers identified by addr + offset + size + type or name
    int err;
    size_t size;
    pcilib_register_t i;
    pcilib_register_description_t *regs;
    pcilib_register_context_t *reg_ctx;
    pcilib_register_bank_t bank = PCILIB_REGISTER_BANK_INVALID;
    pcilib_register_bank_addr_t bank_addr = (pcilib_register_bank_addr_t)-1;
    pcilib_register_bank_t *banks;
    if (!n) {
        for (n = 0; registers[n].bits; n++);
    }
    if ((ctx->num_reg + n + 1) > ctx->alloc_reg) {
        for (size = ctx->alloc_reg; size < 2 * (n + ctx->num_reg + 1); size<<=1);
        regs = (pcilib_register_description_t*)realloc(ctx->registers, size * sizeof(pcilib_register_description_t));
        if (!regs) return PCILIB_ERROR_MEMORY;
        ctx->registers = regs;
        ctx->model_info.registers = regs;
        reg_ctx = (pcilib_register_context_t*)realloc(ctx->registers, size * sizeof(pcilib_register_context_t));
        if (!reg_ctx) return PCILIB_ERROR_MEMORY;
        memset(reg_ctx + ctx->alloc_reg, 0, (size - ctx->alloc_reg) * sizeof(pcilib_register_context_t));
        if (ctx->register_ctx != reg_ctx) {
                // We need to recreate cache if context is moved...
            HASH_CLEAR(hh, ctx->reg_hash);
            for (i = 0; i < ctx->num_reg; i++) {
                pcilib_register_context_t *cur = &ctx->register_ctx[ctx->num_reg + i];
                HASH_ADD_KEYPTR(hh, ctx->reg_hash, cur->name, strlen(cur->name), cur);
            }
        }
        ctx->register_ctx = reg_ctx;
        ctx->alloc_reg = size;
    }
    banks = (pcilib_register_bank_t*)alloca(n * sizeof(pcilib_register_bank_t));
    if (!banks) return PCILIB_ERROR_MEMORY;
    for (i = 0; i < n; i++) {
        if (registers[i].bank != bank_addr) {
            bank_addr = registers[i].bank;
            bank = pcilib_find_register_bank_by_addr(ctx, bank_addr);
            if (bank == PCILIB_REGISTER_BANK_INVALID) {
                    // We need to add a bank first in this case
                if (registers[i].type == PCILIB_REGISTER_PROPERTY) {
                    err = pcilib_add_register_banks(ctx, 0, 1, &pcilib_property_register_bank, &bank);
                } else {
                    err = PCILIB_ERROR_INVALID_BANK;
                }
                if (err) {
                    pcilib_error("Invalid bank address (0x%lx) is specified for register %s", bank_addr, registers[i].name);
                    return err;
                }
            }
        }
/*
            // No hash so far, will iterate.
        pcilib_register_t reg = pcilib_find_register(ctx, ctx->banks[bank].name, registers[i].name);
        if (reg != PCILIB_REGISTER_INVALID) {
            pcilib_error("Register %s is already defined in the model", registers[i].name);
            return PCILIB_ERROR_EXIST;
        }
*/
        banks[i] = bank;
    }
    err = pcilib_add_properties_from_registers(ctx, n, banks, registers);
    if (err) return err;
    for (i = 0; i < n; i++) {
        pcilib_register_context_t *cur = &ctx->register_ctx[ctx->num_reg + i];
        cur->reg = ctx->num_reg + i;
        cur->name = registers[i].name;
        cur->bank = banks[i];
        HASH_ADD_KEYPTR(hh, ctx->reg_hash, cur->name, strlen(cur->name), cur);
    }
    memcpy(ctx->registers + ctx->num_reg, registers, n * sizeof(pcilib_register_description_t));
    memset(ctx->registers + ctx->num_reg + n, 0, sizeof(pcilib_register_description_t));
    if (ids) {
        size_t i;
        for (i = 0; i < n; i++)
            ids[i] = ctx->num_reg + i;
    }
    ctx->num_reg += n;
    return 0;
}
References pcilib_s::alloc_reg, pcilib_register_description_t::bank, pcilib_register_context_t::bank, pcilib_register_description_t::bits, pcilib_s::model_info, pcilib_register_description_t::name, pcilib_register_context_t::name, pcilib_s::num_reg, pcilib_add_properties_from_registers(), pcilib_add_register_banks(), pcilib_error, PCILIB_ERROR_INVALID_BANK, PCILIB_ERROR_MEMORY, pcilib_find_register_bank_by_addr(), pcilib_property_register_bank, PCILIB_REGISTER_BANK_INVALID, PCILIB_REGISTER_PROPERTY, pcilib_register_context_t::reg, pcilib_s::reg_hash, pcilib_s::register_ctx, pcilib_model_description_t::registers, and pcilib_s::registers.
Referenced by pcilib_add_registers_from_properties(), and pcilib_open().
pcilib_clean_registers()
void pcilib_clean_registers (pcilib_t * ctx, pcilib_register_t start)
Destroys data associated with registers.
This is an internal function and will be called during clean-up.
Parameters
[in,out] ctx - pcilib context
[in] start - specifies first register to clean (used to clean only part of the registers to keep the defined state if pcilib_add_registers has failed)
{
    pcilib_register_t reg;
    pcilib_register_context_t *reg_ctx, *tmp;
    if (start) {
        HASH_ITER(hh, ctx->reg_hash, reg_ctx, tmp) {
            if (reg_ctx->reg >= start) {
                HASH_DEL(ctx->reg_hash, reg_ctx);
            }
        }
    } else {
        HASH_CLEAR(hh, ctx->reg_hash);
    }
    for (reg = start; reg < ctx->num_reg; reg++) {
        if (ctx->register_ctx[reg].views)
            free(ctx->register_ctx[reg].views);
    }
    if (ctx->registers)
        memset(&ctx->registers[start], 0, sizeof(pcilib_register_description_t));
    if (ctx->register_ctx)
        memset(&ctx->register_ctx[start], 0, (ctx->alloc_reg - start) * sizeof(pcilib_register_context_t));
    ctx->num_reg = start;
}
References pcilib_s::alloc_reg, pcilib_s::num_reg, pcilib_register_context_t::reg, pcilib_s::reg_hash, pcilib_s::register_ctx, pcilib_s::registers, and pcilib_register_context_t::views.
Referenced by pcilib_close().