pcilib: pcilib_dma_api_description_t Struct Reference
pcilib_dma_api_description_t Struct Reference
#include <dma.h>
Data Fields
pcilib_version_t version
pcilib_dma_context_t *(* init)(pcilib_t *ctx, const char *model, const void *arg)
void(* free)(pcilib_dma_context_t *ctx)
int(* status)(pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_engine_status_t *status, size_t n_buffers, pcilib_dma_buffer_status_t *buffers)
int(* enable_irq)(pcilib_dma_context_t *ctx, pcilib_irq_type_t irq_type, pcilib_dma_flags_t flags)
int(* disable_irq)(pcilib_dma_context_t *ctx, pcilib_dma_flags_t flags)
int(* acknowledge_irq)(pcilib_dma_context_t *ctx, pcilib_irq_type_t irq_type, pcilib_irq_source_t irq_source)
int(* start_dma)(pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
int(* stop_dma)(pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
int(* push)(pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *written)
int(* stream)(pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, pcilib_dma_callback_t cb, void *cbattr)
double(* benchmark)(pcilib_dma_context_t *ctx, pcilib_dma_engine_addr_t dma, uintptr_t addr, size_t size, size_t iterations, pcilib_dma_direction_t direction)
Field Documentation
acknowledge_irq
int(* pcilib_dma_api_description_t::acknowledge_irq) (pcilib_dma_context_t *ctx, pcilib_irq_type_t irq_type, pcilib_irq_source_t irq_source)
Referenced by pcilib_acknowledge_irq().
benchmark
double(* pcilib_dma_api_description_t::benchmark) (pcilib_dma_context_t *ctx, pcilib_dma_engine_addr_t dma, uintptr_t addr, size_t size, size_t iterations, pcilib_dma_direction_t direction)
Referenced by pcilib_benchmark_dma().
disable_irq
int(* pcilib_dma_api_description_t::disable_irq) (pcilib_dma_context_t *ctx, pcilib_dma_flags_t flags)
Referenced by pcilib_disable_irq().
enable_irq
int(* pcilib_dma_api_description_t::enable_irq) (pcilib_dma_context_t *ctx, pcilib_irq_type_t irq_type, pcilib_dma_flags_t flags)
Referenced by pcilib_enable_irq().
free
void(* pcilib_dma_api_description_t::free) (pcilib_dma_context_t *ctx)
Referenced by pcilib_close(), and pcilib_init_dma().
init
pcilib_dma_context_t *(* pcilib_dma_api_description_t::init) (pcilib_t *ctx, const char *model, const void *arg)
Referenced by pcilib_init_dma().
push
int(* pcilib_dma_api_description_t::push) (pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, void *buf, size_t *written)
Referenced by pcilib_push_dma().
start_dma
int(* pcilib_dma_api_description_t::start_dma) (pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Referenced by pcilib_start_dma().
status
int(* pcilib_dma_api_description_t::status) (pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_engine_status_t *status, size_t n_buffers, pcilib_dma_buffer_status_t *buffers)
Referenced by pcilib_get_dma_status().
stop_dma
int(* pcilib_dma_api_description_t::stop_dma) (pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, pcilib_dma_flags_t flags)
Referenced by pcilib_stop_dma().
stream
int(* pcilib_dma_api_description_t::stream) (pcilib_dma_context_t *ctx, pcilib_dma_engine_t dma, uintptr_t addr, size_t size, pcilib_dma_flags_t flags, pcilib_timeout_t timeout, pcilib_dma_callback_t cb, void *cbattr)
Referenced by pcilib_stream_dma().
version
pcilib_version_t pcilib_dma_api_description_t::version
The documentation for this struct was generated from the following file:
dma.h