pcilib: pcilib_event_api_description_t Struct Reference
pcilib_event_api_description_t Struct Reference
#include <event.h>
Data Fields
pcilib_version_t version
pcilib_context_t *(* init)(pcilib_t *ctx)
void(* free)(pcilib_context_t *ctx)
pcilib_dma_context_t *(* init_dma)(pcilib_context_t *ctx)
int(* reset)(pcilib_context_t *ctx)
int(* start)(pcilib_context_t *ctx, pcilib_event_t event_mask, pcilib_event_flags_t flags)
int(* stop)(pcilib_context_t *ctx, pcilib_event_flags_t flags)
int(* trigger)(pcilib_context_t *ctx, pcilib_event_t event, size_t trigger_size, void *trigger_data)
int(* stream)(pcilib_context_t *ctx, pcilib_event_callback_t callback, void *user)
int(* next_event)(pcilib_context_t *ctx, pcilib_timeout_t timeout, pcilib_event_id_t *evid, size_t info_size, pcilib_event_info_t *info)
int(* get_data)(pcilib_context_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t *size, void **data)
int(* return_data)(pcilib_context_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, void *data)
Field Documentation
free
void(* pcilib_event_api_description_t::free) (pcilib_context_t *ctx)
Referenced by pcilib_close().
get_data
int(* pcilib_event_api_description_t::get_data) (pcilib_context_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, size_t arg_size, void *arg, size_t *size, void **data)
Referenced by pcilib_copy_data(), pcilib_copy_data_with_argument(), pcilib_get_data(), and pcilib_get_data_with_argument().
init
pcilib_context_t *(* pcilib_event_api_description_t::init) (pcilib_t *ctx)
Referenced by pcilib_init_event_engine().
init_dma
pcilib_dma_context_t *(* pcilib_event_api_description_t::init_dma) (pcilib_context_t *ctx)
Referenced by pcilib_init_dma().
next_event
int(* pcilib_event_api_description_t::next_event) (pcilib_context_t *ctx, pcilib_timeout_t timeout, pcilib_event_id_t *evid, size_t info_size, pcilib_event_info_t *info)
Referenced by pcilib_get_next_event(), and pcilib_stream().
reset
int(* pcilib_event_api_description_t::reset) (pcilib_context_t *ctx)
Referenced by pcilib_reset().
return_data
int(* pcilib_event_api_description_t::return_data) (pcilib_context_t *ctx, pcilib_event_id_t event_id, pcilib_event_data_type_t data_type, void *data)
Referenced by pcilib_return_data().
start
int(* pcilib_event_api_description_t::start) (pcilib_context_t *ctx, pcilib_event_t event_mask, pcilib_event_flags_t flags)
Referenced by pcilib_start().
stop
int(* pcilib_event_api_description_t::stop) (pcilib_context_t *ctx, pcilib_event_flags_t flags)
Referenced by pcilib_stop().
stream
int(* pcilib_event_api_description_t::stream) (pcilib_context_t *ctx, pcilib_event_callback_t callback, void *user)
Referenced by pcilib_stream().
trigger
int(* pcilib_event_api_description_t::trigger) (pcilib_context_t *ctx, pcilib_event_t event, size_t trigger_size, void *trigger_data)
Referenced by pcilib_trigger().
version
pcilib_version_t pcilib_event_api_description_t::version
The documentation for this struct was generated from the following file:
event.h