pcilib: pcilib_register_protocol_api_description_t Struct Reference
pcilib_register_protocol_api_description_t Struct Reference
#include <bank.h>
Data Fields
pcilib_version_t version
pcilib_register_bank_context_t *(* init)(pcilib_t *ctx, pcilib_register_bank_t bank, const char *model, const void *args)
Optional API call to initialize bank context.
void(* free)(pcilib_t *pcilib, pcilib_register_bank_context_t *ctx)
Optional API call to cleanup bank context.
uintptr_t(* resolve)(pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_address_resolution_flags_t flags, pcilib_register_addr_t addr)
Resolves register virtual address (if supported)
int(* read)(pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_register_addr_t addr, pcilib_register_value_t *value)
Read from register, mandatory for RO/RW registers.
int(* write)(pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_register_addr_t addr, pcilib_register_value_t value)
Write to register, mandatory for WO/RW registers.
Field Documentation
free
void(* pcilib_register_protocol_api_description_t::free) (pcilib_t *pcilib, pcilib_register_bank_context_t *ctx)
Optional API call to cleanup bank context.
Referenced by pcilib_free_register_banks().
init
pcilib_register_bank_context_t *(* pcilib_register_protocol_api_description_t::init) (pcilib_t *ctx, pcilib_register_bank_t bank, const char *model, const void *args)
Optional API call to initialize bank context.
Referenced by pcilib_init_register_banks().
read
int(* pcilib_register_protocol_api_description_t::read) (pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_register_addr_t addr, pcilib_register_value_t *value)
Read from register, mandatory for RO/RW registers.
resolve
uintptr_t(* pcilib_register_protocol_api_description_t::resolve) (pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_address_resolution_flags_t flags, pcilib_register_addr_t addr)
Resolves register virtual address (if supported)
Referenced by pcilib_resolve_bank_address_by_id(), and pcilib_resolve_register_address_by_id().
version
pcilib_version_t pcilib_register_protocol_api_description_t::version
write
int(* pcilib_register_protocol_api_description_t::write) (pcilib_t *pcilib, pcilib_register_bank_context_t *ctx, pcilib_register_addr_t addr, pcilib_register_value_t value)
Write to register, mandatory for WO/RW registers.
The documentation for this struct was generated from the following file:
bank.h