pcilib: pcilib_view_api_description_t Struct Reference
pcilib_view_api_description_t Struct Reference
#include <view.h>
Data Fields
pcilib_version_t version
Version.
size_t description_size
The actual size of the description.
pcilib_view_context_t *(* init)(pcilib_t *ctx, pcilib_view_t view)
Optional function which should allocated context used by read/write functions.
void(* free)(pcilib_t *ctx, pcilib_view_context_t *view)
Optional function which should clean context.
void(* free_description)(pcilib_t *ctx, pcilib_view_description_t *view)
Optional function which shoud clean required parts of the extended description if non-static memory was used to initialize it.
int(* read_from_reg)(pcilib_t *ctx, pcilib_view_context_t *view, pcilib_register_value_t regval, pcilib_value_t *val)
Function which computes view value based on the passed the register value (view-based properties should not use register value)
int(* write_to_reg)(pcilib_t *ctx, pcilib_view_context_t *view, pcilib_register_value_t *regval, const pcilib_value_t *val)
Function which computes register value based on the passed value (view-based properties are not required to set the register value)
Field Documentation
description_size
size_t pcilib_view_api_description_t::description_size
The actual size of the description.
Referenced by pcilib_add_views_custom().
free
void(* pcilib_view_api_description_t::free) (pcilib_t *ctx, pcilib_view_context_t *view)
Optional function which should clean context.
Referenced by pcilib_clean_views().
free_description
void(* pcilib_view_api_description_t::free_description) (pcilib_t *ctx, pcilib_view_description_t *view)
Optional function which shoud clean required parts of the extended description if non-static memory was used to initialize it.
Referenced by pcilib_clean_views().
init
pcilib_view_context_t *(* pcilib_view_api_description_t::init) (pcilib_t *ctx, pcilib_view_t view)
Optional function which should allocated context used by read/write functions.
Referenced by pcilib_add_views_custom().
read_from_reg
int(* pcilib_view_api_description_t::read_from_reg) (pcilib_t *ctx, pcilib_view_context_t *view, pcilib_register_value_t regval, pcilib_value_t *val)
Function which computes view value based on the passed the register value (view-based properties should not use register value)
Referenced by pcilib_add_properties_from_registers(), and pcilib_read_register_view_by_id().
version
pcilib_version_t pcilib_view_api_description_t::version
Version.
write_to_reg
int(* pcilib_view_api_description_t::write_to_reg) (pcilib_t *ctx, pcilib_view_context_t *view, pcilib_register_value_t *regval, const pcilib_value_t *val)
Function which computes register value based on the passed value (view-based properties are not required to set the register value)
Referenced by pcilib_add_properties_from_registers(), and pcilib_write_register_view_by_id().
The documentation for this struct was generated from the following file:
view.h