pcilib: timing.c File Reference
timing.c File Reference
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <assert.h>
#include <ctype.h>
#include <time.h>
#include <sched.h>
#include <arpa/inet.h>
#include <sys/time.h>
#include "pci.h"
#include "tools.h"
#include "error.h"
Macros
#define _POSIX_C_SOURCE 200112L
#define _GNU_SOURCE
Functions
int pcilib_add_timeout (struct timeval *tv, pcilib_timeout_t timeout)
Add the specified number of microseconds to the time stored in tv.
int pcilib_calc_deadline (struct timeval *tv, pcilib_timeout_t timeout)
Computes the deadline by adding the specified number of microseconds to the current timestamp.
int pcilib_check_deadline (struct timeval *tve, pcilib_timeout_t timeout)
Check if we are within timeout microseconds before the specified deadline or already past it.
pcilib_timeout_t pcilib_calc_time_to_deadline (struct timeval *tve)
Compute the remaining time to deadline.
int pcilib_sleep_until_deadline (struct timeval *tv)
Executes sleep until the specified deadline Real-time capabilities are not used.
pcilib_timeout_t pcilib_timediff (struct timeval *tvs, struct timeval *tve)
Computes the number of microseconds between 2 timestamps.
int pcilib_timecmp (struct timeval *tv1, struct timeval *tv2)
Compares two timestamps.
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
_POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200112L
Function Documentation
pcilib_add_timeout()
int pcilib_add_timeout (struct timeval * tv, pcilib_timeout_t timeout)
Add the specified number of microseconds to the time stored in tv.
Parameters
[in,out] tv - timestamp
[in] timeout - number of microseconds to add
Returns
- error code or 0 for correctness
{
    tv->tv_usec += timeout%1000000;
    if (tv->tv_usec > 999999) {
        tv->tv_usec -= 1000000;
        tv->tv_sec += 1 + timeout/1000000;
    } else {
        tv->tv_sec += timeout/1000000;
    }
    return 0;
}
Referenced by pcilib_calc_deadline().
pcilib_calc_deadline()
int pcilib_calc_deadline (struct timeval * tv, pcilib_timeout_t timeout)
Computes the deadline by adding the specified number of microseconds to the current timestamp.
Parameters
[out] tv - the deadline
[in] timeout - number of microseconds to add
Returns
- error code or 0 for correctness
{
    gettimeofday(tv, NULL);
    pcilib_add_timeout(tv, timeout);
    return 0;
}
References pcilib_add_timeout().
pcilib_calc_time_to_deadline()
pcilib_timeout_t pcilib_calc_time_to_deadline (struct timeval * tv)
Compute the remaining time to deadline.
Parameters
[in] tv - the deadline
Returns
- number of microseconds until deadline or 0 if we are already past it
{
    int64_t res;
    struct timeval tvs;
    gettimeofday(&tvs, NULL);
    res = ((tve->tv_sec - tvs.tv_sec)*1000000 + (tve->tv_usec - tvs.tv_usec));
    if (res < 0) return 0;
    return res;
}
Referenced by pcilib_sleep_until_deadline().
pcilib_check_deadline()
int pcilib_check_deadline (struct timeval * tv, pcilib_timeout_t timeout)
Check if we are within timeout microseconds before the specified deadline or already past it.
Parameters
[in] tv - the deadline
[in] timeout - maximum number of microseconds before deadline
Returns
- 1 if we are within timeout microseconds before deadline or past it, 0 - otherwise
{
    int64_t res;
    struct timeval tvs;
    if (!tve->tv_sec) return 0;
    gettimeofday(&tvs, NULL);
    res = ((tve->tv_sec - tvs.tv_sec)*1000000 + (tve->tv_usec - tvs.tv_usec));
        // Hm... Some problems comparing signed and unsigned. So, sign check first
    if ((res < 0)||(res < timeout)) {
        return 1;
    }
    return 0;
}
pcilib_sleep_until_deadline()
int pcilib_sleep_until_deadline (struct timeval * tv)
Executes sleep until the specified deadline Real-time capabilities are not used.
TThe sleep could wake slightly after the specified deadline.
Parameters
[in] tv - the deadline
Returns
- error code or 0 for correctness
{
    struct timespec wait;
    pcilib_timeout_t duration;
    duration = pcilib_calc_time_to_deadline(tv);
    if (duration > 0) {
        wait.tv_sec = duration / 1000000;
        wait.tv_nsec = 1000 * (duration % 1000000);
        nanosleep(&wait, NULL);
    }
    return 0;
}
References pcilib_calc_time_to_deadline(), timespec::tv_nsec, and timespec::tv_sec.
pcilib_timecmp()
int pcilib_timecmp (struct timeval * tv1, struct timeval * tv2)
Compares two timestamps.
Parameters
[in] tv1 - the first timestamp
[in] tv2 - the second timestamp
Returns
- 0 if timestamps are equal, 1 if the first timestamp is after the second, or -1 if the second is after the first.
{
    if (tv1->tv_sec > tv2->tv_sec) return 1;
    else if (tv1->tv_sec < tv2->tv_sec) return -1;
    else if (tv1->tv_usec > tv2->tv_usec) return 1;
    else if (tv1->tv_usec < tv2->tv_usec) return -1;
    return 0;
}
pcilib_timediff()
pcilib_timeout_t pcilib_timediff (struct timeval * tve, struct timeval * tvs)
Computes the number of microseconds between 2 timestamps.
This function expects that tve is after tvs.
Parameters
[in] tve - the end of the time interval
[in] tvs - the beginning of the time interval
Returns
- number of microseconds between two timestamps
{
    return ((tve->tv_sec - tvs->tv_sec)*1000000 + (tve->tv_usec - tvs->tv_usec));
}