pcilib: tools.h File Reference
tools.h File Reference
#include <stdio.h>
#include <stdint.h>
#include <pcilib.h>
Macros
#define BIT_MASK(bits) ((1ll << (bits)) - 1)
#define min2(a, b) (((a)<(b))?(a):(b))
Functions
int pcilib_isnumber (const char *str)
Check if provided string is a decimal integer.
int pcilib_isxnumber (const char *str)
Check if provided string is a hexdecimal integer, optionally prefexed with 0x.
int pcilib_isnumber_n (const char *str, size_t len)
Check if first len bytes of the provided string is a decimal integer.
int pcilib_isxnumber_n (const char *str, size_t len)
Check if first len bytes of the provided string is a hexdecimal integer, optionally prefexed with 0x.
uint16_t pcilib_swap16 (uint16_t x)
Change the endianess of the provided number (between big- and little-endian format)
uint32_t pcilib_swap32 (uint32_t x)
Change the endianess of the provided number (between big- and little-endian format)
uint64_t pcilib_swap64 (uint64_t x)
Change the endianess of the provided number (between big- and little-endian format)
void pcilib_swap (void *dst, void *src, size_t access, size_t n)
Change the endianess of the provided array.
Macro Definition Documentation
BIT_MASK
#define BIT_MASK (bits) ((1ll << (bits)) - 1)
min2
#define min2 (a, b) (((a)<(b))?(a):(b))
Function Documentation
pcilib_isnumber()
int pcilib_isnumber (const char * str)
Check if provided string is a decimal integer.
Parameters
[in] str - string to check
Returns
- 1 if string is a number and 0 - otherwise
{
    int i = 0;
    for (i = 0; str[i]; i++)
        if (!isdigit(str[i])) return 0;
    return 1;
}
Referenced by pcilib_convert_value_type().
pcilib_isnumber_n()
int pcilib_isnumber_n (const char * str, size_t len)
Check if first len bytes of the provided string is a decimal integer.
Parameters
[in] str - string to check
[in] len - size of the string
Returns
- 1 if string is a number and 0 - otherwise
{
    int i = 0;
    for (i = 0; (str[i])&&(i < len); i++)
        if (!isdigit(str[i])) return 0;
    return 1;
}
pcilib_isxnumber()
int pcilib_isxnumber (const char * str)
Check if provided string is a hexdecimal integer, optionally prefexed with 0x.
Parameters
[in] str - string to check
Returns
- 1 if string is a number and 0 - otherwise
{
    int i = 0;
    if ((str[0] == '0')&&((str[1] == 'x')||(str[1] == 'X'))) i += 2;
    for (; str[i]; i++)
        if (!isxdigit(str[i])) return 0;
    return 1;
}
Referenced by pcilib_convert_value_type(), pcilib_find_register_bank(), and pcilib_find_register_protocol().
pcilib_isxnumber_n()
int pcilib_isxnumber_n (const char * str, size_t len)
Check if first len bytes of the provided string is a hexdecimal integer, optionally prefexed with 0x.
Parameters
[in] str - string to check
[in] len - size of the string
Returns
- 1 if string is a number and 0 - otherwise
{
    int i = 0;
    if ((len > 1)&&(str[0] == '0')&&((str[1] == 'x')||(str[1] == 'X'))) i += 2;
    for (; (str[i])&&(i < len); i++)
        if (!isxdigit(str[i])) return 0;
    return 1;
}
pcilib_swap()
void pcilib_swap (void * dst, void * src, size_t access, size_t n)
Change the endianess of the provided array.
Parameters
[out] dst - the destination memory region, can be equal to src
[in] src - the source memory region
[in] access - the size of word in bytes (1, 2, 4, or 8)
[in] n - the number of words to copy (n * access bytes are copied).
{
    int i;
    switch (size) {
        case 1:
            if (src != dst) memcpy(dst, src, n);
        break;
        case 2:
            for (i = 0; i < n; i++) {
                ((uint16_t*)dst)[i] = pcilib_swap16(((uint16_t*)src)[i]);
            }
        break;
        case 4:
            for (i = 0; i < n; i++) {
                ((uint32_t*)dst)[i] = pcilib_swap32(((uint32_t*)src)[i]);
            }
        break;
        case 8:
            for (i = 0; i < n; i++) {
                ((uint64_t*)dst)[i] = pcilib_swap64(((uint64_t*)src)[i]);
            }
        break;
        default:
            pcilib_error("Invalid word size: %i", size);
    }
}
References pcilib_error, pcilib_swap16(), pcilib_swap32(), and pcilib_swap64().
pcilib_swap16()
uint16_t pcilib_swap16 (uint16_t x)
Change the endianess of the provided number (between big- and little-endian format)
Parameters
[in] x - number in little/big endian format
Returns
- number in big/little endian format
{
    return (((x<<8)&0xFFFF) | ((x>>8)&0xFFFF));
}
Referenced by pcilib_swap().
pcilib_swap32()
uint32_t pcilib_swap32 (uint32_t x)
Change the endianess of the provided number (between big- and little-endian format)
Parameters
[in] x - number in little/big endian format
Returns
- number in big/little endian format
{
    return ((x & 0xFF) << 24) | \
        ((x & 0xFF00) << 8) | \
        ((x & 0xFF0000) >> 8) | \
        ((x & 0xFF000000) >> 24);
}
Referenced by pcilib_swap().
pcilib_swap64()
uint64_t pcilib_swap64 (uint64_t x)
Change the endianess of the provided number (between big- and little-endian format)
Parameters
[in] x - number in little/big endian format
Returns
- number in big/little endian format
{
    return (((uint64_t)(x) << 56) | \
        (((uint64_t)(x) << 40) & 0xff000000000000ULL) | \
        (((uint64_t)(x) << 24) & 0xff0000000000ULL) | \
        (((uint64_t)(x) << 8)  & 0xff00000000ULL) | \
        (((uint64_t)(x) >> 8)  & 0xff000000ULL) | \
        (((uint64_t)(x) >> 24) & 0xff0000ULL) | \
        (((uint64_t)(x) >> 40) & 0xff00ULL) | \
        ((uint64_t)(x)  >> 56));
}
Referenced by pcilib_swap().