pcilib: unit.h File Reference
unit.h File Reference
#include <uthash.h>
#include <pcilib.h>
Data Structures
struct pcilib_unit_transform_t
unit transformation routines
struct pcilib_unit_description_t
struct pcilib_unit_context_s
Macros
#define PCILIB_UNIT_INVALID ((pcilib_unit_t)-1)
#define PCILIB_UNIT_TRANSFORM_INVALID ((pcilib_unit_transform_t)-1)
#define PCILIB_MAX_TRANSFORMS_PER_UNIT 16
Limits number of supported transforms per unit.
Typedefs
typedef struct pcilib_unit_context_s pcilib_unit_context_t
Functions
int pcilib_add_units (pcilib_t *ctx, size_t n, const pcilib_unit_description_t *desc)
Use this function to add new unit definitions into the model.
void pcilib_clean_units (pcilib_t *ctx, pcilib_unit_t start)
Destroys data associated with units.
pcilib_unit_t pcilib_find_unit_by_name (pcilib_t *ctx, const char *unit)
Find unit id using supplied name.
pcilib_unit_transform_t * pcilib_find_transform_by_unit_names (pcilib_t *ctx, const char *from, const char *to)
Find the required transform between two specified units.
int pcilib_transform_unit (pcilib_t *ctx, const pcilib_unit_transform_t *trans, pcilib_value_t *value)
Converts value to the requested units.
int pcilib_transform_unit_by_name (pcilib_t *ctx, const char *to, pcilib_value_t *value)
Converts value to the requested units.
Macro Definition Documentation
PCILIB_MAX_TRANSFORMS_PER_UNIT
#define PCILIB_MAX_TRANSFORMS_PER_UNIT 16
Limits number of supported transforms per unit.
PCILIB_UNIT_INVALID
#define PCILIB_UNIT_INVALID ((pcilib_unit_t)-1)
PCILIB_UNIT_TRANSFORM_INVALID
#define PCILIB_UNIT_TRANSFORM_INVALID ((pcilib_unit_transform_t)-1)
Typedef Documentation
pcilib_unit_context_t
typedef struct pcilib_unit_context_s pcilib_unit_context_t
Function Documentation
pcilib_add_units()
int pcilib_add_units (pcilib_t * ctx, size_t n, const pcilib_unit_description_t * desc)
Use this function to add new unit definitions into the model.
It is error to re-register already registered unit. The function will copy the context of unit description, but name, transform, and other strings in the structure are considered to have static duration and will not be copied. On error no new units are initalized.
Parameters
[in,out] ctx - pcilib context
[in] n - number of units to initialize. It is OK to pass 0 if protocols variable is NULL terminated (last member of protocols array have all members set to 0)
[in] desc - unit descriptions
Returns
- error or 0 on success
{
    size_t i;
    int err = 0;
    if (!n) {
        for (n = 0; desc[n].name; n++);
    }
    if ((ctx->num_units + n + 1) > ctx->alloc_units) {
        size_t size;
        pcilib_unit_description_t *units;
        for (size = ctx->alloc_units; size < 2 * (n + ctx->num_units + 1); size <<= 1);
        units = (pcilib_unit_description_t*)realloc(ctx->units, size * sizeof(pcilib_unit_description_t));
        if (!units) return PCILIB_ERROR_MEMORY;
        ctx->units = units;
        ctx->alloc_units = size;
        ctx->model_info.units = units;
    }
        // ToDo: Check if exists...
    for (i = 0; i < n; i++) {
        pcilib_unit_t unit = pcilib_find_unit_by_name(ctx, desc[i].name);
        if (unit != PCILIB_UNIT_INVALID) {
            pcilib_clean_units(ctx, ctx->num_units);
            pcilib_error("Unit %s is already defined in the model", desc[i].name);
            return PCILIB_ERROR_EXIST;
        }
        pcilib_unit_context_t *unit_ctx = (pcilib_unit_context_t*)malloc(sizeof(pcilib_unit_context_t));
        if (!unit_ctx) {
            pcilib_clean_units(ctx, ctx->num_units);
            return PCILIB_ERROR_MEMORY;
        }
        memset(unit_ctx, 0, sizeof(pcilib_unit_context_t));
        unit_ctx->unit = ctx->num_units + i;
        unit_ctx->name = desc[i].name;
        HASH_ADD_KEYPTR(hh, ctx->unit_hash, unit_ctx->name, strlen(unit_ctx->name), unit_ctx);
        memcpy(ctx->units + ctx->num_units + i, &desc[i], sizeof(pcilib_unit_description_t));
    }
    ctx->num_units += n;
    memset(ctx->units + ctx->num_units, 0, sizeof(pcilib_unit_description_t));
    return err;
}
References pcilib_s::alloc_units, pcilib_s::model_info, pcilib_unit_description_t::name, pcilib_unit_context_s::name, pcilib_s::num_units, pcilib_clean_units(), pcilib_error, PCILIB_ERROR_EXIST, PCILIB_ERROR_MEMORY, pcilib_find_unit_by_name(), PCILIB_UNIT_INVALID, pcilib_unit_context_s::unit, pcilib_s::unit_hash, pcilib_model_description_t::units, and pcilib_s::units.
pcilib_clean_units()
void pcilib_clean_units (pcilib_t * ctx, pcilib_unit_t start)
Destroys data associated with units.
This is an internal function and will be called during clean-up.
Parameters
[in,out] ctx - pcilib context
[in] start - specifies first unit to clean (used to clean only part of the units to keep the defined state if pcilib_add_units has failed)
{
    pcilib_unit_context_t *s, *tmp;
    if (ctx->unit_hash) {
        HASH_ITER(hh, ctx->unit_hash, s, tmp) {
            if (s->unit >= start) {
                HASH_DEL(ctx->unit_hash, s);
                free(s);
            }
        }
    }
    memset(&ctx->units[start], 0, sizeof(pcilib_unit_description_t));
    ctx->num_units = start;
}
References pcilib_s::num_units, pcilib_unit_context_s::unit, pcilib_s::unit_hash, and pcilib_s::units.
Referenced by pcilib_add_units(), and pcilib_close().
pcilib_find_transform_by_unit_names()
pcilib_unit_transform_t * pcilib_find_transform_by_unit_names (pcilib_t * ctx, const char * from, const char * to)
Find the required transform between two specified units.
Parameters
[in] ctx - pcilib context
[in] from - the source unit
[in] to - destination unit
Returns
- the pointer to unit transform or NULL in case of error. If no transform required (i.e. from = to), the function will return pcilib_unit_transform_t structure with transform field set to NULL.
{
    int i;
    pcilib_unit_t unit;
    if ((!from)||(!to))
        return NULL;
    if (!strcasecmp(from, to))
        return &pcilib_unit_transform_null;
    unit = pcilib_find_unit_by_name(ctx, from);
    if (unit == PCILIB_UNIT_INVALID) return NULL;
    for (i = 0; ctx->units[unit].transforms[i].unit; i++) {
        if (!strcasecmp(ctx->units[unit].transforms[i].unit, to))
            return &ctx->units[unit].transforms[i];
    }
    return NULL;
}
References pcilib_find_unit_by_name(), PCILIB_UNIT_INVALID, pcilib_unit_description_t::transforms, pcilib_unit_transform_t::unit, and pcilib_s::units.
Referenced by pcilib_transform_unit_by_name().
pcilib_find_unit_by_name()
pcilib_unit_t pcilib_find_unit_by_name (pcilib_t * ctx, const char * unit)
Find unit id using supplied name.
Parameters
[in] ctx - pcilib context
[in] unit - the requested unit name
Returns
- unit id or PCILIB_UNIT_INVALID if error not found or error has occured
{
    pcilib_unit_context_t *unit_ctx = NULL;
    HASH_FIND_STR(ctx->unit_hash, name, unit_ctx);
    if (unit_ctx) return unit_ctx->unit;
/*
    pcilib_unit_t i;
    for(i = 0; ctx->units[i].name; i++) {
        if (!strcasecmp(ctx->units[i].name, name))
            return i;
    }
*/
    return PCILIB_UNIT_INVALID;
}
References PCILIB_UNIT_INVALID, pcilib_unit_context_s::unit, and pcilib_s::unit_hash.
Referenced by pcilib_add_units(), pcilib_convert_value_unit(), and pcilib_find_transform_by_unit_names().
pcilib_transform_unit()
int pcilib_transform_unit (pcilib_t * ctx, const pcilib_unit_transform_t * trans, pcilib_value_t * value)
Converts value to the requested units.
It is error to convert values with unspecified units. This is internal function, use pcilib_value_convert_value_unit instead.
Parameters
[in,out] ctx - pcilib context
[in] trans - the requested unit transform
[in,out] value - the value to be converted (changed on success)
Returns
- error or 0 on success
{
    int err;
    if (trans->transform) {
        err = pcilib_py_eval_string(ctx, trans->transform, value);
        if (err) return err;
        value->unit = trans->unit;
    } else if (trans->unit) {
        value->unit = trans->unit;
    }
    return 0;
}
References pcilib_py_eval_string(), pcilib_unit_transform_t::transform, pcilib_value_t::unit, and pcilib_unit_transform_t::unit.
Referenced by pcilib_read_register_view_by_id(), pcilib_transform_unit_by_name(), and pcilib_write_register_view_by_id().
pcilib_transform_unit_by_name()
int pcilib_transform_unit_by_name (pcilib_t * ctx, const char * to, pcilib_value_t * value)
Converts value to the requested units.
It is error to convert values with unspecified units. This is internal function, use pcilib_value_convert_value_unit instead.
Parameters
[in,out] ctx - pcilib context
[in] to - specifies the requested unit of the value
[in,out] value - the value to be converted (changed on success)
Returns
- error or 0 on success
{
    pcilib_unit_transform_t *trans;
    if (!value->unit) {
        pcilib_warning("Can't transform unit of the value with unspecified unit");
        return PCILIB_ERROR_INVALID_ARGUMENT;
    }
    trans = pcilib_find_transform_by_unit_names(ctx, value->unit, to);
    if (!trans) {
        pcilib_warning("Can't transform unit (%s) to (%s)", value->unit, to);
        return PCILIB_ERROR_NOTSUPPORTED;
    }
    return pcilib_transform_unit(ctx, trans, value);
}
References PCILIB_ERROR_INVALID_ARGUMENT, PCILIB_ERROR_NOTSUPPORTED, pcilib_find_transform_by_unit_names(), pcilib_transform_unit(), pcilib_warning, and pcilib_value_t::unit.
Referenced by pcilib_convert_value_unit().