pcilib: view.h File Reference
view.h File Reference
#include <uthash.h>
#include <pcilib.h>
#include <pcilib/unit.h>
Data Structures
struct pcilib_view_api_description_t
struct pcilib_view_description_s
struct pcilib_view_context_s
Macros
#define PCILIB_VIEW_INVALID ((pcilib_view_t)-1)
Typedefs
typedef struct pcilib_view_context_s pcilib_view_context_t
typedef struct pcilib_view_description_s pcilib_view_description_t
Enumerations
enum pcilib_view_flags_t { PCILIB_VIEW_FLAG_PROPERTY = 1 , PCILIB_VIEW_FLAG_REGISTER = 2 }
Functions
int pcilib_add_views (pcilib_t *ctx, size_t n, const pcilib_view_description_t *desc)
Use this function to add new view definitions into the model.
int pcilib_add_views_custom (pcilib_t *ctx, size_t n, const pcilib_view_description_t *desc, pcilib_view_context_t **refs)
Use this function to add new view definitions into the model.
void pcilib_clean_views (pcilib_t *ctx, pcilib_view_t start)
Destroys data associated with views.
pcilib_view_context_t * pcilib_find_view_context_by_name (pcilib_t *ctx, const char *view)
pcilib_view_context_t * pcilib_find_register_view_context_by_name (pcilib_t *ctx, pcilib_register_t reg, const char *name)
pcilib_view_context_t * pcilib_find_register_view_context (pcilib_t *ctx, pcilib_register_t reg, const char *name)
pcilib_view_t pcilib_find_view_by_name (pcilib_t *ctx, const char *name)
Macro Definition Documentation
PCILIB_VIEW_INVALID
#define PCILIB_VIEW_INVALID ((pcilib_view_t)-1)
Typedef Documentation
pcilib_view_context_t
typedef struct pcilib_view_context_s pcilib_view_context_t
pcilib_view_description_t
typedef struct pcilib_view_description_s pcilib_view_description_t
Enumeration Type Documentation
pcilib_view_flags_t
enum pcilib_view_flags_t
Enumerator
PCILIB_VIEW_FLAG_PROPERTY
Indicates that view does not depend on a value and is independent property.
PCILIB_VIEW_FLAG_REGISTER
Indicates that view does not depend on a value and should be mapped to the register space.
             {
    PCILIB_VIEW_FLAG_PROPERTY = 1,
    PCILIB_VIEW_FLAG_REGISTER = 2
} pcilib_view_flags_t;
Function Documentation
pcilib_add_views()
int pcilib_add_views (pcilib_t * ctx, size_t n, const pcilib_view_description_t * desc)
Use this function to add new view definitions into the model.
It is error to re-register already registered view. The function will copy the context of unit description, but name, transform, and other strings in the structure are considered to have static duration and will not be copied. On error no new views are initalized.
Parameters
[in,out] ctx - pcilib context
[in] n - number of views to initialize. It is OK to pass 0 if protocols variable is NULL terminated (last member of protocols array have all members set to 0)
[in] desc - view descriptions
Returns
- error or 0 on success
{
    return pcilib_add_views_custom(ctx, n, desc, NULL);
}
References pcilib_add_views_custom().
Referenced by pcilib_add_properties_from_registers().
pcilib_add_views_custom()
int pcilib_add_views_custom (pcilib_t * ctx, size_t n, const pcilib_view_description_t * desc, pcilib_view_context_t ** refs)
Use this function to add new view definitions into the model.
It is error to re-register already registered view. The function will copy the context of unit description, but name, transform, and other strings in the structure are considered to have static duration and will not be copied. On error no new views are initalized.
Parameters
[in,out] ctx - pcilib context
[in] n - number of views to initialize. It is OK to pass 0 if protocols variable is NULL terminated (last member of protocols array have all members set to 0)
[in] desc - view descriptions
[out] refs - fills allocated view contexts. On error context is undefined.
Returns
- error or 0 on success
{
    int err;
    size_t i;
    void *ptr;
    if (!n) {
            // No padding between array elements
        ptr = (void*)desc;
        while (1) {
            const pcilib_view_description_t *v = (const pcilib_view_description_t*)ptr;
            if (v->name) n++;
            else break;
            ptr += v->api->description_size;
        }
    }
    if (!refs) {
        refs = (pcilib_view_context_t**)alloca(n * sizeof(pcilib_view_context_t*));
        if (!refs) return PCILIB_ERROR_MEMORY;
    }
    if ((ctx->num_views + n + 1) > ctx->alloc_views) {
        size_t size;
        pcilib_view_description_t **views;
        for (size = ctx->alloc_views; size < 2 * (n + ctx->num_views + 1); size<<=1);
        views = (pcilib_view_description_t**)realloc(ctx->views, size * sizeof(pcilib_view_description_t*));
        if (!views) return PCILIB_ERROR_MEMORY;
        ctx->views = views;
        ctx->alloc_views = size;
        ctx->model_info.views = (const pcilib_view_description_t**)views;
    }
        // No padding between array elements
    ptr = (void*)desc;
    for (i = 0; i < n; i++) {
        const pcilib_view_description_t *v = (const pcilib_view_description_t*)ptr;
        pcilib_view_description_t *cur;
        pcilib_view_context_t *view_ctx;
        pcilib_view_t view = pcilib_find_view_by_name(ctx, v->name);
        if (view != PCILIB_VIEW_INVALID) {
            ctx->views[ctx->num_views + i] = NULL;
            pcilib_clean_views(ctx, ctx->num_views);
            pcilib_error("View %s is already defined in the model", v->name);
            return PCILIB_ERROR_EXIST;
        }
        cur = (pcilib_view_description_t*)malloc(v->api->description_size);
        if (!cur) {
            ctx->views[ctx->num_views + i] = NULL;
            pcilib_clean_views(ctx, ctx->num_views);
            return PCILIB_ERROR_MEMORY;
        }
        memcpy(cur, v, v->api->description_size);
        ctx->views[ctx->num_views + i] = cur;
        if (v->api->init)
            view_ctx = v->api->init(ctx, ctx->num_views + i);
        else {
            view_ctx = (pcilib_view_context_t*)malloc(sizeof(pcilib_view_context_t));
            if (view_ctx) memset(view_ctx, 0, sizeof(pcilib_view_context_t));
        }
        if (!view_ctx) {
            free(cur);
            ctx->views[ctx->num_views + i] = NULL;
            pcilib_clean_views(ctx, ctx->num_views);
            return PCILIB_ERROR_FAILED;
        }
        view_ctx->view = ctx->num_views + i;
        view_ctx->name = v->name;
        HASH_ADD_KEYPTR(hh, ctx->view_hash, view_ctx->name, strlen(view_ctx->name), view_ctx);
        if (refs) refs[i] = view_ctx;
        ptr += v->api->description_size;
    }
    ctx->views[ctx->num_views + n] = NULL;
    err = pcilib_add_registers_from_properties(ctx, n, refs, ctx->views + ctx->num_views);
    if (err) {
        pcilib_clean_views(ctx, ctx->num_views);
        return err;
    }
    ctx->num_views += n;
    return 0;
}
References pcilib_s::alloc_views, pcilib_view_description_s::api, pcilib_view_api_description_t::description_size, pcilib_view_api_description_t::init, pcilib_s::model_info, pcilib_view_description_s::name, pcilib_view_context_s::name, pcilib_s::num_views, pcilib_add_registers_from_properties(), pcilib_clean_views(), pcilib_error, PCILIB_ERROR_EXIST, PCILIB_ERROR_FAILED, PCILIB_ERROR_MEMORY, pcilib_find_view_by_name(), PCILIB_VIEW_INVALID, pcilib_view_context_s::view, pcilib_s::view_hash, pcilib_model_description_t::views, and pcilib_s::views.
Referenced by pcilib_add_views().
pcilib_clean_views()
void pcilib_clean_views (pcilib_t * ctx, pcilib_view_t start)
Destroys data associated with views.
This is an internal function and will be called during clean-up.
Parameters
[in,out] ctx - pcilib context
[in] start - specifies first view to clean (used to clean only part of the views to keep the defined state if pcilib_add_views has failed)
{
    pcilib_view_t i;
    pcilib_view_context_t *view_ctx, *tmp;
    if (ctx->view_hash) {
        HASH_ITER(hh, ctx->view_hash, view_ctx, tmp) {
            const pcilib_view_description_t *v = ctx->views[view_ctx->view];
            if (view_ctx->view >= start) {
                HASH_DEL(ctx->view_hash, view_ctx);
                if (v->api->free) v->api->free(ctx, view_ctx);
                else free(view_ctx);
            }
        }
    }
    for (i = start; ctx->views[i]; i++) {
        if (ctx->views[i]->api->free_description) {
            ctx->views[i]->api->free_description(ctx, ctx->views[i]);
        } else {
            free(ctx->views[i]);
        }
    }
    ctx->views[start] = NULL;
    ctx->num_views = start;
}
References pcilib_view_description_s::api, pcilib_view_api_description_t::free, pcilib_view_api_description_t::free_description, pcilib_s::num_views, pcilib_view_context_s::view, pcilib_s::view_hash, and pcilib_s::views.
Referenced by pcilib_add_properties_from_registers(), pcilib_add_views_custom(), and pcilib_close().
pcilib_find_register_view_context()
pcilib_view_context_t * pcilib_find_register_view_context (pcilib_t * ctx, pcilib_register_t reg, const char * name)
{
    int err;
    pcilib_view_context_t *view;
    err = pcilib_detect_register_view_and_unit(ctx, reg, name, 0, &view, NULL);
    if (err) return NULL;
    return view;
}
pcilib_find_register_view_context_by_name()
pcilib_view_context_t * pcilib_find_register_view_context_by_name (pcilib_t * ctx, pcilib_register_t reg, const char * name)
{
    pcilib_view_t i;
    pcilib_register_context_t *regctx = &ctx->register_ctx[reg];
    if (!regctx->views) return NULL;
    for (i = 0; regctx->views[i].name; i++) {
        if (!strcasecmp(name, regctx->views[i].name)) {
            return pcilib_find_view_context_by_name(ctx, regctx->views[i].view);
        }
    }
    return NULL;
}
References pcilib_view_reference_t::name, pcilib_find_view_context_by_name(), pcilib_s::register_ctx, pcilib_view_reference_t::view, and pcilib_register_context_t::views.
pcilib_find_view_by_name()
pcilib_view_t pcilib_find_view_by_name (pcilib_t * ctx, const char * name)
{
    pcilib_view_context_t *view_ctx = pcilib_find_view_context_by_name(ctx, name);
    if (view_ctx) return view_ctx->view;
    return PCILIB_VIEW_INVALID;
}
References pcilib_find_view_context_by_name(), PCILIB_VIEW_INVALID, and pcilib_view_context_s::view.
Referenced by pcilib_add_properties_from_registers(), pcilib_add_views_custom(), and pcilib_get_register_info().
pcilib_find_view_context_by_name()
pcilib_view_context_t * pcilib_find_view_context_by_name (pcilib_t * ctx, const char * view)
{
    pcilib_view_context_t *view_ctx = NULL;
    HASH_FIND_STR(ctx->view_hash, name, view_ctx);
    return view_ctx;
}
References pcilib_s::view_hash.
Referenced by pcilib_find_register_view_context_by_name(), pcilib_find_view_by_name(), and pcilib_get_property_attr().