pcilib: xml.c File Reference
xml.c File Reference
this file is the main source file for the implementation of dynamic registers using xml and several funtionalities for the "pci-tool" line command tool from XML files. the xml part has been implemented using libxml2
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <dirent.h>
#include <errno.h>
#include <alloca.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <libxml/xmlschemastypes.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <libxml/xpathInternals.h>
#include "config.h"
#include "pci.h"
#include "bank.h"
#include "register.h"
#include "xml.h"
#include "error.h"
#include "view.h"
#include "py.h"
#include "views/enum.h"
#include "views/transform.h"
Data Structures
struct pcilib_xml_register_description_t
Macros
#define _XOPEN_SOURCE 700
#define _BSD_SOURCE
#define _DEFAULT_SOURCE
#define BANKS_PATH ((xmlChar*)"/model/bank")
path to complete nodes of banks
#define REGISTERS_PATH ((xmlChar*)"./register")
all standard registers nodes
#define BIT_REGISTERS_PATH ((xmlChar*)"./field")
all bits registers nodes
#define REGISTER_VIEWS_PATH ((xmlChar*)"./view")
supported register & field views
#define TRANSFORM_VIEWS_PATH ((xmlChar*)"/model/transform")
path to complete nodes of views
#define ENUM_VIEWS_PATH ((xmlChar*)"/model/enum")
path to complete nodes of views
#define ENUM_ELEMENTS_PATH ((xmlChar*)"./name")
all elements in the enum
#define UNITS_PATH ((xmlChar*)"/model/unit")
path to complete nodes of units
#define UNIT_TRANSFORMS_PATH ((xmlChar*)"./transform")
all transforms of the unit
Functions
int pcilib_get_xml_attr (pcilib_t *ctx, pcilib_xml_node_t *node, const char *attr, pcilib_value_t *val)
This is an internal function which returns a specified node attribute in the pcilib_value_t structure.
int pcilib_process_xml (pcilib_t *ctx, const char *location)
Processes a bunch of XML files in the specified directory.
int pcilib_init_xml (pcilib_t *ctx, const char *model)
Initializes XML stack and loads a default set of XML files.
void pcilib_free_xml (pcilib_t *ctx)
Cleans up memory used by various XML structures.
char * pcilib_detect_xml_model (pcilib_t *ctx, unsigned int vendor_id, unsigned int device_id)
Resolves device model from vendor and device ids using XML configuration The association of vendor/device id pairs with model are provided devices.xml under PCILIB_MODEL_DIR.
Detailed Description
this file is the main source file for the implementation of dynamic registers using xml and several funtionalities for the "pci-tool" line command tool from XML files. the xml part has been implemented using libxml2
Version
1.0
registers and banks nodes are parsed using xpath expression, but their properties is get by recursively getting all properties nodes. In this sense, if a property changes, the algorithm has to be changed, but if it's registers or banks nodes, just the xpath expression modification should be enough.
Libxml2 considers blank spaces within the XML as node natively and this code as been produced considering blank spaces in the XML files. In case XML files would not contain blank spaces anymore, please change the code.
In case the performance is not good enough, please consider the following : hard code of formulas
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
_DEFAULT_SOURCE
#define _DEFAULT_SOURCE
_XOPEN_SOURCE
#define _XOPEN_SOURCE 700
BANKS_PATH
#define BANKS_PATH ((xmlChar*)"/model/bank")
path to complete nodes of banks
BIT_REGISTERS_PATH
#define BIT_REGISTERS_PATH ((xmlChar*)"./field")
all bits registers nodes
ENUM_ELEMENTS_PATH
#define ENUM_ELEMENTS_PATH ((xmlChar*)"./name")
all elements in the enum
ENUM_VIEWS_PATH
#define ENUM_VIEWS_PATH ((xmlChar*)"/model/enum")
path to complete nodes of views
REGISTER_VIEWS_PATH
#define REGISTER_VIEWS_PATH ((xmlChar*)"./view")
supported register & field views
REGISTERS_PATH
#define REGISTERS_PATH ((xmlChar*)"./register")
all standard registers nodes
TRANSFORM_VIEWS_PATH
#define TRANSFORM_VIEWS_PATH ((xmlChar*)"/model/transform")
path to complete nodes of views
UNIT_TRANSFORMS_PATH
#define UNIT_TRANSFORMS_PATH ((xmlChar*)"./transform")
all transforms of the unit
UNITS_PATH
#define UNITS_PATH ((xmlChar*)"/model/unit")
path to complete nodes of units
Function Documentation
pcilib_detect_xml_model()
char * pcilib_detect_xml_model (pcilib_t * ctx, unsigned int vendor_id, unsigned int device_id)
Resolves device model from vendor and device ids using XML configuration The association of vendor/device id pairs with model are provided devices.xml under PCILIB_MODEL_DIR.
Parameters
[in,out] ctx - pcilib context
[in] vendor_id - the vendor id
[in] device_id - the device id
Returns
- the name of model or NULL on an error and unknown device. It is caller responsibility to free returned string.
< Pointer to the parsed xsd schema
< Pointer to the XML validation context
< Pointer to the XML parser context
{
    int err;
    char *model = NULL;
    xmlSchemaPtr schema;
    xmlSchemaValidCtxtPtr validator;
    xmlParserCtxtPtr parser;
    DIR *rep;
    struct dirent *file = NULL;
    struct stat st;
    const char *data_dir;
    char *xsd_path, *xml_path;
    xmlXPathObjectPtr nodes;
    xmlChar xpath_query[64];
    xmlStrPrintf(xpath_query, sizeof(xpath_query), (xmlChar*)"/devices/device[@vendor=\"%04x\" and @device=\"%04x\"]/@model", vendor_id, device_id);
    data_dir = getenv("PCILIB_DATA_DIR");
    if (!data_dir) data_dir = PCILIB_DATA_DIR;
    xsd_path = (char*)alloca(strlen(data_dir) + 32);
    xml_path = (char*)alloca(strlen(data_dir) + 32);
    if ((!xsd_path)||(!xml_path)) {
        pcilib_error("Error allocating stack memory");
        return NULL;
    }
    sprintf(xsd_path, "%s/devices.xsd", data_dir);
    sprintf(xml_path, "%s/devices", data_dir);
    if (stat(xsd_path, &st)||stat(xml_path, &st)) {
        pcilib_info("No XML devices are defined, missing devices schema or list");
        return NULL;
    }
    parser = xmlNewParserCtxt();
    if (!parser) {
        xmlErrorPtr xmlerr = xmlGetLastError();
        if (xmlerr) pcilib_error("xmlNewParserCtxt reported error %d (%s)", xmlerr->code, xmlerr->message);
        else pcilib_error("Failed to create an XML parser context");
        return NULL;
    }
    err = pcilib_xml_load_xsd_file(ctx, xsd_path, &schema, &validator);
    if (err) {
        xmlFreeParserCtxt(parser);
        pcilib_error("Error (%i) parsing the device schema (%s)", err, xsd_path);
        return NULL;
    }
    rep = opendir(xml_path);
    if (!rep) goto cleanup;
    while ((model == NULL)&&((file = readdir(rep)) != NULL)) {
        xmlDocPtr doc;
        size_t len = strlen(file->d_name);
        if ((len < 4)||(strcasecmp(file->d_name + len - 4, ".xml"))) continue;
        if (file->d_type != DT_REG) continue;
        doc = pcilib_xml_load_file(ctx, parser, validator, xml_path, file->d_name);
        if (!doc) continue;
        nodes = pcilib_xml_eval_xpath_expression(ctx, doc, xpath_query);
        if (!nodes) {
            xmlFreeDoc(doc);
            continue;
        }
        if (!xmlXPathNodeSetIsEmpty(nodes->nodesetval)) {
            xmlNodePtr node = nodes->nodesetval->nodeTab[0];
            model = strdup((char*)node->children->content);
        }
        xmlXPathFreeObject(nodes);
        xmlFreeDoc(doc);
    }
    closedir(rep);
cleanup:
    xmlSchemaFree(schema);
    xmlSchemaFreeValidCtxt(validator);
    xmlFreeParserCtxt(parser);
    return model;
}
References pcilib_error, and pcilib_info.
Referenced by pcilib_open().
pcilib_free_xml()
void pcilib_free_xml (pcilib_t * ctx)
Cleans up memory used by various XML structures.
Parameters
[in] ctx - the pcilib_t context
{
    int i;
    memset(ctx->xml.bank_nodes, 0, sizeof(ctx->xml.bank_nodes));
    for (i = 0; i < ctx->num_banks; i++) {
        if (ctx->bank_ctx[i])
            ctx->bank_ctx[i]->xml = NULL;
    }
    for (i = 0; i < ctx->num_reg; i++) {
        ctx->register_ctx[i].xml = NULL;
    }
    for (i = 0; i < ctx->xml.num_files; i++) {
        if (ctx->xml.docs[i]) {
            xmlFreeDoc(ctx->xml.docs[i]);
            ctx->xml.docs[i] = NULL;
        }
        if (ctx->xml.xpath[i]) {
            xmlXPathFreeContext(ctx->xml.xpath[i]);
            ctx->xml.xpath[i] = NULL;
        }
    }
    ctx->xml.num_files = 0;
    if (ctx->xml.validator) {
        xmlSchemaFreeValidCtxt(ctx->xml.validator);
        ctx->xml.validator = NULL;
    }
    if (ctx->xml.schema) {
        xmlSchemaFree(ctx->xml.schema);
        ctx->xml.schema = NULL;
    }
    if (ctx->xml.parts_validator) {
        xmlSchemaFreeValidCtxt(ctx->xml.parts_validator);
        ctx->xml.parts_validator = NULL;
    }
    if (ctx->xml.parts_schema) {
        xmlSchemaFree(ctx->xml.parts_schema);
        ctx->xml.parts_schema = NULL;
    }
    if (ctx->xml.parser) {
        xmlFreeParserCtxt(ctx->xml.parser);
        ctx->xml.parser = NULL;
    }
    /*
        xmlSchemaCleanupTypes();
        xmlCleanupParser();
        xmlMemoryDump();
    */
}
References pcilib_s::bank_ctx, pcilib_xml_s::bank_nodes, pcilib_xml_s::docs, pcilib_s::num_banks, pcilib_xml_s::num_files, pcilib_s::num_reg, pcilib_xml_s::parser, pcilib_xml_s::parts_schema, pcilib_xml_s::parts_validator, pcilib_s::register_ctx, pcilib_xml_s::schema, pcilib_xml_s::validator, pcilib_register_bank_context_s::xml, pcilib_s::xml, pcilib_register_context_t::xml, and pcilib_xml_s::xpath.
Referenced by pcilib_close().
pcilib_get_xml_attr()
int pcilib_get_xml_attr (pcilib_t * ctx, pcilib_xml_node_t * node, const char * attr, pcilib_value_t * val)
This is an internal function which returns a specified node attribute in the pcilib_value_t structure.
This function should not be used directly. Instead subsystem specific calls like pcilib_get_register_attr, pcilib_get_property_attr, ...have to be used.
Parameters
[in] ctx - pcilib context
[in] node - LibXML2 node
[in] attr - attribute name
[out] val - the result will be returned in this variable. Prior to first usage pcilib_value_t variable should be initalized to 0.
Returns
- error or 0 on success
{
    xmlAttr *prop;
    xmlChar *str;
    prop = xmlHasProp(node, BAD_CAST attr);
    if ((!prop)||(!prop->children)) return PCILIB_ERROR_NOTFOUND;
    str = prop->children->content;
    return pcilib_set_value_from_static_string(ctx, val, (const char*)str);
}
References PCILIB_ERROR_NOTFOUND, and pcilib_set_value_from_static_string().
Referenced by pcilib_get_property_attr(), pcilib_get_register_attr_by_id(), and pcilib_get_register_bank_attr_by_id().
pcilib_init_xml()
int pcilib_init_xml (pcilib_t * ctx, const char * model)
Initializes XML stack and loads a default set of XML files.
The default location for XML files is /usr/local/share/pcilib/models/model. This can be altered using CMake PCILIB_MODEL_DIR variable while building or using PCILIB_MODEL_DIR environmental variable dynamicly. More XML files can be added later using pcilib_process_xml() call.
Parameters
[in,out] ctx - pcilib context
[in] model - the name of the model
Returns
- error or 0 on success
{
    int err;
    char *model_dir;
    model_dir = getenv("PCILIB_MODEL_DIR");
    if (!model_dir) model_dir = PCILIB_MODEL_DIR;
    ctx->xml.parser = xmlNewParserCtxt();
    if (!ctx->xml.parser) {
        xmlErrorPtr xmlerr = xmlGetLastError();
        if (xmlerr) pcilib_error("xmlNewParserCtxt reported error %d (%s)", xmlerr->code, xmlerr->message);
        else pcilib_error("Failed to create an XML parser context");
        return PCILIB_ERROR_FAILED;
    }
    err = pcilib_xml_load_xsd(ctx, model_dir);
    if (err) return err;
    return pcilib_process_xml_internal(ctx, model, NULL);
}
References pcilib_xml_s::parser, pcilib_error, PCILIB_ERROR_FAILED, and pcilib_s::xml.
Referenced by pcilib_open().
pcilib_process_xml()
int pcilib_process_xml (pcilib_t * ctx, const char * location)
Processes a bunch of XML files in the specified directory.
During the initialization, all XML files in the corresponding model directory will be loaded. This function allows to additionally load XML files from the specified subdirectories of the model directory. I.e. the XML files from the /usr/local/share/pcilib/models/current_model/location will be loaded. As with pcilib_init_xml, the directory can be adjusted using CMake build configuration or PCILIB_MODEL_DIR environmental variable.
Parameters
[in] ctx - pcilib context
[in] location - Specifies sub-directory with XML files relative to the model directory.
Returns
- error or 0 on success
{
    return pcilib_process_xml_internal(ctx, NULL, location);
}